import React from 'react';
import { Container, Box, Typography, Grid, Card, CardContent, useTheme, alpha } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import MarketingLayout from '../../components/marketing/MarketingLayout';
import PageHeader from '../../components/marketing/PageHeader';
import CTASection from '../../components/marketing/CTASection';
import ImagePlaceholder from '../../components/marketing/ImagePlaceholder';
import {
  TrendingUp as TrendingUpIcon,
  Equalizer as EqualizerIcon,
  Event as EventIcon,
  Business as BusinessIcon,
  Psychology as PsychologyIcon,
  Timeline as TimelineIcon,
  Calculate as CalculateIcon,
  Assessment as AssessmentIcon,
  BarChart as BarChartIcon,
} from '@mui/icons-material';

const InvestmentTools = () => {
  const theme = useTheme();
  const navigate = useNavigate();

  const tools = [
    {
      icon: <TrendingUpIcon />,
      title: 'Trading Signals',
      description: 'Daily buy signals generated by a six-tier filter: market health, Minervini trend template, Stage 2 uptrend, fundamental quality, portfolio constraints, and advanced technical screens. Only the highest-conviction setups pass.',
      link: '/app/trading-signals',
      badge: 'Core',
    },
    {
      icon: <EqualizerIcon />,
      title: 'Stock Scores Dashboard',
      description: 'Multi-factor composite scores for every stock in our 5,300+ universe. Rank and filter by earnings quality, valuation, momentum, trend strength, and fundamental health. See at a glance which stocks are in the best shape right now.',
      link: '/app/scores',
      badge: 'Core',
    },
    {
      icon: <TimelineIcon />,
      title: 'Swing Candidates',
      description: 'Near-term momentum candidates filtered for tight consolidations, volume breakouts, and technical setups aligned with broader market conditions. Updated daily with entry criteria and risk parameters.',
      link: '/app/swing',
      badge: null,
    },
    {
      icon: <EventIcon />,
      title: 'Earnings Calendar & Analysis',
      description: 'Track upcoming earnings with historical surprise data, analyst estimate revisions, and earnings momentum scores. Identify stocks with consistent positive surprises and accelerating estimate trends.',
      link: '/app/earnings',
      badge: null,
    },
    {
      icon: <BarChartIcon />,
      title: 'Market Health & Breadth',
      description: 'Daily market health scoring using advance/decline breadth, distribution day counts, VIX analysis, and SPY/market structure. The same data the orchestrator uses to decide whether conditions favor new entries.',
      link: '/app/markets',
      badge: null,
    },
    {
      icon: <AssessmentIcon />,
      title: 'Sector Analysis',
      description: 'Relative strength rankings across all major sectors. Identify which sectors are leading, which are rotating in, and which are distribution targets. Critical for position sizing and directional bias.',
      link: '/app/sectors',
      badge: null,
    },
    {
      icon: <PsychologyIcon />,
      title: 'Sentiment Indicators',
      description: 'Institutional sentiment tracking using analyst positioning, upgrade/downgrade flows, and market psychology indicators. Useful for identifying when consensus positioning is extreme&#8212;often a contrarian signal.',
      link: '/app/sentiment',
      badge: null,
    },
    {
      icon: <CalculateIcon />,
      title: 'Pre-Trade Simulator',
      description: 'Simulate any trade before placing it. Input ticker, size, and entry price to see projected risk, position weight, and how the trade affects overall portfolio exposure and drawdown limits.',
      link: '/app/simulate',
      badge: null,
    },
  ];

  const methodology = [
    { step: '1', title: 'Market Gate', description: 'No new longs unless the broader market passes health checks: breadth, trend, and distribution day count all evaluated first.' },
    { step: '2', title: 'Trend Template', description: 'Each candidate must satisfy Minervini\'s 7-condition trend template: price above 150/200 SMA, 52-week range position, relative strength, and volume confirmation.' },
    { step: '3', title: 'Fundamental Filter', description: 'Quality screens for earnings growth, revenue acceleration, profit margins, and financial strength. No story stocks&#8212;fundamentals must support the price action.' },
    { step: '4', title: 'Signal Ranking', description: 'Survivors are scored and ranked by composite quality. Only the top-ranked candidates pass to the execution layer each day.' },
  ];

  return (
    <MarketingLayout>
      <PageHeader
        title="Investment Tools"
        subtitle="A complete toolkit for systematic, evidence-based investing&#8212;from signal generation to trade execution"
      />

      {/* Hero */}
      <Box sx={{ py: { xs: 8, md: 10 }, backgroundColor: theme.palette.background.default }}>
        <Container maxWidth="lg">
          <Grid container spacing={7} alignItems="center">
            <Grid item xs={12} md={6}>
              <Typography
                variant="overline"
                sx={{ color: theme.palette.primary.main, fontWeight: 700, letterSpacing: '3px', display: 'block', mb: 1.5 }}
              >
                Professional-Grade Analysis
              </Typography>
              <Typography
                variant="h3"
                sx={{
                  fontSize: { xs: '2rem', sm: '2.5rem', md: '3rem' },
                  fontWeight: 800,
                  mb: 3,
                  color: theme.palette.text.primary,
                  letterSpacing: '-0.5px',
                  lineHeight: 1.2,
                }}
              >
                Every Tool Serious Traders Actually Use
              </Typography>
              <Typography
                variant="body1"
                sx={{ fontSize: '1.1rem', color: theme.palette.text.secondary, lineHeight: 1.8, mb: 3 }}
              >
                Signals, scores, earnings, sentiment, sector rotation, market breadth,
                pre-trade simulation&#8212;the complete research stack that institutional
                desks run daily, available to individual investors for free.
              </Typography>
              <Typography
                variant="body1"
                sx={{ fontSize: '1rem', color: theme.palette.text.secondary, lineHeight: 1.8 }}
              >
                Everything is updated before market open and after market close,
                driven by a 24-loader automated data pipeline processing prices,
                technicals, fundamentals, and economic data every trading day.
              </Typography>
            </Grid>
            <Grid item xs={12} md={6}>
              <ImagePlaceholder
                src="https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=900&h=650&fit=crop&auto=format&q=80"
                alt="Trading signals and stock analysis dashboard"
                height={{ xs: '300px', md: '420px' }}
              />
            </Grid>
          </Grid>
        </Container>
      </Box>

      {/* Methodology Strip */}
      <Box
        sx={{
          py: { xs: 7, md: 8 },
          backgroundColor: alpha(theme.palette.primary.main, 0.04),
          borderTop: `1px solid ${theme.palette.divider}`,
          borderBottom: `1px solid ${theme.palette.divider}`,
        }}
      >
        <Container maxWidth="lg">
          <Box sx={{ textAlign: 'center', mb: 6 }}>
            <Typography
              variant="overline"
              sx={{ color: theme.palette.primary.main, fontWeight: 700, letterSpacing: '3px', display: 'block', mb: 1 }}
            >
              Signal Methodology
            </Typography>
            <Typography variant="h4" sx={{ fontWeight: 800, color: theme.palette.text.primary, mb: 1.5 }}>
              How Signals Are Generated
            </Typography>
            <Typography sx={{ color: theme.palette.text.secondary, fontSize: '1rem', maxWidth: '600px', mx: 'auto' }}>
              Every trading signal passes through a sequential four-stage filter. Miss any stage and the stock is rejected.
            </Typography>
          </Box>

          <Grid container spacing={3}>
            {methodology.map((item, idx) => (
              <Grid item xs={12} sm={6} md={3} key={idx}>
                <Box sx={{ position: 'relative' }}>
                  <Box
                    sx={{
                      position: 'absolute',
                      top: -1,
                      left: -1,
                      width: 44,
                      height: 44,
                      backgroundColor: theme.palette.primary.main,
                      color: '#fff',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontWeight: 900,
                      fontSize: '1.1rem',
                      zIndex: 1,
                    }}
                  >
                    {item.step}
                  </Box>
                  <Box
                    sx={{
                      pt: 5,
                      px: 3,
                      pb: 3,
                      border: `1px solid ${theme.palette.divider}`,
                      backgroundColor: theme.palette.background.paper,
                      height: '100%',
                    }}
                  >
                    <Typography variant="h6" sx={{ fontWeight: 700, mb: 1, color: theme.palette.text.primary, fontSize: '1rem' }}>
                      {item.title}
                    </Typography>
                    <Typography variant="body2" sx={{ color: theme.palette.text.secondary, lineHeight: 1.7 }}>
                      {item.description}
                    </Typography>
                  </Box>
                </Box>
              </Grid>
            ))}
          </Grid>
        </Container>
      </Box>

      {/* Tool Cards */}
      <Container maxWidth="lg" sx={{ py: { xs: 8, md: 10 } }}>
        <Box sx={{ textAlign: 'center', mb: 7 }}>
          <Typography
            variant="overline"
            sx={{ color: theme.palette.primary.main, fontWeight: 700, letterSpacing: '3px', display: 'block', mb: 1.5 }}
          >
            Platform Tools
          </Typography>
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: '1.9rem', sm: '2.3rem', md: '2.8rem' },
              fontWeight: 800,
              mb: 2,
              color: theme.palette.text.primary,
              letterSpacing: '-0.5px',
            }}
          >
            Eight Research Tools. One Platform.
          </Typography>
          <Typography sx={{ fontSize: '1.05rem', color: theme.palette.text.secondary, maxWidth: '580px', mx: 'auto', lineHeight: 1.8 }}>
            Everything updates daily. Everything is free.
          </Typography>
        </Box>

        <Grid container spacing={3}>
          {tools.map((tool, idx) => (
            <Grid item xs={12} sm={6} key={idx}>
              <Card
                onClick={() => navigate(tool.link)}
                sx={{
                  height: '100%',
                  border: `1px solid ${theme.palette.divider}`,
                  backgroundColor: theme.palette.background.paper,
                  borderRadius: '0px',
                  boxShadow: 'none',
                  cursor: 'pointer',
                  transition: 'all 0.25s ease',
                  '&:hover': {
                    boxShadow: '0 6px 20px rgba(0,0,0,0.09)',
                    borderColor: theme.palette.primary.main,
                    transform: 'translateY(-3px)',
                  },
                }}
              >
                <CardContent sx={{ p: 3.5 }}>
                  <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 2, mb: 2 }}>
                    <Box
                      sx={{
                        width: 40,
                        height: 40,
                        flexShrink: 0,
                        borderRadius: '0px',
                        backgroundColor: alpha(theme.palette.primary.main, 0.1),
                        color: theme.palette.primary.main,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        border: `1px solid ${alpha(theme.palette.primary.main, 0.2)}`,
                      }}
                    >
                      {tool.icon}
                    </Box>
                    <Box sx={{ flex: 1, minWidth: 0 }}>
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.5 }}>
                        <Typography variant="h6" sx={{ fontWeight: 700, color: theme.palette.primary.main, fontSize: '1.05rem' }}>
                          {tool.title}
                        </Typography>
                        {tool.badge && (
                          <Box
                            sx={{
                              px: 1,
                              py: 0.25,
                              fontSize: '0.65rem',
                              fontWeight: 700,
                              backgroundColor: theme.palette.primary.main,
                              color: '#fff',
                              borderRadius: '0px',
                              flexShrink: 0,
                            }}
                          >
                            {tool.badge}
                          </Box>
                        )}
                      </Box>
                    </Box>
                  </Box>
                  <Typography
                    variant="body2"
                    sx={{ color: theme.palette.text.secondary, lineHeight: 1.7 }}
                    dangerouslySetInnerHTML={{ __html: tool.description }}
                  />
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Container>

      <CTASection
        variant="dark"
        title="Start Using the Full Toolkit"
        subtitle="Trading signals, stock scores, earnings analysis, sector rotation, sentiment&#8212;all in one platform, completely free."
        primaryCTA={{ label: 'Launch Platform', link: '/app/markets' }}
        secondaryCTA={{ label: 'See Research Methodology', link: '/research-insights' }}
      />
    </MarketingLayout>
  );
};

export default InvestmentTools;
