"""PIPELINE_REMOVED_TABLES - tables intentionally excluded from health/freshness tracking.

Split out of the former flat algo_handlers/market.py (file-size-ratchet compliance split,
2026-09-05) so the constant lives in its own module; re-exported from
algo_handlers/market/__init__.py so existing callers (routes/algo.py,
algo_handlers/monitoring.py) require zero changes.
"""

from __future__ import annotations

from algo.monitoring.pipeline_health import PipelineHealth

# Tables intentionally removed from health tracking - these are optional enrichment only
# (not core to algo trading decisions). Excluding them prevents noise on the health panel.
# These are still populated by loaders but monitoring them isn't critical.
#
# Module-level (not local to _get_data_status) so other health/monitoring endpoints - e.g.
# monitoring.py's freshness/extended loader_health summary - can exclude the same tables.
# Before this was hoisted, monitoring.py's unhealthy-loader count had no such exclusion,
# so a table like algo_untracked_positions (excluded here, so it can NEVER appear in the
# DATA FRESHNESS table) could still be counted in the "Loader Health: N table(s) with
# issues (see Data Freshness Table below)" summary - pointing the user at a table list that
# structurally cannot contain the table being complained about. Confirmed live 2026-08-04.
PIPELINE_REMOVED_TABLES = {
    # Enrichment-only tables (Phase 1 halt logic doesn't depend on these)
    "price_monthly",
    "price_weekly",
    "etf_price_daily",
    "etf_price_weekly",
    "etf_price_monthly",
    # Signal variants (only daily equity signals matter; weekly/monthly/ETF are enrichment)
    "buy_sell_daily_etf",
    "buy_sell_weekly",
    "buy_sell_weekly_etf",
    "buy_sell_monthly",
    "buy_sell_monthly_etf",
    "signal_quality_scores",  # Enrichment; quality tracked via avg_strength in buy_sell_daily
    # SESSION 118 FIX: Restored visibility of metrics tables
    # These were hidden from health panel by Session 114 with rationale "enrichment-only",
    # but stakeholders need to know when optional data is 2+ days stale. Restored them to
    # the data status report (dashboard & monitor) while keeping them separate from
    # critical_tables (Phase 1/9 dependencies). Phase 1 may not halt on stale metrics,
    # but visible staleness = faster issue detection vs. silent rot behind an "everything OK" UI.
    "positioning_metrics",  # Re-added: institutional holdings data (daily). Was temporarily
    # removed with growth/quality/value metrics above but is different - it's computed from
    # 13F filings (quarterly updates), not daily SEC data like the metrics we restored.
    # Keep visible but acknowledge lower update cadence than growth/quality/value_metrics.
    # Economic data (not used in trading logic)
    "economic_data",
    # System/user tables
    "users",
    "user_alerts",
    "user_dashboard_settings",
    "user_api_keys",
    # Archive tables (historical only)
    "algo_trades_archive",
    # Utility tables
    "schema_version",
    "last_updated",
    "api_idempotency_cache",
    # Optional metrics (enrichment only)
    "economic_calendar",
    "earnings_calendar",
    "insider_transactions",
    "institutional_ownership",
    "stock_splits",
    "analyst_sentiment_analysis",
    "analyst_upgrade_downgrade",
    "aaii_sentiment",
    "naaim",
    "fear_greed_index",
    "commodity_correlations",
    "commodity_seasonality",
    "covered_call_opportunities",
    "credit_spreads",
    "vcp_patterns",
    "support_resistance_levels",
    "seasonality_day_of_week",
    "seasonality_monthly_stats",
    "ttm_cash_flow",
    "ttm_income_statement",
    "yfinance_ip_ban",
    "yfinance_snapshot",
    # Contact/community tables
    "contact_submissions",
    "community_signups",
    # ETF-specific (not algo-traded)
    "etf_symbols",
    # Alpha/ML archive (historical experiments)
    "algo_model_registry",
    "algo_champion_challenger",
    "algo_position_sizing_audit",
    "algo_stop_loss_audit",
    "algo_tca",
    "algo_trade_adds",
    "algo_trade_r_distribution",
    "algo_exit_rules_distribution",
    "algo_daily_return_histogram",  # Analytics table (empty)
    "algo_data_patrol",  # Analytics table (empty)
    "algo_holding_period_histogram",  # Analytics table (empty)
    "algo_orchestrator_state",  # Deprecated state table (empty, use orchestrator_runs instead)
    "alpaca_import_failures",
    "data_remediation_log",
    # Market/sector analysis (rarely updated or empty)
    "dividend_history",  # Historical data, not actively maintained
    "sector_correlation",  # Analytics table (empty)
    "sectors",  # Base lookup table (rarely changes)
    # Phase 9 outputs (only populated on successful complete orchestrator runs)
    "equity_curve_daily",  # Generated by Phase 9 - not always updated
    "portfolio_holdings",  # Manual/enrichment table (very stale)
    "positions_using_stale_fallback",  # Deprecated - empty
    "algo_untracked_positions",  # Empty from this morning's error run
    # Deprecated loaders (removed per DEPRECATED_LOADERS.md)
    "market_cap_computed",  # ORPHANED - load_market_cap_computed.py removed
    "price_extremes_52week",  # ORPHANED - load_price_extremes.py removed
    # Earnings table name mismatch (config calls it earnings_history_daily, actual table is earnings_history; loader writes to earnings_calendar_sec)
    "earnings_history",  # Legacy empty table - no loader writes to it (loader→earnings_calendar_sec)
    # Superseded tables (per algo/monitoring/pipeline_health.py's KNOWN_DEPRECATED_TABLES -
    # confirmed live 2026-07-27: 0 rows, no INSERT/UPDATE writer anywhere in the codebase)
    "sec_dividends",  # Superseded by dividend_data
    "sec_material_events",  # Superseded by current_reports_8k
    # Financeals (supplementary)
    "annual_balance_sheet",
    "annual_cash_flow",
    "annual_income_statement",
    "quarterly_balance_sheet",
    "quarterly_cash_flow",
    "quarterly_income_statement",
    "sec_valuations",
    # Misc
    "loader_execution_locks",
    "loader_sla_status",
    "filter_rejection_log",
    "signal_filter_tiers",
    "signal_rejection_log",
    "signal_trade_performance",
    "qualified_trades",
    "manual_positions",
} | PipelineHealth.KNOWN_DEPRECATED_TABLES
# ^ Unioned in rather than hand-duplicated: this set and algo/monitoring/pipeline_health.py's
# KNOWN_DEPRECATED_TABLES are both "tables with no writer, expected to sit frozen" allowlists,
# but were maintained as two independent literals. They drifted - sec_cash_flow_metrics
# (deprecated 2026-07-27) and algo_performance_metrics (confirmed dead 2026-08-10) were added
# to KNOWN_DEPRECATED_TABLES but never mirrored here, so this endpoint (the actual source for
# the dashboard's DATA FRESHNESS panel) kept reporting both as false STALE for weeks - confirmed
# live 2026-08-11 in the "5 stale" dashboard count. Unioning instead of copying means any future
# addition to KNOWN_DEPRECATED_TABLES can't silently drift out of sync with this list again.
