#!/usr/bin/env python3
"""Local development environment setup and coordinator.

Configures LOCAL_MODE, verifies database, and launches coordinated services.
Run once at startup to prepare dev environment.

Usage:
  python dev_environment_setup.py              # Setup and verify
  python dev_environment_setup.py --check      # Check status only
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo


def check_postgres() -> bool:
    """Verify PostgreSQL is running and accessible."""
    try:
        result = subprocess.run(
            ["python", "-c",
             "import psycopg2; c = psycopg2.connect('dbname=stocks user=stocks host=localhost'); print('OK'); c.close()"],
            capture_output=True,
            timeout=5
        )
        if result.returncode != 0:
            print(f"PostgreSQL check failed: {result.stderr}", file=sys.stderr)
        return result.returncode == 0
    except subprocess.TimeoutExpired:
        print("PostgreSQL check timed out (5s) - server may be slow or unresponsive", file=sys.stderr)
        return False
    except FileNotFoundError:
        print("PostgreSQL check failed: 'python' command not found", file=sys.stderr)
        return False
    except Exception as e:
        print(f"PostgreSQL check failed: {type(e).__name__}: {e}", file=sys.stderr)
        return False

def check_dev_server() -> bool:
    """Check if dev server is running on localhost:3001."""
    try:
        result = subprocess.run(
            ["curl", "-s", "http://localhost:3001/api/health"],
            capture_output=True,
            timeout=3
        )
        if result.returncode != 0:
            print(f"Dev server check failed: {result.stderr}", file=sys.stderr)
        return result.returncode == 0
    except subprocess.TimeoutExpired:
        print("Dev server check timed out (3s) - server may be slow or unresponsive", file=sys.stderr)
        return False
    except FileNotFoundError:
        print("Dev server check failed: 'curl' command not found", file=sys.stderr)
        return False
    except Exception as e:
        print(f"Dev server check failed: {type(e).__name__}: {e}", file=sys.stderr)
        return False

def setup_environment() -> None:
    """Set LOCAL_MODE and dev environment variables."""
    os.environ["LOCAL_MODE"] = "true"
    os.environ["ENVIRONMENT"] = "development"
    os.environ["ALPACA_PAPER_TRADING"] = "true"  # CRITICAL: Paper trading mode for local development
    # NOTE: SKIP_ORCHESTRATOR_LOCK removed - distributed lock prevents duplicate trades.

    # Write to .env.local for persistence
    env_file = Path(".env.local")
    env_content = """# Local development mode - auto-generated by dev_environment_setup.py
LOCAL_MODE=true
ENVIRONMENT=development
"""
    if not env_file.exists():
        env_file.write_text(env_content)
        print(f"✓ Created {env_file}")

def check_status() -> bool:
    """Check dev environment status."""
    et = ZoneInfo("America/New_York")
    now = datetime.now(et)

    print("\n" + "="*70)
    print("LOCAL DEVELOPMENT ENVIRONMENT STATUS")
    print("="*70)
    print(f"Time: {now.strftime('%Y-%m-%d %H:%M:%S %Z')}")
    print(f"LOCAL_MODE: {os.getenv('LOCAL_MODE', 'NOT SET')}")
    print()

    checks = []

    # PostgreSQL
    print("[DB] Database...", end=" ", flush=True)
    pg_ok = check_postgres()
    print("[OK]" if pg_ok else "[FAIL]")
    checks.append(("PostgreSQL", pg_ok))

    # Dev Server
    print("[API] Dev Server (localhost:3001)...", end=" ", flush=True)
    dev_ok = check_dev_server()
    print("[OK]" if dev_ok else "[NOT RUNNING]")
    checks.append(("Dev Server", dev_ok))

    # Data freshness
    if pg_ok:
        print("[DATA] Data Freshness...", end=" ", flush=True)
        try:
            result = subprocess.run(
                ["python", "check_system_health.py"],
                capture_output=True,
                text=True,
                timeout=10
            )
            if "[FAIL]" not in result.stdout:
                print("[OK]")
                checks.append(("Data Freshness", True))
            else:
                print("[WARN - Data stale]")
                checks.append(("Data Freshness", False))
        except Exception as e:
            print(f"[ERROR - {e}]")
            checks.append(("Data Freshness", False))

    # Dashboard module
    print("[UI] Dashboard Module...", end=" ", flush=True)
    try:
        result = subprocess.run(
            ["python", "-c", "from dashboard import Dashboard; print('OK')"],
            capture_output=True,
            timeout=5
        )
        if result.returncode == 0:
            print("[OK]")
            checks.append(("Dashboard", True))
        else:
            print("[FAIL]")
            error_msg = result.stderr if result.stderr else result.stdout
            print(f"Dashboard import failed: {error_msg}", file=sys.stderr)
            checks.append(("Dashboard", False))
    except subprocess.TimeoutExpired:
        print("[ERROR - timeout]")
        print("Dashboard import check timed out (5s)", file=sys.stderr)
        checks.append(("Dashboard", False))
    except Exception as e:
        print("[ERROR]")
        print(f"Dashboard import check failed: {type(e).__name__}: {e}", file=sys.stderr)
        checks.append(("Dashboard", False))

    # Summary
    passed = sum(1 for _, ok in checks if ok)
    print()
    print("="*70)
    print(f"Status: {passed}/{len(checks)} checks passed")
    print("="*70)

    if passed == len(checks):
        print("\n[OK] All systems ready! You can now:")
        print("   • Run orchestrator: python scripts/run_local_orchestrator.py")
        print("   • Refresh data: cd loaders && python load_prices.py")
        print("   • Start dashboard: python dashboard.py --local")
        return True
    else:
        print("\n[WARN] Some systems not ready:")
        for name, ok in checks:
            if not ok:
                if name == "PostgreSQL":
                    print(f"   • {name}: Run: psql dbname=stocks")
                elif name == "Dev Server":
                    print(f"   • {name}: Run: python lambda/api/dev_server.py")
                elif name == "Data Freshness":
                    print(f"   • {name}: Run loaders: cd loaders && python load_prices.py")
                else:
                    print(f"   • {name}: Check installation")
        return False

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Setup local development environment"
    )
    parser.add_argument(
        "--check", action="store_true", help="Check status only (don't modify)"
    )
    args = parser.parse_args()

    if args.check:
        success = check_status()
        sys.exit(0 if success else 1)
    else:
        print("Setting up local development environment...")
        setup_environment()
        success = check_status()
        sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
