# Dockerfile.info
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.info requirements-loadinfo.txt loadinfo.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadinfo.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadinfo.py"]
