# Dockerfile.technicalsdaily
FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements-loadtechnicalsdaily.txt .
RUN pip install --no-cache-dir -r requirements-loadtechnicalsdaily.txt

# Copy script
COPY loadtechnicalsdaily.py .

ENTRYPOINT ["python", "loadtechnicalsdaily.py"]
