ARG REGISTRY=python
ARG TAG=3.11-slim
FROM ${REGISTRY}:${TAG}

WORKDIR /app

# Copy requirements and script
COPY requirements-loadbuysell_etf_daily.txt .
COPY loadbuysell_etf_daily.py .

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadbuysell_etf_daily.txt

# Set the entrypoint
ENV PYTHONUNBUFFERED=1
ENV AWS_DEFAULT_REGION=us-east-1
ENTRYPOINT ["python", "-u", "loadbuysell_etf_daily.py"]
