FROM python:3.9-slim

WORKDIR /app

COPY requirements-loadquarterlybalancesheet.txt .
RUN pip install --no-cache-dir -r requirements-loadquarterlybalancesheet.txt

COPY loadquarterlybalancesheet.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "loadquarterlybalancesheet.py"]
