FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      gcc \
      libpq-dev \
      libssl-dev \
      libffi-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-loadlatestbuysellweekly.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadlatestbuysellweekly.txt

COPY loadlatestbuysellweekly.py .
CMD ["python", "loadlatestbuysellweekly.py"]