# Dockerfile.loadearningshistory
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY requirements-loadearningshistory.txt loadearningshistory.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadearningshistory.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadearningshistory.py"]
# Trigger Mon Oct 7 02:20 CDT 2025 - Deploy earnings loaders to fix calendar API
