# Dockerfile.pricedaily
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

# install Python dependencies for loadpricedaily.py
COPY requirements-loadlatestpricedaily.txt .
RUN pip install --no-cache-dir -r requirements-loadlatestpricedaily.txt

# copy and run the price-daily loader script
COPY loadlatestpricedaily.py .
ENTRYPOINT ["python", "loadlatestpricedaily.py"]
