# Dockerfile.latesttechnicalsdaily
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

# Install dependencies
COPY requirements-loadlatesttechnicalsdaily.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadlatesttechnicalsdaily.txt

# Copy script
COPY loadlatesttechnicalsdaily.py .

ENTRYPOINT ["python", "loadlatesttechnicalsdaily.py"]
# Trigger rebuild Mon Oct  6 13:53:02 CDT 2025
# Trigger rebuild Mon Oct  6 14:13:22 CDT 2025
