FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      gcc \
      libpq-dev \
      libssl-dev \
      libffi-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-loadsentiment_realtime.txt .
RUN pip install --no-cache-dir -r requirements-loadsentiment_realtime.txt

COPY loadsentiment_realtime.py .
CMD ["python", "loadsentiment_realtime.py"]