FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      gcc \
      libpq-dev \
      libssl-dev \
      libffi-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-loadanalystupgradedowngrade.txt .
RUN pip install --no-cache-dir -r requirements-loadanalystupgradedowngrade.txt

COPY loadanalystupgradedowngrade.py .
CMD ["python", "loadanalystupgradedowngrade.py"]