ARG REGISTRY=python
ARG TAG=3.11-slim
FROM ${REGISTRY}:${TAG}

WORKDIR /app

# Copy requirements and script
COPY requirements-loadcommodities.txt .
COPY loadcommodities.py .

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadcommodities.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadcommodities.py"]
