# Dockerfile.pricedaily
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

# install Python dependencies for loadpricedaily.py
COPY requirements-loadpricedaily.txt .
RUN pip install --no-cache-dir -r requirements-loadpricedaily.txt

# copy and run the price-daily loader script
COPY loadpricedaily.py .
ENTRYPOINT ["python", "loadpricedaily.py"]
