FROM python:3.9-slim

WORKDIR /app

COPY requirements-loadbalancesheet.txt .
RUN pip install --no-cache-dir -r requirements-loadbalancesheet.txt

COPY loadbalancesheet.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "loadbalancesheet.py"]
