# Dockerfile.financials
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.financials requirements-loadfinancials.txt loadfinancials.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadfinancials.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadfinancials.py"]
