FROM python:3.9-slim

WORKDIR /app

COPY requirements-loadrecommendations.txt .
RUN pip install --no-cache-dir -r requirements-loadrecommendations.txt

COPY loadrecommendations.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "loadrecommendations.py"]
