ARG REGISTRY=python
ARG TAG=3.11-slim
FROM ${REGISTRY}:${TAG}

WORKDIR /app

# Copy requirements and script
COPY requirements-loaddailycompanydata.txt .
COPY loaddailycompanydata.py .

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loaddailycompanydata.txt

# Set the entrypoint
ENTRYPOINT ["python", "loaddailycompanydata.py"]
