FROM python:3.11-slim
WORKDIR /app
COPY loadlatestpricedaily.py .
COPY requirements-loadlatestpricedaily.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "loadlatestpricedaily.py"]
