ARG ECR_REGISTRY
FROM ${ECR_REGISTRY}:base-loader-latest
COPY loadearningsrevisions.py /app/
COPY requirements-loadearningsrevisions.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
ENTRYPOINT ["python", "/app/loadearningsrevisions.py"]
