# Use a small Python base image
FROM python:3.10-slim

# Set our working directory
WORKDIR /app

# Copy and install Python dependencies
COPY requirements-loadearnings.txt .
RUN pip install --no-cache-dir -r requirements-loadearnings.txt


# Copy the loader script to the image
COPY loadearnings.py ./

# Default command
CMD ["python", "-u", "loadearnings.py"]
