# Dockerfile.technicalsmonthly
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

# Install dependencies
COPY requirements-loadtechnicalsmonthly.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadtechnicalsmonthly.txt

# Copy script
COPY loadtechnicalsmonthly.py .

ENTRYPOINT ["python", "loadtechnicalsmonthly.py"]
