FROM python:3.11-slim

WORKDIR /app

COPY requirements-loadstocksymbols.txt ./
RUN pip install --no-cache-dir -r requirements-loadstocksymbols.txt

COPY loadstocksymbols.py ./

CMD ["python", "-u", "loadstocksymbols.py"]
