FROM python:3.9-slim

WORKDIR /app

COPY requirements-loadquarterlycashflow.txt .
RUN pip install --no-cache-dir -r requirements-loadquarterlycashflow.txt

COPY loadquarterlycashflow.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "loadquarterlycashflow.py"]
