# Dockerfile.loadearningsestimate
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

COPY Dockerfile.loadearningsestimate requirements-loadearningsestimate.txt loadearningsestimate.py ./

RUN pip install --no-cache-dir -r requirements-loadearningsestimate.txt

# Run as non-root
USER 1000

ENTRYPOINT ["python", "loadearningsestimate.py"]
