# Dockerfile.riskmetrics
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.riskmetrics requirements-loadriskmetrics.txt loadriskmetrics.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadriskmetrics.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadriskmetrics.py"]
