# Dockerfile.priceweekly
FROM python:3.11-slim

WORKDIR /app

# install Python dependencies for loadpriceweekly.py
COPY requirements-loadlatestpriceweekly.txt .
RUN pip install --no-cache-dir -r requirements-loadlatestpriceweekly.txt

# copy and run the price-weekly loader script
COPY loadlatestpriceweekly.py .
ENTRYPOINT ["python", "loadlatestpriceweekly.py"]
