# Dockerfile.pricemonthly
FROM python:3.11-slim

WORKDIR /app

# install Python dependencies for loadpricemonthly.py
COPY requirements-loadlatestpricemonthly.txt .
RUN pip install --no-cache-dir -r requirements-loadlatestpricemonthly.txt

# copy and run the price-monthly loader script
COPY loadlatestpricemonthly.py .
ENTRYPOINT ["python", "loadlatestpricemonthly.py"]
