# Dockerfile.technicalsweekly
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements-loadtechnicalsweekly.txt .
RUN pip install --no-cache-dir -r requirements-loadtechnicalsweekly.txt

# Copy script
COPY loadtechnicalsweekly.py .

ENTRYPOINT ["python", "loadtechnicalsweekly.py"]
