# Dockerfile.technicalsweekly
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

# Install dependencies
COPY requirements-loadtechnicalsweekly.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadtechnicalsweekly.txt

# Copy script
COPY loadtechnicalsweekly.py .

ENTRYPOINT ["python", "loadtechnicalsweekly.py"]
