FROM python:3.9-slim

WORKDIR /app

COPY requirements-loadepsrevisions.txt .
RUN pip install --no-cache-dir -r requirements-loadepsrevisions.txt

COPY loadepsrevisions.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "loadepsrevisions.py"]
