# Dockerfile.priceweekly
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

# install Python dependencies for loadpriceweekly.py
COPY requirements-loadpricemonthly.txt .
RUN pip install --no-cache-dir -r requirements-loadpricemonthly.txt

# copy and run the price-weekly loader script
COPY loadpricemonthly.py .
ENTRYPOINT ["python", "loadpricemonthly.py"]
