# Dockerfile.dailycompanydata
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.dailycompanydata requirements-loaddailycompanydata.txt loaddailycompanydata.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loaddailycompanydata.txt

# Set the entrypoint
ENTRYPOINT ["python", "loaddailycompanydata.py"]
