# Dockerfile.latesttechnicalsdaily
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

# Install dependencies
COPY requirements-loadlatesttechnicalsdaily.txt .
RUN pip install --no-cache-dir -r requirements-loadlatesttechnicalsdaily.txt

# Copy script
COPY loadlatesttechnicalsdaily.py .

ENTRYPOINT ["python", "loadlatesttechnicalsdaily.py"]
