# Dockerfile.aaii
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY requirements-loadaaiidata.txt loadaaiidata.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadaaiidata.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadaaiidata.py"]
