# Dockerfile.fundamentalmetrics
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.fundamentalmetrics requirements-loadfundamentalmetrics.txt loadfundamentalmetrics.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadfundamentalmetrics.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadfundamentalmetrics.py"]
