FROM python:3.11-slim

WORKDIR /app
COPY requirements-loadrevenueestimate.txt .
RUN pip install -r requirements-loadrevenueestimate.txt

COPY loadrevenueestimate.py .

ENTRYPOINT ["python", "loadrevenueestimate.py"]
