FROM python:3.11-slim
WORKDIR /app
COPY loadlatestpriceweekly.py .
COPY requirements-loadlatestpricemonthly.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "loadlatestpriceweekly.py"]
