# Dockerfile.buyselldaily
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.buyselldaily requirements-loadbuysell.txt loadbuyselldaily.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadbuysell.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadbuyselldaily.py"] 