FROM python:3.9-slim

WORKDIR /app

COPY requirements-loadcashflow.txt .
RUN pip install --no-cache-dir -r requirements-loadcashflow.txt

COPY loadcashflow.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "loadcashflow.py"]
