# Dockerfile.loadearnings
FROM python:3.9-slim

WORKDIR /app

COPY Dockerfile.loadearnings requirements.txt loadearnings.py ./

RUN pip install --no-cache-dir -r requirements.txt

# Run as non-root
USER 1000

ENTRYPOINT ["python", "loadearnings.py"]
