# Dockerfile.latesttechnicalsmonthly
FROM python:3.11-slim

# Set environment variables to suppress pip warnings
ENV PIP_ROOT_USER_ACTION=ignore \
    PIP_DISABLE_PIP_VERSION_CHECK=1


WORKDIR /app

# Install dependencies
COPY requirements-loadlatesttechnicalsmonthly.txt .
RUN pip install --no-cache-dir -r requirements-loadlatesttechnicalsmonthly.txt

# Copy script
COPY loadlatesttechnicalsmonthly.py .

ENTRYPOINT ["python", "loadlatesttechnicalsmonthly.py"]
