# Dockerfile.loadearningsestimate
FROM python:3.11-slim

WORKDIR /app

COPY Dockerfile.loadearningsestimate requirements-loadearningsestimate.txt loadearningsestimate.py ./

RUN pip install --no-cache-dir -r requirements-loadearningsestimate.txt

# Run as non-root
USER 1000

ENTRYPOINT ["python", "loadearningsestimate.py"]
