# Use a small Python base image
FROM python:3.10-slim

# Set our working directory
WORKDIR /app

# Copy and install Python dependencies
COPY requirements-loadbuysell.txt .
RUN pip install --no-cache-dir -r requirements-loadbuysell.txt


# Default command
CMD ["python", "-u", "loadbuysell.py"]
