# Dockerfile.keystats
FROM python:3.9-slim

WORKDIR /app

# Install Python dependencies
COPY requirements-loadkeystats.txt .
RUN pip install --no-cache-dir -r requirements-loadkeystats.txt

# Copy script
COPY loadkeystats.py .

ENTRYPOINT ["python", "loadkeystats.py"]
