ARG REGISTRY=python
ARG TAG=3.11-slim
FROM ${REGISTRY}:${TAG}

WORKDIR /app

# Copy requirements and script
COPY requirements-loadfundamentalmetrics.txt .
COPY loadfundamentalmetrics.py .

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadfundamentalmetrics.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadfundamentalmetrics.py"]
