# Dockerfile.loadsymbols
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.loadsymbols requirements-loadsymbols.txt loadsymbols.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadsymbols.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadsymbols.py"]