# Dockerfile.pricedaily
FROM python:3.9-slim

WORKDIR /app

# install Python dependencies for loadpricedaily.py
COPY requirements-pricedaily.txt .
RUN pip install --no-cache-dir -r requirements-pricedaily.txt

# copy and run the price-daily loader script
COPY loadpricedaily.py .
ENTRYPOINT ["python", "loadpricedaily.py"]
