# Dockerfile.loadanalystupgradedowngrade
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.loadanalystupgradedowngrade requirements-loadanalystupgradedowngrade.txt loadanalystupgradedowngrade.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadanalystupgradedowngrade.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadanalystupgradedowngrade.py"]# Trigger rebuild Mon Oct  6 13:52:53 CDT 2025
