# Dockerfile.loadearningsestimate
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.loadearningsestimate requirements-loadearningsestimate.txt loadearningsestimate.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadearningsestimate.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadearningsestimate.py"]
