# Dockerfile.priceweekly
FROM python:3.10-slim

WORKDIR /app

# install Python dependencies for loadpriceweekly.py
COPY requirements-loadpricemonthly.txt .
RUN pip install --no-cache-dir -r requirements-loadpricemonthly.txt

# copy and run the price-weekly loader script
COPY loadpricemonthly.py .
ENTRYPOINT ["python", "loadpricemonthly.py"]
