FROM python:3.11-slim
WORKDIR /app
COPY loadlatestpricemonthly.py .
COPY requirements-loadlatestpricemonthly.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "loadlatestpricemonthly.py"]
