ARG ECR_REGISTRY
FROM ${ECR_REGISTRY}:base-loader-latest
WORKDIR /app
COPY loadearningsrevisions.py .
COPY requirements-loadearningsrevisions.txt .
RUN pip install --no-cache-dir -r requirements-loadearningsrevisions.txt
ENTRYPOINT ["python", "loadearningsrevisions.py"]
