# Dockerfile.positioning
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.positioning requirements-loadpositioning.txt loadpositioning.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadpositioning.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadpositioning.py"]
