# Dockerfile.sectordata
FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements and script
COPY Dockerfile.sectordata requirements-loadsectordata.txt loadsectordata.py ./

# Install the requirements
RUN --mount=type=cache,target=/root/.cache/pip pip install --prefer-binary -r requirements-loadsectordata.txt

# Set the entrypoint
ENTRYPOINT ["python", "loadsectordata.py"]
