FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      gcc \
      libpq-dev \
      libssl-dev \
      libffi-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-loadsentiment.txt .
RUN pip install --no-cache-dir -r requirements-loadsentiment.txt

COPY loadsentiment.py .
CMD ["python", "loadsentiment.py"]