AWSTemplateFormatVersion: '2010-09-09'
Description: loadstocksymbols λ – download & load symbols into Postgres RDS

Parameters:
  CodeKey:
    Type: String
    Description: S3 key of the Lambda ZIP

  DBPassword:
    Type: String
    NoEcho: true
    Description: RDS master password

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Lambda SG in stocks VPC"
      VpcId: !ImportValue network-VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  LoadStockSymbolsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: loadstocksymbols
      Runtime: python3.9
      Handler: loadstocksymbols.handler
      Role: !ImportValue iam-RoleArn
      Code:
        S3Bucket: !ImportValue storage-CodeBucketName
        S3Key:    !Ref CodeKey
      Timeout: 300
      VpcConfig:
        SubnetIds: !Split [",", !ImportValue network-PrivateSubnets]
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
      Environment:
        Variables:
          DB_ENDPOINT: !ImportValue rds-DBEndpoint
          DB_PORT:     !ImportValue rds-DBPort
          DB_USER:     "rds_username"
          DB_PASS:     !Ref DBPassword
          DB_NAME:     "stocks"

Outputs:
  FunctionArn:
    Description: "ARN of the loadstocksymbols Lambda"
    Value: !GetAtt LoadStockSymbolsFunction.Arn
    Export:
      Name: lambda-loadstocksymbols-FunctionArn
