# File: rds-template.yml

AWSTemplateFormatVersion: '2010-09-09'
Description: rds-stack — Postgres RDS using credentials from Secrets Manager

Parameters:
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
    Description: RDS instance class (free-tier)

  DBAllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage (GiB)

Resources:
  StocksDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Select [0, !Split [",", !ImportValue network-PrivateSubnets]]
        - !Select [1, !Split [",", !ImportValue network-PrivateSubnets]]

  StocksDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: stocks-db
      AllocatedStorage:   !Ref DBAllocatedStorage
      DBInstanceClass:    !Ref DBInstanceClass
      Engine:             postgres
      MasterUsername:     "{{resolve:secretsmanager:stocks-db-credentials:SecretString:username}}"
      MasterUserPassword: "{{resolve:secretsmanager:stocks-db-credentials:SecretString:password}}"
      VPCSecurityGroups:
        - !ImportValue network-DBSecurityGroupId
      DBSubnetGroupName:  !Ref StocksDBSubnetGroup
      MultiAZ:            false
      PubliclyAccessible: false
      DeletionProtection: false

Outputs:
  DBEndpoint:
    Description: RDS endpoint address
    Value: !GetAtt StocksDBInstance.Endpoint.Address
    Export:
      Name: rds-DBEndpoint

  DBPort:
    Description: RDS endpoint port
    Value: !GetAtt StocksDBInstance.Endpoint.Port
    Export:
      Name: rds-DBPort
