#!/usr/bin/env python3
"""
Interactive Setup — Configure alerts programmatically

Prompts for credentials, validates, writes .env.local, tests everything.
Safe: checks existing env vars, validates inputs, backs up old .env.local
"""

import os
import sys
import getpass
from pathlib import Path
from dotenv import load_dotenv

def print_header(text):
    """Print section header."""
    print(f"\n{'='*70}")
    print(f"  {text}")
    print(f"{'='*70}\n")

def print_success(text):
    """Print success message."""
    print(f"  ✓ {text}")

def print_error(text):
    """Print error message."""
    print(f"  ✗ {text}")

def prompt(question, default=None, secret=False):
    """Prompt user for input."""
    if default:
        prompt_text = f"  {question} [{default}]: "
    else:
        prompt_text = f"  {question}: "

    if secret:
        value = getpass.getpass(prompt_text)
    else:
        value = input(prompt_text)

    return value.strip() if value else default

def validate_email(email):
    """Basic email validation."""
    return '@' in email and '.' in email.split('@')[-1]

def validate_phone(phone):
    """Validate phone number format."""
    # Accept: +1-312-307-8620, +13123078620, 13123078620, etc
    digits = ''.join(c for c in phone if c.isdigit())
    return len(digits) >= 10

def validate_gmail_password(pwd):
    """Validate Gmail app password (16 chars, letters+digits+space)."""
    pwd_clean = pwd.replace(' ', '')
    return len(pwd_clean) == 16

def load_existing_env():
    """Load existing .env.local if it exists."""
    env_file = Path('.env.local')
    if env_file.exists():
        load_dotenv(env_file)
        return True
    return False

def write_env(config):
    """Write configuration to .env.local."""
    env_file = Path('.env.local')

    # Backup existing
    if env_file.exists():
        backup = env_file.with_suffix('.local.bak')
        env_file.rename(backup)
        print_success(f"Backed up existing to {backup.name}")

    # Write new
    content = f"""# Algo Monitoring Configuration
# Generated by setup.py — {__import__('datetime').datetime.now().isoformat()}
# Never commit this file (it's in .gitignore)

# ============================================================
# EMAIL ALERTS (Required)
# ============================================================
ALERT_EMAIL_FROM={config['email_from']}
ALERT_EMAIL_TO={config['email_to']}
ALERT_SMTP_HOST=smtp.gmail.com
ALERT_SMTP_PORT=587
ALERT_SMTP_USER={config['smtp_user']}
ALERT_SMTP_PASSWORD={config['smtp_password']}

# ============================================================
# SMS ALERTS (Optional)
# ============================================================
TWILIO_ACCOUNT_SID={config.get('twilio_sid', '')}
TWILIO_AUTH_TOKEN={config.get('twilio_token', '')}
TWILIO_PHONE_NUMBER={config.get('twilio_number', '')}
ALERT_PHONE_NUMBERS={config.get('alert_phone', '+1-312-307-8620')}

# ============================================================
# SLACK ALERTS (Optional)
# ============================================================
ALERT_WEBHOOK_URL={config.get('slack_webhook', '')}

# ============================================================
# DATABASE (Optional — usually already set)
# ============================================================
DB_HOST={os.getenv('DB_HOST', 'localhost')}
DB_PORT={os.getenv('DB_PORT', '5432')}
DB_USER={os.getenv('DB_USER', 'stocks')}
DB_PASSWORD={os.getenv('DB_PASSWORD', '')}
DB_NAME={os.getenv('DB_NAME', 'stocks')}

# ============================================================
# ALPACA (Optional — usually already set)
# ============================================================
APCA_API_KEY_ID={os.getenv('APCA_API_KEY_ID', '')}
APCA_API_SECRET_KEY={os.getenv('APCA_API_SECRET_KEY', '')}
APCA_API_BASE_URL={os.getenv('APCA_API_BASE_URL', 'https://paper-api.alpaca.markets')}
"""

    env_file.write_text(content)
    env_file.chmod(0o600)  # Restrict to owner only
    print_success(f"Configuration written to .env.local (mode 600)")

def test_alerts(config):
    """Test alert configuration."""
    print_header("Testing Alerts")

    try:
        from algo_alerts import AlertManager

        # Update env with new config
        for key, val in config.items():
            if val:
                os.environ[key.upper()] = val

        alerts = AlertManager()

        print("  Email:")
        print(f"    From: {alerts.email_from}")
        print(f"    To: {', '.join(alerts.email_to) if alerts.email_to else '(none)'}")

        if alerts.twilio_client:
            print("  SMS:")
            print(f"    Twilio: YES ({len(alerts.phone_numbers)} numbers)")
        else:
            print("  SMS:")
            print(f"    Twilio: NO (skipped)")

        if alerts.webhook_url:
            print("  Slack:")
            print(f"    Webhook: YES")
        else:
            print("  Slack:")
            print(f"    Webhook: NO (optional)")

        return True
    except Exception as e:
        print_error(f"Alert config error: {e}")
        return False

def main():
    """Main setup flow."""
    print_header("Algo Monitoring Setup")
    print("This will configure email/SMS/Slack alerts for trading surveillance.\n")

    # Check if already configured
    existing = load_existing_env()
    if existing:
        response = prompt("Found existing .env.local. Reconfigure?", "n")
        if response.lower() not in ['y', 'yes']:
            print_success("Using existing configuration")
            return 0

    config = {}

    # ====== EMAIL (Required) ======
    print_header("Email Configuration (Required)")
    print("Your alerts will be sent to email.\n")

    config['email_from'] = prompt(
        "Sender email",
        os.getenv('ALERT_EMAIL_FROM', 'edgebrookecapital@gmail.com')
    )

    config['email_to'] = prompt(
        "Recipient email",
        os.getenv('ALERT_EMAIL_TO', 'argeropolos@gmail.com')
    )

    if not validate_email(config['email_to']):
        print_error(f"Invalid email: {config['email_to']}")
        return 1

    config['smtp_user'] = prompt(
        "Gmail username",
        os.getenv('ALERT_SMTP_USER', 'edgebrookecapital@gmail.com')
    )

    print("\n  Gmail App Password:")
    print("    1. Go to: https://myaccount.google.com/apppasswords")
    print("    2. Select 'Mail' + 'Your Device'")
    print("    3. Google generates 16-character password")
    print("    4. Paste below (no spaces)")

    while True:
        pwd = getpass.getpass("  Paste Gmail app password: ").replace(' ', '')
        if validate_gmail_password(pwd):
            config['smtp_password'] = pwd
            print_success("Gmail password accepted (16 chars)")
            break
        else:
            print_error(f"Invalid length: {len(pwd)} chars (need 16)")

    # ====== SMS (Optional) ======
    print_header("SMS Alerts (Optional)")
    print("SMS notifications for CRITICAL alerts. Free tier: 1000 SMS/month.\n")

    response = prompt("Configure SMS with Twilio?", "n")
    if response.lower() in ['y', 'yes']:
        print("\n  Twilio Setup:")
        print("    1. Go to: https://www.twilio.com/console")
        print("    2. Create free account")
        print("    3. Get trial phone number")
        print("    4. Copy Account SID, Auth Token, Phone Number")

        config['twilio_sid'] = prompt("  Twilio Account SID")
        config['twilio_token'] = prompt("  Twilio Auth Token")
        config['twilio_number'] = prompt("  Twilio Phone Number (e.g., +1-414-XXX-XXXX)")
        config['alert_phone'] = prompt(
            "  Alert recipient phone",
            os.getenv('ALERT_PHONE_NUMBERS', '+1-312-307-8620')
        )

        if not validate_phone(config['alert_phone']):
            print_error(f"Invalid phone: {config['alert_phone']}")
            return 1

        print_success("SMS configuration saved")
    else:
        print_success("SMS skipped (optional)")

    # ====== Slack (Optional) ======
    print_header("Slack Alerts (Optional)")
    print("Post alerts to #trading-alerts channel.\n")

    response = prompt("Configure Slack?", "n")
    if response.lower() in ['y', 'yes']:
        print("\n  Slack Setup:")
        print("    1. Go to Slack Workspace → Manage Apps")
        print("    2. Create New App → 'From scratch'")
        print("    3. Name: 'Algo Alerts'")
        print("    4. Enable 'Incoming Webhooks'")
        print("    5. Create webhook to #trading-alerts")
        print("    6. Copy webhook URL")

        config['slack_webhook'] = prompt("  Slack Webhook URL")
        print_success("Slack webhook saved")
    else:
        print_success("Slack skipped (optional)")

    # ====== Write & Test ======
    print_header("Saving Configuration")
    write_env(config)

    print_header("Testing Configuration")
    if not test_alerts(config):
        print_error("Alert test failed")
        return 1

    # ====== Final ======
    print_header("Setup Complete!")
    print("""
Ready to deploy. Next steps:

1. Test alerts:
   python3 test_patrol_system.py --send-test-alert
   (Check email + SMS arrived)

2. Deploy monitoring:
   bash deploy_cron.sh
   (Sets up daily + continuous monitoring)

3. Monitor logs:
   tail -f /var/log/algo/orchestrator.log

See README_PRODUCTION.md for complete guide.
""")

    return 0

if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
    except Exception as e:
        print_error(f"Setup failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
