AWSTemplateFormatVersion: '2010-09-09'
Description: storage-stack – S3 bucket for Lambda deployment packages

Resources:
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: argofinancial-code
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

Outputs:
  CodeBucketName:
    Description: "Name of the S3 bucket for Lambda code"
    Value: !Ref CodeBucket
    Export:
      Name: storage-CodeBucketName
