AWSTemplateFormatVersion: '2010-09-09'
Description: Core infrastructure stack – IAM, VPC, Subnets, Internet/NAT, Bastion host (with bootstrap for PostgreSQL access), auto-shutdown Lambda, ECR registry, and S3 code bucket

Parameters:
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"
  PublicSubnetCidr1:
    Type: String
    Default: "10.0.1.0/24"
  PublicSubnetCidr2:
    Type: String
    Default: "10.0.2.0/24"
  PrivateSubnetCidr1:
    Type: String
    Default: "10.0.101.0/24"
  PrivateSubnetCidr2:
    Type: String
    Default: "10.0.102.0/24"

  DBStackName:
    Type: String
    Default: "stocks-db-lambda-stack"
    Description: Name of the CFN stack exporting DBEndpoint & DBPort
  DBSecretName:
    Type: String
    Default: "stocks-db-credentials"
    Description: Name of the SecretsManager secret holding DB credentials JSON

Resources:

  ### IAM Role for Lambdas ###
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-execution-admin-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ### VPC & Networking ###
  StocksVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true

  StocksIGW:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref StocksVPC
      InternetGatewayId: !Ref StocksIGW

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref StocksVPC
      CidrBlock: !Ref PublicSubnetCidr1
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref StocksVPC
      CidrBlock: !Ref PublicSubnetCidr2
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs '']

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref StocksVPC

  PublicDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref StocksIGW

  PubSubnet1RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PubSubnet2RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    DependsOn: NatEIP
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref StocksVPC
      CidrBlock: !Ref PrivateSubnetCidr1
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref StocksVPC
      CidrBlock: !Ref PrivateSubnetCidr2
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [1, !GetAZs '']

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref StocksVPC

  PrivateDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: NatGateway
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NatGateway

  PrivSubnet1RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivSubnet2RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref StocksVPC
      GroupDescription: "Allow egress for Lambdas"
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ### Bastion Host ###
  BastionInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: [ec2.amazonaws.com] }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  BastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref BastionInstanceRole]

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref StocksVPC
      GroupDescription: "Bastion SG (SSM only)"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0c94855ba95c71c99   # Amazon Linux 2
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet1
          GroupSet: [!Ref BastionSecurityGroup]
      IamInstanceProfile: !Ref BastionInstanceProfile
      Tags:
        - Key: Name
          Value: stocks-bastion
      UserData: !Base64 |
        #!/bin/bash
        set -eux

        # 1) System update
        yum update -y

        # 2) Install dependencies: curl, jq, AWS CLI (v1)
        yum install -y curl jq aws-cli

        # 3) Add PGDG repository for PostgreSQL 10+
        curl -fsSL \
          https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm \
          -o /tmp/pgdg.rpm
        rpm -Uvh /tmp/pgdg.rpm

        # 4) Remove any distro psql, then install PGDG psql client
        yum remove -y postgresql postgresql-libs
        yum install -y postgresql10

        # 5) Configure AWS CLI default region
        aws configure set region ${AWS::Region}

        # 6) Fetch DB creds from SecretsManager
        CREDS=$(aws secretsmanager get-secret-value \
          --secret-id "${DBSecretName}" \
          --query SecretString --output text)
        DB_USER=$(echo "$CREDS"    | jq -r .username)
        DB_PASS=$(echo "$CREDS"    | jq -r .password)
        DB_NAME=$(echo "$CREDS"    | jq -r .dbname)

        # 7) Lookup RDS endpoint & port from CFN Outputs
        DB_HOST=$(aws cloudformation describe-stacks \
          --stack-name "${DBStackName}" \
          --query "Stacks[0].Outputs[?OutputKey=='DBEndpoint'].OutputValue" \
          --output text)
        DB_PORT=$(aws cloudformation describe-stacks \
          --stack-name "${DBStackName}" \
          --query "Stacks[0].Outputs[?OutputKey=='DBPort'].OutputValue" \
          --output text)

        # 8) Create .pgpass for passwordless psql
        echo "${DB_HOST}:${DB_PORT}:${DB_NAME}:${DB_USER}:${DB_PASS}" \
          > /home/ec2-user/.pgpass
        chmod 600 /home/ec2-user/.pgpass
        chown ec2-user:ec2-user /home/ec2-user/.pgpass

        # 9) Export env vars in ec2-user's shell
        cat >> /home/ec2-user/.bash_profile <<'EOF'
export PGHOST=${DB_HOST}
export PGPORT=${DB_PORT}
export PGUSER=${DB_USER}
export PGPASSWORD=${DB_PASS}
export PGDATABASE=${DB_NAME}
EOF
        chown ec2-user:ec2-user /home/ec2-user/.bash_profile

  ### Auto-shutdown Lambda ###
  BastionStopRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: [lambda.amazonaws.com] }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StopBastion
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ec2:StopInstances
                Resource: !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/${BastionHost}

  BastionStopFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      Role: !GetAtt BastionStopRole.Arn
      Environment:
        Variables:
          BASTION_ID: !Ref BastionHost
      Code:
        ZipFile: |
          import boto3, os
          boto3.client('ec2').stop_instances(InstanceIds=[os.environ['BASTION_ID']])

  BastionStopRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Daily stop of bastion at 6 PM CT"
      ScheduleExpression: cron(0 23 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt BastionStopFunction.Arn
          Id: StopBastion

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BastionStopFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BastionStopRule.Arn

  ### ECR Registry ###
  ContainerRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Delete
    Properties:
      RepositoryName: stocks-app-registry
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"description":"Expire images older than 30 days","selection":{"tagStatus":"any","countType":"sinceImagePushed","countUnit":"days","countNumber":30},"action":{"type":"expire"}}]}

  ### S3 bucket for Lambda code ###
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration: { Status: Enabled }
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

Outputs:
  VpcId:
    Value: !Ref StocksVPC
    Export: { Name: StocksCore-VpcId }
  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Export: { Name: StocksCore-PublicSubnet1Id }
  PublicSubnet2Id:
    Value: !Ref PublicSubnet2
    Export: { Name: StocksCore-PublicSubnet2Id }
  PrivateSubnet1Id:
    Value: !Ref PrivateSubnet1
    Export: { Name: StocksCore-PrivateSubnet1Id }
  PrivateSubnet2Id:
    Value: !Ref PrivateSubnet2
    Export: { Name: StocksCore-PrivateSubnet2Id }
  LambdaSecurityGroupId:
    Value: !Ref LambdaSecurityGroup
    Export: { Name: StocksCore-LambdaSecurityGroupId }
  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn
    Export: { Name: StocksCore-LambdaExecutionRoleArn }
  ContainerRepositoryUri:
    Value: !GetAtt ContainerRepository.RepositoryUri
    Export: { Name: StocksCore-ContainerRepositoryUri }
  CodeBucketName:
    Value: !Ref CodeBucket
    Export: { Name: StocksCore-CodeBucketName }
