AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECS TaskDefinitions, CloudWatch LogGroups, and zero‑scale Services
  for stock‑symbols, econ‑data, monthly‑price loaders,
  plus findata, pricedaily, priceweekly, pricemonthly & technicaldaily.

Parameters:
  StockSymbolsImageTag:
    Type: String
    Description: Tag for stock‑symbols loader image
  EconDataImageTag:
    Type: String
    Description: Tag for econ‑data loader image
  MonthlyPriceImageTag:
    Type: String
    Description: Tag for monthly‑price loader image
  FindataImageTag:
    Type: String
    Description: Tag for findata loader image
  PriceImageTag:
    Type: String
    Description: Tag for pricedaily loader image
  PriceWeeklyImageTag:
    Type: String
    Description: Tag for priceweekly loader image
  PriceMonthlyImageTag:
    Type: String
    Description: Tag for pricemonthly loader image
  TechnicalDailyImageTag:
    Type: String
    Description: Tag for technicaldaily loader image
  FREDApiKey:
    Type: String
    NoEcho: true
    Description: FRED API key for econ‑data loader

Resources:

  ######################################
  # A) ECS Execution Role & Policy     #
  ######################################
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        # (1) Allow creating CloudWatch LogGroups if they don't exist
        - PolicyName: AllowCreateCWLogGroups
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/*"
        # (2) Allow reading your DB secret and KMS decrypt
        - PolicyName: AllowReadDBSecret
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !ImportValue StocksApp-SecretArn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: '*'  # you can lock this down to your secret’s CMK ARN

  ######################################
  # B) CloudWatch Log Groups           #
  ######################################
  StockSymbolsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/stocksymbols-loader
      RetentionInDays: 14

  EconDataLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/econdata-loader
      RetentionInDays: 14

  MonthlyPriceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/monthlyprice-loader
      RetentionInDays: 14

  FindataLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/findata-loader
      RetentionInDays: 14

  PriceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/pricedaily-loader
      RetentionInDays: 14

  WeeklyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/priceweekly-loader
      RetentionInDays: 14

  PricemonthlyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/pricemonthly-loader
      RetentionInDays: 14

  TechnicalDailyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/technicaldaily-loader
      RetentionInDays: 14

  ###########################################################
  # C) stock‑symbols loader TaskDefinition & Service        #
  ###########################################################
  StockSymbolsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: stocksymbols-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn:      !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: stocksymbols-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref StockSymbolsImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksApp-SecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/stocksymbols-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  StockSymbolsLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: stocksymbols-loader-service
      Cluster: !ImportValue StocksApp-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref StockSymbolsTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  ###########################################################
  # D) econ‑data loader TaskDefinition & Service            #
  ###########################################################
  EconDataTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: econdata-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn:      !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: econdata-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref EconDataImageTag
          Essential: true
          Environment:
            - Name: LOG_GROUP
              Value: /ecs/econdata-loader
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksApp-SecretArn
            - Name: FRED_API_KEY
              Value: !Ref FREDApiKey
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/econdata-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  EconDataLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: econdata-loader-service
      Cluster: !ImportValue StocksApp-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref EconDataTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  ###########################################################
  # E) monthly‑price loader TaskDefinition & Service        #
  ###########################################################
  MonthlyPriceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: monthlyprice-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn:      !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: monthlyprice-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref MonthlyPriceImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksApp-SecretArn
            - Name: FRED_API_KEY
              Value: !Ref FREDApiKey
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/monthlyprice-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  MonthlyPriceLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: monthlyprice-loader-service
      Cluster: !ImportValue StocksApp-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref MonthlyPriceTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  ###########################################################
  # F) findata, pricedaily, priceweekly, pricemonthly,      #
  #    technicaldaily loaders                               #
  ###########################################################
  FindataTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: findata-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn:      !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: findata-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref FindataImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksApp-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/findata-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  FindataLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: findata-loader-service
      Cluster: !ImportValue StocksApp-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref FindataTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  PriceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricedaily-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn:      !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: pricedaily-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref PriceImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksApp-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/pricedaily-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  PriceLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: pricedaily-loader-service
      Cluster: !ImportValue StocksApp-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref PriceTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  PriceWeeklyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: priceweekly-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn:      !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: priceweekly-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref PriceWeeklyImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksApp-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/priceweekly-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  PriceWeeklyLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: priceweekly-loader-service
      Cluster: !ImportValue StocksApp-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref PriceWeeklyTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  PricemonthlyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricemonthly-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn:      !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: pricemonthly-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref PriceMonthlyImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksApp-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/pricemonthly-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  PricemonthlyLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: pricemonthly-loader-service
      Cluster: !ImportValue StocksApp-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref PricemonthlyTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  TechnicalDailyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: technicaldaily-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn:      !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: technicaldaily-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref TechnicalDailyImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksApp-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/technicaldaily-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  TechnicalDailyLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: technicaldaily-loader-service
      Cluster: !ImportValue StocksApp-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref TechnicalDailyTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

Outputs:
  StockSymbolsTaskDefArn:
    Value: !Ref StockSymbolsTaskDefinition
  StockSymbolsServiceName:
    Value: !GetAtt StockSymbolsLoaderService.Name

  EconDataTaskDefArn:
    Value: !Ref EconDataTaskDefinition
  EconDataServiceName:
    Value: !GetAtt EconDataLoaderService.Name

  MonthlyPriceTaskDefArn:
    Value: !Ref MonthlyPriceTaskDefinition
  MonthlyPriceServiceName:
    Value: !GetAtt MonthlyPriceLoaderService.Name

  FindataTaskDefArn:
    Value: !Ref FindataTaskDefinition
  FindataServiceName:
    Value: !GetAtt FindataLoaderService.Name

  PriceTaskDefArn:
    Value: !Ref PriceTaskDefinition
  PriceServiceName:
    Value: !GetAtt PriceLoaderService.Name

  PriceWeeklyTaskDefArn:
    Value: !Ref PriceWeeklyTaskDefinition
  PriceWeeklyServiceName:
    Value: !GetAtt PriceWeeklyLoaderService.Name

  PricemonthlyTaskDefArn:
    Value: !Ref PricemonthlyTaskDefinition
  PricemonthlyServiceName:
    Value: !GetAtt PricemonthlyLoaderService.Name

  TechnicalDailyTaskDefArn:
    Value: !Ref TechnicalDailyTaskDefinition
  TechnicalDailyServiceName:
    Value: !GetAtt TechnicalDailyLoaderService.Name
