AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECS TaskDefinitions and CloudWatch LogGroups for findata,
  pricedaily, priceweekly & pricemonthly—no schedules; tasks are executed manually
  (e.g. via CI workflow).

Parameters:
  FindataImageTag:
    Type: String
    Description: Tag of the findata image (e.g. findata-<git-sha>)
  PriceImageTag:
    Type: String
    Description: Tag of the pricedaily image (e.g. pricedaily-<git-sha>)
  PriceWeeklyImageTag:
    Type: String
    Description: Tag of the priceweekly image (e.g. priceweekly-<git-sha>)
  PriceMonthlyImageTag:
    Type: String
    Description: Tag of the pricemonthly image (e.g. pricemonthly-<git-sha>)
  FREDApiKey:
    Type: String
    NoEcho: true
    Description: FRED API key for econ-data loader

Resources:

  ##################################
  # 0) CloudWatch LogGroups
  ##################################
  FindataLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/findata-loader'
      RetentionInDays: 14

  PriceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/pricedaily-loader'
      RetentionInDays: 14

  WeeklyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/priceweekly-loader'
      RetentionInDays: 14

  MonthlyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/pricemonthly-loader'
      RetentionInDays: 14

  ##################################
  # 1) findata-loader TaskDefinition
  ##################################
  FindataTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: findata-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: findata-loader
          Image:
            Fn::Join:
              - ""
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - ":"
                - !Ref FindataImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
            - Name: FRED_API_KEY
              Value: !Ref FREDApiKey
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/findata-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ##################################
  # 2) pricedaily-loader TaskDefinition
  ##################################
  PriceTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricedaily-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: pricedaily-loader
          Image:
            Fn::Join:
              - ""
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - ":"
                - !Ref PriceImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/pricedaily-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ##################################
  # 3) priceweekly-loader TaskDefinition
  ##################################
  WeeklyTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: priceweekly-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: priceweekly-loader
          Image:
            Fn::Join:
              - ""
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - ":"
                - !Ref PriceWeeklyImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/priceweekly-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ##################################
  # 4) pricemonthly-loader TaskDefinition
  ##################################
  MonthlyTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricemonthly-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: pricemonthly-loader
          Image:
            Fn::Join:
              - ""
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - ":"
                - !Ref PriceMonthlyImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/pricemonthly-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

Outputs:
  FindataTaskDefinitionArn:
    Description: ARN of the findata task definition
    Value: !Ref FindataTaskDef

  PriceTaskDefinitionArn:
    Description: ARN of the pricedaily task definition
    Value: !Ref PriceTaskDef

  PriceWeeklyTaskDefinitionArn:
    Description: ARN of the priceweekly task definition
    Value: !Ref WeeklyTaskDef

  PriceMonthlyTaskDefinitionArn:
    Description: ARN of the pricemonthly task definition
    Value: !Ref MonthlyTaskDef
