AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECS TaskDefinitions, CloudWatch LogGroups, and zero-scale Services
  for findata, pricedaily, priceweekly, pricemonthly & technicaldaily.
  Services start at DesiredCount=0 and are scaled on demand via CI.

Parameters:
  FindataImageTag:
    Type: String
    Description: Tag of the findata container image (e.g. findata-<git-sha>)
  PriceImageTag:
    Type: String
    Description: Tag of the pricedaily container image (e.g. pricedaily-<git-sha>)
  PriceWeeklyImageTag:
    Type: String
    Description: Tag of the priceweekly container image (e.g. priceweekly-<git-sha>)
  PriceMonthlyImageTag:
    Type: String
    Description: Tag of the pricemonthly container image (e.g. pricemonthly-<git-sha>)
  TechnicalDailyImageTag:
    Type: String
    Description: Tag of the technicaldaily container image (e.g. technicaldaily-<git-sha>)
  FREDApiKey:
    Type: String
    NoEcho: true
    Description: FRED API key for econ-data loader

Resources:

  ##################################
  # 0) CloudWatch LogGroups        #
  ##################################
  FindataLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/findata-loader'
      RetentionInDays: 14

  PriceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/pricedaily-loader'
      RetentionInDays: 14

  WeeklyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/priceweekly-loader'
      RetentionInDays: 14

  MonthlyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/pricemonthly-loader'
      RetentionInDays: 14

  TechnicalDailyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/technicaldaily-loader'
      RetentionInDays: 14

  ##############################################
  # 1) findata-loader TaskDefinition           #
  ##############################################
  FindataTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: findata-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: findata-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref FindataImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
            - Name: FRED_API_KEY
              Value: !Ref FREDApiKey
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/findata-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ##################################################
  # 2) pricedaily-loader TaskDefinition            #
  ##################################################
  PriceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricedaily-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: pricedaily-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref PriceImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/pricedaily-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ##################################################
  # 3) priceweekly-loader TaskDefinition           #
  ##################################################
  PriceWeeklyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: priceweekly-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: priceweekly-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref PriceWeeklyImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/priceweekly-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ##################################################
  # 4) pricemonthly-loader TaskDefinition          #
  ##################################################
  PriceMonthlyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricemonthly-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: pricemonthly-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref PriceMonthlyImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/pricemonthly-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ##########################################################
  # 5) technicaldaily-loader TaskDefinition               #
  ##########################################################
  TechnicalDailyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: technicaldaily-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: technicaldaily-loader
          Image:
            Fn::Join:
              - ":"
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - !Ref TechnicalDailyImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: DB_HOST
              Value: !ImportValue StocksApp-DBEndpoint
            - Name: DB_PORT
              Value: !ImportValue StocksApp-DBPort
            - Name: DB_NAME
              Value: !ImportValue StocksApp-DBName
            - Name: DB_USER
              Value: !ImportValue StocksApp-DBUsername
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/technicaldaily-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ##############################################################
  # 6) findata-loader Service (zero scale, inline subnets)     #
  ##############################################################
  FindataLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: findata-loader-service
      Cluster: !ImportValue StocksDBLambdaStack-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref FindataTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  ##############################################################
  # 7) pricedaily-loader Service (zero scale, inline subnets)  #
  ##############################################################
  PriceDailyLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: pricedaily-loader-service
      Cluster: !ImportValue StocksDBLambdaStack-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref PriceTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  ##############################################################
  # 8) priceweekly-loader Service (zero scale, inline subnets) #
  ##############################################################
  PriceWeeklyLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: priceweekly-loader-service
      Cluster: !ImportValue StocksDBLambdaStack-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref PriceWeeklyTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  ##############################################################
  # 9) pricemonthly-loader Service (inline subnets)           #
  ##############################################################
  PriceMonthlyLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: pricemonthly-loader-service
      Cluster: !ImportValue StocksDBLambdaStack-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref PriceMonthlyTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

  ##############################################################
  # 10) technicaldaily-loader Service (inline subnets)         #
  ##############################################################
  TechnicalDailyLoaderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: technicaldaily-loader-service
      Cluster: !ImportValue StocksDBLambdaStack-ClusterArn
      LaunchType: FARGATE
      DesiredCount: 0
      TaskDefinition: !Ref TechnicalDailyTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue StocksCore-PublicSubnet1Id
            - !ImportValue StocksCore-PublicSubnet2Id
          AssignPublicIp: ENABLED

Outputs:

  FindataTaskDefinitionArn:
    Description: ARN of the findata ECS TaskDefinition
    Value: !Ref FindataTaskDefinition

  PriceTaskDefinitionArn:
    Description: ARN of the pricedaily ECS TaskDefinition
    Value: !Ref PriceTaskDefinition

  PriceWeeklyTaskDefinitionArn:
    Description: ARN of the priceweekly ECS TaskDefinition
    Value: !Ref PriceWeeklyTaskDefinition

  PriceMonthlyTaskDefinitionArn:
    Description: ARN of the pricemonthly ECS TaskDefinition
    Value: !Ref PriceMonthlyTaskDefinition

  TechnicalDailyTaskDefinitionArn:
    Description: ARN of the technicaldaily ECS TaskDefinition
    Value: !Ref TechnicalDailyTaskDefinition

  FindataLoaderServiceName:
    Description: ECS Service name for findata-loader
    Value: !Ref FindataLoaderService

  PriceDailyLoaderServiceName:
    Description: ECS Service name for pricedaily-loader
    Value: !Ref PriceDailyLoaderService

  PriceWeeklyLoaderServiceName:
    Description: ECS Service name for priceweekly-loader
    Value: !Ref PriceWeeklyLoaderService

  PriceMonthlyLoaderServiceName:
    Description: ECS Service name for pricemonthly-loader
    Value: !Ref PriceMonthlyLoaderService

  TechnicalDailyLoaderServiceName:
    Description: ECS Service name for technicaldaily-loader
    Value: !Ref TechnicalDailyLoaderService
