AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Application stack – RDS (public), Secrets (DB creds),
  three Lambdas (symbols‑loader, economic‑data loader & monthly‑price loader),
  and ECS cluster, all in public subnets.

Parameters:
  CodeKey:
    Type: String
    Description: S3 key of the symbols‑loader Lambda ZIP
  EconomicCodeKey:
    Type: String
    Description: S3 key of the economic‑data loader Lambda ZIP
  MonthlyCodeKey:
    Type: String
    Description: S3 key of the monthly‑price loader Lambda ZIP
  RDSUsername:
    Type: String
    Description: RDS master username
  RDSPassword:
    Type: String
    NoEcho: true
    Description: RDS master password
  FREDApiKey:
    Type: String
    NoEcho: true
    Description: FRED API key for economic‑data loader
  VpcCidr:
    Type: String
    Default: "0.0.0.0/0"
    Description: CIDR block allowed to connect to RDS (public access)

Resources:

  ### RDS Subnet Group (only public subnets) ###
  StocksDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DBSubnetGroupDescription: Public subnet group for RDS
      SubnetIds:
        - !ImportValue StocksCore-PublicSubnet1Id
        - !ImportValue StocksCore-PublicSubnet2Id

  ### RDS Security Group ###
  StocksDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Postgres access from VpcCidr
      VpcId: !ImportValue StocksCore-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref VpcCidr

  ### RDS Instance (publicly accessible) ###
  StocksDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    DependsOn:
      - StocksDBSubnetGroup
      - StocksDBSecurityGroup
    Properties:
      DBInstanceIdentifier: stocks
      DBName: stocks
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref RDSUsername
      MasterUserPassword: !Ref RDSPassword
      VPCSecurityGroups:
        - !Ref StocksDBSecurityGroup
      DBSubnetGroupName: !Ref StocksDBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true
      DeletionProtection: false

  ### Secrets Manager: DB credentials ###
  DBCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    DependsOn: StocksDBInstance
    Properties:
      Name: stocks-db-credentials
      Description: JSON with username, password, host, port, dbname
      SecretString:
        Fn::Join:
          - ""
          - - '{"username":"'
            - !Ref RDSUsername
            - '","password":"'
            - !Ref RDSPassword
            - '","host":"'
            - !GetAtt StocksDBInstance.Endpoint.Address
            - '","port":"'
            - !GetAtt StocksDBInstance.Endpoint.Port
            - '","dbname":"stocks"}'

  ### Lambda: symbols‑loader (public subnets) ###
  LoadStockSymbolsFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - StocksDBInstance
      - DBCredentialsSecret
    Properties:
      FunctionName: loadstocksymbols
      Runtime: python3.9
      Handler: index.handler
      Role: !ImportValue StocksCore-LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue StocksCore-CodeBucketName
        S3Key: !Ref CodeKey
      Timeout: 300
      VpcConfig:
        SubnetIds:
          - !ImportValue StocksCore-PublicSubnet1Id
          - !ImportValue StocksCore-PublicSubnet2Id
        SecurityGroupIds:
          - !ImportValue StocksCore-LambdaSecurityGroupId
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DBCredentialsSecret

  ### Lambda: economic‑data loader (public subnets) ###
  LoadEconomicDataFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - StocksDBInstance
      - DBCredentialsSecret
    Properties:
      FunctionName: loadecondata
      Runtime: python3.9
      Handler: index.handler
      Role: !ImportValue StocksCore-LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue StocksCore-CodeBucketName
        S3Key: !Ref EconomicCodeKey
      Timeout: 900
      VpcConfig:
        SubnetIds:
          - !ImportValue StocksCore-PublicSubnet1Id
          - !ImportValue StocksCore-PublicSubnet2Id
        SecurityGroupIds:
          - !ImportValue StocksCore-LambdaSecurityGroupId
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DBCredentialsSecret
          FRED_API_KEY:   !Ref FREDApiKey

  ### Lambda: monthly‑price loader (public subnets) ###
  LoadMonthlyPriceFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - StocksDBInstance
      - DBCredentialsSecret
    Properties:
      FunctionName: loadpricemonthly
      Runtime: python3.9
      Handler: index.handler
      Role: !ImportValue StocksCore-LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue StocksCore-CodeBucketName
        S3Key: !Ref MonthlyCodeKey
      Timeout: 900
      VpcConfig:
        SubnetIds:
          - !ImportValue StocksCore-PublicSubnet1Id
          - !ImportValue StocksCore-PublicSubnet2Id
        SecurityGroupIds:
          - !ImportValue StocksCore-LambdaSecurityGroupId
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DBCredentialsSecret
          FRED_API_KEY:   !Ref FREDApiKey

  ### ECS Cluster ###
  StocksEcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: stocks-cluster

  ### ECS Task Execution Role ###
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-task-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: AllowGetSecretValue
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DBCredentialsSecret

Outputs:
  DBEndpoint:
    Description: RDS endpoint address
    Value: !GetAtt StocksDBInstance.Endpoint.Address
    Export:
      Name: StocksApp-DBEndpoint

  DBPort:
    Description: RDS endpoint port
    Value: !GetAtt StocksDBInstance.Endpoint.Port
    Export:
      Name: StocksApp-DBPort

  DBName:
    Description: RDS database name
    Value: stocks
    Export:
      Name: StocksApp-DBName

  DBUsername:
    Description: RDS master username
    Value: !Ref RDSUsername
    Export:
      Name: StocksApp-DBUsername

  SecretArn:
    Description: ARN of the DB credentials secret
    Value: !Ref DBCredentialsSecret
    Export:
      Name: StocksDBLambdaStack-SecretArn

  ClusterArn:
    Description: ARN of the ECS cluster
    Value: !GetAtt StocksEcsCluster.Arn
    Export:
      Name: StocksDBLambdaStack-ClusterArn

  EcsTaskExecutionRoleArn:
    Description: ARN of the ECS Task Execution Role
    Value: !GetAtt EcsTaskExecutionRole.Arn
    Export:
      Name: StocksDBLambdaStack-EcsTaskExecutionRoleArn
