AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Defines the Fargate TaskDefinition and a scheduled EventBridge Rule
  to run the data-loader daily.

Parameters:
  ImageTag:
    Type: String
    Description: Docker image tag (Git SHA) to deploy

Resources:

  ### IAM role for EventBridge to invoke ECS RunTask ###
  DataLoaderEventsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DataLoaderInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn

  ### ECS TaskDefinition for the data-loader ###
  DataLoaderTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      RequiresCompatibilities:
        - FARGATE
      Cpu:    '256'
      Memory: '512'
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: stocks-data-loader
          Image: !Sub "${ContainerRepositoryUri}:${ImageTag}"
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:        /ecs/stocks-data-loader
              awslogs-region:       !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  ### Scheduled rule to run the task daily at noon UTC ###
  DataLoaderSchedule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Daily run of stocks-data-loader on Fargate"
      ScheduleExpression: "cron(0 12 * * ? *)"
      State: ENABLED
      Targets:
        - Id: RunDataLoader
          Arn: !ImportValue StocksDBLambdaStack-ClusterArn
          RoleArn: !GetAtt DataLoaderEventsRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref DataLoaderTaskDefinition
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                Subnets:
                  - !ImportValue StocksCore-PrivateSubnet1Id
                  - !ImportValue StocksCore-PrivateSubnet2Id
                SecurityGroups:
                  - !ImportValue StocksCore-LambdaSecurityGroupId
                AssignPublicIp: DISABLED

Outputs:
  TaskDefinitionArn:
    Description: ARN of the registered ECS TaskDefinition
    Value: !Ref DataLoaderTaskDefinition
