AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECS TaskDefinitions, CloudWatch LogGroups, and EventBridge rules
  to run your data‑processing scripts on Fargate.

Parameters:
  FindataImageTag:
    Type: String
    Description: Tag of the findata image (e.g. findata-<git-sha>)
  PriceImageTag:
    Type: String
    Description: Tag of the pricedaily image (e.g. pricedaily-<git-sha>)
  FREDApiKey:
    Type: String
    NoEcho: true
    Description: FRED API key for the economic‑data loader

Resources:

  ############################################
  # 0) Pre‑create CloudWatch LogGroups
  ############################################

  FindataLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/findata-loader'
      RetentionInDays: 14

  PriceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/pricedaily-loader'
      RetentionInDays: 14

  ############################################
  # 1) IAM Role for EventBridge → ECS RunTask
  ############################################

  EcsEventsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-events-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowRunTask
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                  - iam:PassRole
                Resource: "*"

  ################################################
  # 2) findata‑loader TaskDefinition
  ################################################

  FindataTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: findata-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: findata-loader
          Image:
            Fn::Join:
              - ''
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - ':'
                - !Ref FindataImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
            - Name: FRED_API_KEY
              Value: !Ref FREDApiKey
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/findata-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ################################################
  # 3) pricedaily‑loader TaskDefinition
  ################################################

  PriceTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricedaily-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: pricedaily-loader
          Image:
            Fn::Join:
              - ''
              - - !ImportValue StocksCore-ContainerRepositoryUri
                - ':'
                - !Ref PriceImageTag
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !ImportValue StocksDBLambdaStack-SecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:         /ecs/pricedaily-loader
              awslogs-region:        !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ################################################
  # 4) Scheduled Rule: findata daily
  ################################################

  FindataSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: findata-loader-schedule
      Description: "Daily run of findata‑loader"
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !ImportValue StocksDBLambdaStack-ClusterArn
          Id: RunFindata
          RoleArn: !GetAtt EcsEventsRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref FindataTaskDef
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                Subnets:
                  - !ImportValue StocksCore-PrivateSubnet1Id
                  - !ImportValue StocksCore-PrivateSubnet2Id
                SecurityGroups:
                  - !ImportValue StocksCore-LambdaSecurityGroupId
                AssignPublicIp: DISABLED

  ################################################
  # 5) Scheduled Rule: pricedaily daily
  ################################################

  PriceSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: pricedaily-loader-schedule
      Description: "Daily run of pricedaily‑loader"
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !ImportValue StocksDBLambdaStack-ClusterArn
          Id: RunPrice
          RoleArn: !GetAtt EcsEventsRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref PriceTaskDef
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                Subnets:
                  - !ImportValue StocksCore-PrivateSubnet1Id
                  - !ImportValue StocksCore-PrivateSubnet2Id
                SecurityGroups:
                  - !ImportValue StocksCore-LambdaSecurityGroupId
                AssignPublicIp: DISABLED

Outputs:
  FindataTaskDefinitionArn:
    Description: ARN of the findata task definition
    Value: !Ref FindataTaskDef

  PriceTaskDefinitionArn:
    Description: ARN of the pricedaily task definition
    Value: !Ref PriceTaskDef
