AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECS TaskDefinitions and EventBridge rules to run
  your data-processing scripts on Fargate.

Parameters:
  ClusterArn:
    Type: String
    Description: ARN of the ECS cluster to run tasks in
  ContainerRepositoryUri:
    Type: String
    Description: URI of the ECR repository
  DBSecretArn:
    Type: String
    Description: ARN of the SecretsManager secret with DB creds
  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: First private subnet ID
  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Second private subnet ID
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for Fargate tasks
  FindataImageTag:
    Type: String
    Description: Tag of the findata image
  PriceImageTag:
    Type: String
    Description: Tag of the pricedaily image
  FREDApiKey:
    Type: String
    Description: FRED API key for the economic-data loader

Resources:

  ## 1) Role for EventBridge to invoke ECS RunTask ##
  EcsEventsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSEventsRolePolicy

  ## 2) findata-loader TaskDefinition ##
  FindataTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: findata-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: findata-loader
          Image:
            Fn::Sub: "${ContainerRepositoryUri}:${FindataImageTag}"
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !Ref DBSecretArn
            - Name: FRED_API_KEY
              Value: !Ref FREDApiKey
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:        /ecs/findata-loader
              awslogs-region:       !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ## 3) pricedaily-loader TaskDefinition ##
  PriceTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricedaily-loader
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      TaskRoleArn:      !ImportValue StocksDBLambdaStack-EcsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: pricedaily-loader
          Image:
            Fn::Sub: "${ContainerRepositoryUri}:${PriceImageTag}"
          Essential: true
          Environment:
            - Name: DB_SECRET_ARN
              Value: !Ref DBSecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:        /ecs/pricedaily-loader
              awslogs-region:       !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ## 4) Scheduled rule: findata daily ##
  FindataSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: findata-loader-schedule
      Description: "Daily run of findata-loader"
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !Ref ClusterArn
          Id: RunFindata
          RoleArn: !GetAtt EcsEventsRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref FindataTaskDef
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                Subnets:
                  - !Ref PrivateSubnet1Id
                  - !Ref PrivateSubnet2Id
                SecurityGroups:
                  - !Ref SecurityGroupId
                AssignPublicIp: DISABLED

  ## 5) Scheduled rule: pricedaily daily ##
  PriceSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: pricedaily-loader-schedule
      Description: "Daily run of pricedaily-loader"
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !Ref ClusterArn
          Id: RunPrice
          RoleArn: !GetAtt EcsEventsRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref PriceTaskDef
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                Subnets:
                  - !Ref PrivateSubnet1Id
                  - !Ref PrivateSubnet2Id
                SecurityGroups:
                  - !Ref SecurityGroupId
                AssignPublicIp: DISABLED

Outputs:
  FindataTaskDefinitionArn:
    Description: ARN of the findata task definition
    Value: !Ref FindataTaskDef
  PriceTaskDefinitionArn:
    Description: ARN of the pricedaily task definition
    Value: !Ref PriceTaskDef
