#!/bin/bash
echo "=========================================="
echo "TESTING WORKFLOW EXECUTION"
echo "=========================================="
echo ""
echo "To actually test if workflows work, you need to:"
echo ""
echo "OPTION 1: Push a code change (triggers workflows automatically)"
echo "  $ git add -A"
echo "  $ git commit -m 'test: trigger deployment workflows'"
echo "  $ git push origin main"
echo ""
echo "  Then watch: https://github.com/argie33/algo/actions"
echo "  You should see workflows starting within 30 seconds"
echo ""
echo "OPTION 2: Manually trigger a workflow on GitHub"
echo "  1. Go to https://github.com/argie33/algo/actions"
echo "  2. Click on 'deploy-algo-orchestrator' (or any workflow)"
echo "  3. Click 'Run workflow' dropdown"
echo "  4. Click green 'Run workflow' button"
echo "  5. Watch it execute in real-time"
echo ""
echo "=========================================="
echo "WHAT TO CHECK AFTER TRIGGERING"
echo "=========================================="
echo ""
echo "1. GitHub Actions (30 seconds)"
echo "   URL: https://github.com/argie33/algo/actions"
echo "   Look for: Workflow run starting"
echo "   Status: Green ✅ or Red ❌"
echo ""
echo "2. Workflow Logs (2-5 minutes)"
echo "   Click on the workflow run"
echo "   Click on a job (e.g., 'deploy-lambda')"
echo "   Check for error messages"
echo "   Look specifically for 'CloudFormation' errors"
echo ""
echo "3. AWS CloudFormation (5-15 minutes)"
echo "   URL: https://console.aws.amazon.com/cloudformation"
echo "   Look for: Stack names (stocks-algo-orchestrator, etc.)"
echo "   Status should be: CREATE_COMPLETE or UPDATE_COMPLETE"
echo "   If ROLLBACK_COMPLETE: Click 'Events' tab to see error"
echo ""
echo "4. AWS Lambda (After CloudFormation completes)"
echo "   URL: https://console.aws.amazon.com/lambda"
echo "   Search for: 'algo-orchestrator'"
echo "   Check: Function exists and environment variables are set"
echo ""
echo "=========================================="
echo "WHAT WOULD PROVE WORKFLOWS WORK"
echo "=========================================="
echo ""
echo "✅ GitHub Actions shows green checkmark"
echo "✅ Workflow logs have no errors"
echo "✅ CloudFormation stack exists and is CREATE_COMPLETE"
echo "✅ Lambda function exists with env vars set"
echo "✅ EventBridge rule exists and is ENABLED"
echo ""
echo "=========================================="
echo "WHAT WOULD INDICATE PROBLEMS"
echo "=========================================="
echo ""
echo "❌ Workflow shows red X (failed)"
echo "❌ Logs show 'error' or 'failed'"
echo "❌ CloudFormation stack shows ROLLBACK_COMPLETE"
echo "❌ Lambda function missing or env vars empty"
echo "❌ EventBridge rule missing or DISABLED"
echo ""
echo "=========================================="
