#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🚀 Setting up development environment...');

// Get API URL and environment name from command line or use defaults
const apiUrl = process.argv[2] || 'http://localhost:3001';
const environment = process.argv[3] || 'development';

// Create environment configuration
const devConfig = {
  API_URL: apiUrl,
  BUILD_TIME: new Date().toISOString(),
  VERSION: '1.0.0-dev',
  ENVIRONMENT: environment
};

// Update the runtime config for development
const configPath = path.join(__dirname, '..', 'public', 'config.js');
const configContent = `// Runtime configuration - ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment\n// This file is auto-generated by setup-dev.js\nwindow.__CONFIG__ = ${JSON.stringify(devConfig, null, 2)};\n`;

fs.writeFileSync(configPath, configContent);
console.log('✅ Updated public/config.js for', environment);

// Create .env file for Vite
const envPath = path.join(__dirname, '..', '.env');
const envContent = `# ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment Configuration
# Auto-generated by setup-dev.js

# API Configuration
VITE_API_URL=${apiUrl}
VITE_SERVERLESS=false
VITE_ENVIRONMENT=${environment}

# Build Configuration
VITE_BUILD_TIME=${new Date().toISOString()}
VITE_VERSION=1.0.0-dev

# AWS Cognito Configuration - For development, use empty values to disable auth
VITE_COGNITO_USER_POOL_ID=
VITE_COGNITO_CLIENT_ID=
VITE_AWS_REGION=us-east-1
VITE_COGNITO_DOMAIN=
VITE_COGNITO_REDIRECT_SIGN_IN=http://localhost:5173
VITE_COGNITO_REDIRECT_SIGN_OUT=http://localhost:5173

# Feature Flags
VITE_ENABLE_DEBUG=true
VITE_ENABLE_MOCK_DATA=true
`;

fs.writeFileSync(envPath, envContent);
console.log('✅ Created .env file for', environment);

console.log('');
console.log(`🎉 ${environment.charAt(0).toUpperCase() + environment.slice(1)} environment configured!`);
console.log('');
console.log('📋 Configuration:');
console.log(`   API URL: ${devConfig.API_URL}`);
console.log(`   Environment: ${devConfig.ENVIRONMENT}`);
console.log(`   Version: ${devConfig.VERSION}`);
console.log('');
console.log('🚀 Next steps:');
console.log('   1. Run: npm run dev');
console.log('');
console.log('💡 To reset to production config, run: npm run setup-prod');
console.log(''); 