#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🚀 Setting up development environment...');

// Get API URL and environment name from command line or use defaults
const apiUrl = process.argv[2] || 'http://localhost:3001';
const environment = process.argv[3] || 'development';
const forceSetup = process.argv.includes('--force');

// Create comprehensive environment configuration with dynamic CloudFormation loading
const devConfig = {
  // Build Information
  BUILD_TIME: new Date().toISOString(),
  VERSION: '1.0.0-dev',
  ENVIRONMENT: environment,
  
  // API Configuration - with CloudFormation priority
  API: {
    BASE_URL: `window.__CLOUDFORMATION_CONFIG__?.ApiGatewayUrl || '${apiUrl}'`
  },
  
  // AWS Configuration
  AWS: {
    REGION: 'us-east-1'
  },
  
  // Cognito Configuration - MUST come from CloudFormation
  COGNITO: {
    USER_POOL_ID: 'window.__CLOUDFORMATION_CONFIG__?.UserPoolId || null',
    CLIENT_ID: 'window.__CLOUDFORMATION_CONFIG__?.UserPoolClientId || null',
    REGION: 'us-east-1',
    DOMAIN: 'window.__CLOUDFORMATION_CONFIG__?.UserPoolDomain || null',
    REDIRECT_SIGN_IN: 'window.location.origin',
    REDIRECT_SIGN_OUT: 'window.location.origin'
  },
  
  // Feature Flags
  FEATURES: {
    AUTHENTICATION: true,
    COGNITO_AUTH: true,
    DEBUG_MODE: environment === 'development',
    MOCK_DATA: environment === 'development',
    DEV_TOOLS: environment === 'development'
  }
};

// Update the runtime config for development with enhanced error handling
const configPath = path.join(__dirname, '..', 'public', 'config.js');
const configContent = `/**
 * Runtime Configuration - ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment
 * Auto-generated by setup-dev.js with CloudFormation integration
 */

window.__CONFIG__ = {
  // Build Information
  BUILD_TIME: "${devConfig.BUILD_TIME}",
  VERSION: "${devConfig.VERSION}",
  ENVIRONMENT: "${devConfig.ENVIRONMENT}",
  
  // API Configuration - prioritizes CloudFormation
  API: {
    BASE_URL: (function() {
      if (window.__CLOUDFORMATION_CONFIG__?.ApiGatewayUrl) {
        return window.__CLOUDFORMATION_CONFIG__.ApiGatewayUrl;
      }
      console.warn('⚠️ Using fallback API URL - CloudFormation config not loaded');
      return '${apiUrl}';
    })()
  },
  
  // AWS Configuration
  AWS: {
    REGION: 'us-east-1'
  },
  
  // Cognito Configuration - MUST come from CloudFormation
  COGNITO: {
    USER_POOL_ID: window.__CLOUDFORMATION_CONFIG__?.UserPoolId || null,
    CLIENT_ID: window.__CLOUDFORMATION_CONFIG__?.UserPoolClientId || null,
    REGION: 'us-east-1',
    DOMAIN: window.__CLOUDFORMATION_CONFIG__?.UserPoolDomain || null,
    REDIRECT_SIGN_IN: window.location.origin,
    REDIRECT_SIGN_OUT: window.location.origin
  },
  
  // Feature Flags
  FEATURES: {
    AUTHENTICATION: true,
    COGNITO_AUTH: true,
    DEBUG_MODE: ${environment === 'development'},
    MOCK_DATA: ${environment === 'development'},
    DEV_TOOLS: ${environment === 'development'}
  }
};

// Validation and error reporting
setTimeout(() => {
  // Check Cognito configuration
  if (window.__CONFIG__.FEATURES.AUTHENTICATION) {
    if (!window.__CONFIG__.COGNITO.USER_POOL_ID) {
      console.error('❌ CRITICAL: No Cognito USER_POOL_ID found');
      console.error('   → Check CloudFormation deployment status');
      console.error('   → Verify window.__CLOUDFORMATION_CONFIG__ is loaded');
      console.error('   → Authentication will not work without proper configuration');
    }
    if (!window.__CONFIG__.COGNITO.CLIENT_ID) {
      console.error('❌ CRITICAL: No Cognito CLIENT_ID found');
      console.error('   → Check CloudFormation deployment status');
      console.error('   → Verify window.__CLOUDFORMATION_CONFIG__ is loaded');
      console.error('   → Authentication will not work without proper configuration');
    }
  }
  
  // Check API configuration
  if (!window.__CLOUDFORMATION_CONFIG__?.ApiGatewayUrl) {
    console.warn('⚠️ API configuration using fallback - CloudFormation config not loaded');
  }
  
  console.log('✅ Configuration validation complete for ${environment}');
}, 100);
`;

// Only create config.js if it doesn't already have real CloudFormation values or if --force is used
if (fs.existsSync(configPath) && !forceSetup) {
  const existingContent = fs.readFileSync(configPath, 'utf8');
  if (existingContent.includes('REAL VALUES from CloudFormation deployment')) {
    console.log(`⚠️ Skipping config.js update - real CloudFormation config detected`);
    console.log(`   → config.js already contains real deployment values`);
    console.log(`   → Use '--force' flag to override: node scripts/setup-dev.cjs ${apiUrl} ${environment} --force`);
  } else {
    fs.writeFileSync(configPath, configContent);
    console.log('✅ Updated public/config.js for', environment);
  }
} else {
  if (forceSetup) {
    console.log('🔄 Force setup requested - overriding existing configuration');
  }
  fs.writeFileSync(configPath, configContent);
  console.log('✅ Created public/config.js for', environment);
}

// Create .env file for Vite
const envPath = path.join(__dirname, '..', '.env');
const envContent = `# ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment Configuration
# Auto-generated by setup-dev.js

# API Configuration
VITE_API_URL=${apiUrl}
VITE_SERVERLESS=false
VITE_ENVIRONMENT=${environment}

# Build Configuration
VITE_BUILD_TIME=${new Date().toISOString()}
VITE_VERSION=1.0.0-dev

# AWS Cognito Configuration - For development, use empty values to disable auth
VITE_COGNITO_USER_POOL_ID=
VITE_COGNITO_CLIENT_ID=
VITE_AWS_REGION=us-east-1
VITE_COGNITO_DOMAIN=
VITE_COGNITO_REDIRECT_SIGN_IN=http://localhost:5173
VITE_COGNITO_REDIRECT_SIGN_OUT=http://localhost:5173

# Feature Flags
VITE_ENABLE_DEBUG=true
VITE_ENABLE_MOCK_DATA=true
`;

fs.writeFileSync(envPath, envContent);
console.log('✅ Created .env file for', environment);

console.log('');
console.log(`🎉 ${environment.charAt(0).toUpperCase() + environment.slice(1)} environment configured!`);
console.log('');
console.log('📋 Configuration:');
console.log(`   API URL: ${devConfig.API_URL}`);
console.log(`   Environment: ${devConfig.ENVIRONMENT}`);
console.log(`   Version: ${devConfig.VERSION}`);
console.log('');
console.log('🚀 Next steps:');
console.log('   1. Run: npm run dev');
console.log('');
console.log('💡 To reset to production config, run: npm run setup-prod');
console.log(''); 