#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);


// Get parameters from command line (preferred) or environment variables (CI/CD friendly)
const apiUrl = process.argv[2] || process.env.VITE_API_URL || "";
if (!apiUrl) {
  console.warn("⚠️  Warning: API URL not provided via VITE_API_URL environment variable or argument");
  console.warn("This may be expected if CloudFront is not yet ready. Frontend will use relative API paths.");
  console.warn("Set VITE_API_URL environment variable or run:");
  console.warn(
    "  node setup-prod.js <API_URL> [environment] [userPoolId] [clientId] [cognitoDomain] [cloudfrontUrl]"
  );
}
const environment = process.argv[3] || process.env.VITE_ENVIRONMENT || "production";
const userPoolId = process.argv[4] || process.env.VITE_COGNITO_USER_POOL_ID || "";
const clientId = process.argv[5] || process.env.VITE_COGNITO_CLIENT_ID || "";
const cognitoDomain = process.argv[6] || process.env.VITE_COGNITO_DOMAIN || "";
const cloudfrontUrl = process.argv[7] || process.env.VITE_CLOUDFRONT_DOMAIN || "";

// Create environment configuration
const prodConfig = {
  API_URL: apiUrl,
  USER_POOL_ID: userPoolId,
  USER_POOL_CLIENT_ID: clientId,
  USER_POOL_DOMAIN: cognitoDomain,
  BUILD_TIME: new Date().toISOString(),
  VERSION: "1.0.1",
  ENVIRONMENT: environment,
};

// Update the runtime config for production
const configPath = path.join(__dirname, "..", "public", "config.js");
const configContent = `// Runtime configuration - ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment
// This file is auto-generated by setup-prod.js
window.__CONFIG__ = ${JSON.stringify(prodConfig, null, 2)};
`;

fs.writeFileSync(configPath, configContent);

// Create .env file for Vite
const envPath = path.join(__dirname, "..", ".env");
const envContent = `# ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment Configuration
# Auto-generated by setup-prod.js

# API Configuration
VITE_API_URL=${apiUrl}
VITE_SERVERLESS=true
VITE_ENVIRONMENT=${environment}

# Build Configuration
VITE_BUILD_TIME=${new Date().toISOString()}
VITE_VERSION=1.0.0

# AWS Cognito Configuration
VITE_COGNITO_USER_POOL_ID=${userPoolId}
VITE_COGNITO_CLIENT_ID=${clientId}
VITE_AWS_REGION=us-east-1
VITE_COGNITO_DOMAIN=${cognitoDomain}
VITE_COGNITO_REDIRECT_SIGN_IN=${cloudfrontUrl ? `https://${cloudfrontUrl}` : apiUrl}
VITE_COGNITO_REDIRECT_SIGN_OUT=${cloudfrontUrl ? `https://${cloudfrontUrl}` : apiUrl}

# Feature Flags
VITE_ENABLE_DEBUG=${environment === "production" ? "false" : "true"}
VITE_ENABLE_MOCK_DATA=false
`;

fs.writeFileSync(envPath, envContent);
