#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🚀 Setting up development environment...');

// Get API URL and environment name from command line or use defaults
const apiUrl = process.argv[2] || 'http://localhost:3001';
const environment = process.argv[3] || 'development';

// Create environment configuration
const devConfig = {
  API_URL: apiUrl,
  BUILD_TIME: new Date().toISOString(),
  VERSION: '1.0.0-dev',
  ENVIRONMENT: environment
};

// Update the runtime config for development
const configPath = path.join(__dirname, '..', 'public', 'config.js');
const configContent = `// Runtime configuration - ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment\n// This file is auto-generated by setup-dev.js\nwindow.__CONFIG__ = ${JSON.stringify(devConfig, null, 2)};\n`;

fs.writeFileSync(configPath, configContent);
console.log('✅ Updated public/config.js for', environment);

// Create .env file for Vite
const envPath = path.join(__dirname, '..', '.env');
const envContent = `# ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment Configuration\n# Auto-generated by setup-dev.js\n\n# API Configuration\nVITE_API_URL=${apiUrl}\nVITE_SERVERLESS=false\nVITE_ENVIRONMENT=${environment}\n\n# Build Configuration\nVITE_BUILD_TIME=${new Date().toISOString()}\nVITE_VERSION=1.0.0-dev\n\n# Feature Flags\nVITE_ENABLE_DEBUG=true\nVITE_ENABLE_MOCK_DATA=true\n`;

fs.writeFileSync(envPath, envContent);
console.log('✅ Created .env file for', environment);

console.log('');
console.log(`🎉 ${environment.charAt(0).toUpperCase() + environment.slice(1)} environment configured!`);
console.log('');
console.log('📋 Configuration:');
console.log(`   API URL: ${devConfig.API_URL}`);
console.log(`   Environment: ${devConfig.ENVIRONMENT}`);
console.log(`   Version: ${devConfig.VERSION}`);
console.log('');
console.log('🚀 Next steps:');
console.log('   1. Run: npm run dev');
console.log('');
console.log('💡 To reset to production config, run: npm run setup-prod');
console.log(''); 