#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);


// Get API URL and environment name from command line, env vars, or use defaults
// DEVELOPMENT: Always use localhost:8000 (dev_server.py), never production AWS in config
const isDev = process.env.NODE_ENV !== "production" && !process.argv.includes("--production");
const apiUrl = isDev
  ? "http://localhost:8000"  // Match dev_server.py port
  : (process.argv[2] || process.env.API_URL || process.env.VITE_API_URL || "http://localhost:8000");
const environment = process.argv[3] || process.env.ENVIRONMENT || "development";

// Create environment configuration
const devConfig = {
  API_URL: apiUrl,
  USER_POOL_ID: isDev ? 'us-east-1_DUMMY' : 'us-east-1_XJpLb9SKX',
  USER_POOL_CLIENT_ID: isDev ? 'dummy-client-id' : '6smb0vrcidd9kvhju2kn2a3qrl',
  USER_POOL_DOMAIN: isDev ? 'dummy-domain' : 'stocks-trading-dev-626216981288.auth.626216981288.amazoncognito.com',
  BUILD_TIME: new Date().toISOString(),
  VERSION: "1.0.0-dev",
  ENVIRONMENT: environment,
};

// Update the runtime config for development
const configPath = path.join(__dirname, "..", "public", "config.js");
const configContent = `// Runtime configuration - ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment\n// This file is auto-generated by setup-dev.js\nwindow.__CONFIG__ = ${JSON.stringify(devConfig, null, 2)};\n`;

fs.writeFileSync(configPath, configContent);

// SECURITY: Do NOT create .env files - violates CLAUDE.md rules
// Instead, pass environment variables directly when running npm commands
// Example: VITE_API_URL=http://localhost:3001 npm run dev

console.log(
  `🎉 ${environment.charAt(0).toUpperCase() + environment.slice(1)} environment configured!`
);
