#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);


// Get parameters from command line (preferred) or environment variables (CI/CD friendly)
const apiUrl = process.argv[2] || process.env.VITE_API_URL || "";
const environment = process.argv[3] || process.env.VITE_ENVIRONMENT || "development";

// CRITICAL: Prevent localhost from being written to production config
if (!apiUrl && environment === "production") {
  console.error("❌ ERROR: API_URL is required for production builds");
  console.error("Set VITE_API_URL environment variable or pass as first argument:");
  console.error("  VITE_API_URL=https://api.example.com node setup-prod.js");
  console.error("  OR: node setup-prod.js https://api.example.com production");
  process.exit(1);
}

if (!apiUrl && environment !== "production") {
  console.warn("⚠️  Warning: API URL not provided. Frontend will use relative paths for dev proxy.");
}
const userPoolId = process.argv[4] || process.env.VITE_COGNITO_USER_POOL_ID || "";
const clientId = process.argv[5] || process.env.VITE_COGNITO_CLIENT_ID || "";
const cognitoDomain = process.argv[6] || process.env.VITE_COGNITO_DOMAIN || "";
const cloudfrontUrl = process.argv[7] || process.env.VITE_CLOUDFRONT_DOMAIN || "";

// Create environment configuration
const prodConfig = {
  API_URL: apiUrl,
  USER_POOL_ID: userPoolId,
  USER_POOL_CLIENT_ID: clientId,
  USER_POOL_DOMAIN: cognitoDomain,
  BUILD_TIME: new Date().toISOString(),
  VERSION: "1.0.1",
  ENVIRONMENT: environment,
};

// Update the runtime config for production
const configPath = path.join(__dirname, "..", "public", "config.js");
const configContent = `// Runtime configuration - ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment
// This file is auto-generated by setup-prod.js
window.__CONFIG__ = ${JSON.stringify(prodConfig, null, 2)};
`;

fs.writeFileSync(configPath, configContent);

console.log(`✓ Production config created at: ${configPath}`);
console.log(`  API_URL: ${apiUrl || "(relative paths)"}`);
console.log(`  Environment: ${environment}`);
console.log(`  User Pool ID: ${userPoolId ? "SET" : "(not set)"}`);
