#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🔧 Setting up development environment...');

// Create development environment configuration
const devConfig = {
  API_URL: 'http://localhost:3001',
  BUILD_TIME: new Date().toISOString(),
  VERSION: '1.0.0-dev',
  ENVIRONMENT: 'development'
};

// Update the runtime config for development
const configPath = path.join(__dirname, '..', 'public', 'config.js');
const configContent = `// Runtime configuration - Development Environment
// This file is auto-generated by setup-dev.js
window.__CONFIG__ = ${JSON.stringify(devConfig, null, 2)};
`;

fs.writeFileSync(configPath, configContent);
console.log('✅ Updated public/config.js for development');

// Create .env file for Vite
const envPath = path.join(__dirname, '..', '.env');
const envContent = `# Development Environment Configuration
# Auto-generated by setup-dev.js

# API Configuration
VITE_API_URL=http://localhost:3001
VITE_SERVERLESS=false
VITE_ENVIRONMENT=development

# Build Configuration
VITE_BUILD_TIME=${new Date().toISOString()}
VITE_VERSION=1.0.0-dev

# Feature Flags
VITE_ENABLE_DEBUG=true
VITE_ENABLE_MOCK_DATA=false
`;

fs.writeFileSync(envPath, envContent);
console.log('✅ Created .env file for development');

console.log('');
console.log('🎉 Development environment configured!');
console.log('');
console.log('📋 Configuration:');
console.log(`   API URL: ${devConfig.API_URL}`);
console.log(`   Environment: ${devConfig.ENVIRONMENT}`);
console.log(`   Version: ${devConfig.VERSION}`);
console.log('');
console.log('🚀 Next steps:');
console.log('   1. Start your backend server on localhost:3001');
console.log('   2. Run: npm run dev');
console.log('   3. Open: http://localhost:3000');
console.log('');
console.log('💡 To reset to production config, run: npm run setup-prod'); 