// Runtime configuration - Development Environment
// This file is auto-generated by setup-dev.js
window.__CONFIG__ = {
  "API_URL": "http://localhost:3001",
  "BUILD_TIME": "2026-01-05T13:27:30.749Z",
  "VERSION": "1.0.0-dev",
  "ENVIRONMENT": "development"
};
