"""INSERT-builder functions for value_metrics/quality_metrics/growth_metrics, extracted from
ValueQualityGrowthMetricsLoader (2026-09-16 file-size-ratchet split: the loader file was past
the repo's 2000-line hard ceiling). Pure functions of (cur, row) - no loader instance state.
"""

from typing import Any


def insert_value_metrics(cur: Any, row: dict[str, Any]) -> None:
    """Insert value_metrics row."""
    cur.execute(
        """
        INSERT INTO value_metrics
        (symbol, pe_ratio, pb_ratio, ps_ratio, peg_ratio, dividend_yield, net_payout_yield, fcf_yield, forward_pe, enterprise_value, ev_ebitda, ev_revenue, market_cap, intrinsic_value_per_share, margin_of_safety_pct, value_score, data_unavailable, reason, data_source, updated_at,
         pe_ratio_unavailable_reason, pb_ratio_unavailable_reason, ps_ratio_unavailable_reason, peg_ratio_unavailable_reason,
         dividend_yield_unavailable_reason, fcf_yield_unavailable_reason, forward_pe_unavailable_reason, ev_ebitda_unavailable_reason, ev_revenue_unavailable_reason,
         market_cap_unavailable_reason, held_percent_institutions, held_percent_institutions_unavailable_reason,
         intrinsic_value_unavailable_reason, margin_of_safety_unavailable_reason)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (symbol) DO UPDATE SET
            pe_ratio = EXCLUDED.pe_ratio,
            pb_ratio = EXCLUDED.pb_ratio,
            ps_ratio = EXCLUDED.ps_ratio,
            peg_ratio = EXCLUDED.peg_ratio,
            dividend_yield = EXCLUDED.dividend_yield,
            net_payout_yield = EXCLUDED.net_payout_yield,
            fcf_yield = EXCLUDED.fcf_yield,
            forward_pe = EXCLUDED.forward_pe,
            enterprise_value = EXCLUDED.enterprise_value,
            ev_ebitda = EXCLUDED.ev_ebitda,
            ev_revenue = EXCLUDED.ev_revenue,
            market_cap = EXCLUDED.market_cap,
            intrinsic_value_per_share = EXCLUDED.intrinsic_value_per_share,
            margin_of_safety_pct = EXCLUDED.margin_of_safety_pct,
            value_score = EXCLUDED.value_score,
            pe_ratio_unavailable_reason = EXCLUDED.pe_ratio_unavailable_reason,
            pb_ratio_unavailable_reason = EXCLUDED.pb_ratio_unavailable_reason,
            ps_ratio_unavailable_reason = EXCLUDED.ps_ratio_unavailable_reason,
            peg_ratio_unavailable_reason = EXCLUDED.peg_ratio_unavailable_reason,
            dividend_yield_unavailable_reason = EXCLUDED.dividend_yield_unavailable_reason,
            fcf_yield_unavailable_reason = EXCLUDED.fcf_yield_unavailable_reason,
            forward_pe_unavailable_reason = EXCLUDED.forward_pe_unavailable_reason,
            ev_ebitda_unavailable_reason = EXCLUDED.ev_ebitda_unavailable_reason,
            ev_revenue_unavailable_reason = EXCLUDED.ev_revenue_unavailable_reason,
            market_cap_unavailable_reason = EXCLUDED.market_cap_unavailable_reason,
            held_percent_institutions = EXCLUDED.held_percent_institutions,
            held_percent_institutions_unavailable_reason = EXCLUDED.held_percent_institutions_unavailable_reason,
            intrinsic_value_unavailable_reason = EXCLUDED.intrinsic_value_unavailable_reason,
            margin_of_safety_unavailable_reason = EXCLUDED.margin_of_safety_unavailable_reason,
            data_unavailable = EXCLUDED.data_unavailable,
            reason = EXCLUDED.reason,
            data_source = EXCLUDED.data_source,
            updated_at = EXCLUDED.updated_at
        """,
        (
            row["symbol"],
            row["pe_ratio"],
            row["pb_ratio"],
            row["ps_ratio"],
            row["peg_ratio"],
            row["dividend_yield"],
            row.get("net_payout_yield"),
            row["fcf_yield"],
            row.get("forward_pe"),
            row.get("enterprise_value"),
            row.get("ev_ebitda"),
            row.get("ev_revenue"),
            row.get("market_cap"),
            row.get("intrinsic_value_per_share"),
            row.get("margin_of_safety_pct"),
            row.get("value_score"),
            row["data_unavailable"],
            row.get("reason"),
            row.get("data_source", "sec_audited"),
            row["updated_at"],
            row.get("pe_ratio_unavailable_reason"),
            row.get("pb_ratio_unavailable_reason"),
            row.get("ps_ratio_unavailable_reason"),
            row.get("peg_ratio_unavailable_reason"),
            row.get("dividend_yield_unavailable_reason"),
            row.get("fcf_yield_unavailable_reason"),
            row.get("forward_pe_unavailable_reason"),
            row.get("ev_ebitda_unavailable_reason"),
            row.get("ev_revenue_unavailable_reason"),
            row.get("market_cap_unavailable_reason"),
            row.get("held_percent_institutions"),
            row.get("held_percent_institutions_unavailable_reason"),
            row.get("intrinsic_value_unavailable_reason"),
            row.get("margin_of_safety_unavailable_reason"),
        ),
    )


def insert_quality_metrics(cur: Any, row: dict[str, Any]) -> None:
    """Insert quality_metrics row."""
    cur.execute(
        """
        INSERT INTO quality_metrics
        (symbol, roe, roa, operating_margin, net_margin, debt_to_equity, debt_to_assets, current_ratio, quick_ratio, interest_coverage, quality_score, ebitda, ebitda_margin, data_unavailable, reason, data_source, updated_at,
         gross_margin, roic_pct, fcf_to_net_income, ocf_to_net_income, payout_ratio,
         free_cash_flow, operating_cash_flow, total_debt, total_cash, cash_per_share,
         earnings_growth_yoy, revenue_growth_yoy,
         net_income_growth_yoy, operating_income_growth_yoy, gross_margin_trend, operating_margin_trend, net_margin_trend,
         roe_trend, sustainable_growth_rate, quarterly_growth_momentum, fcf_growth_yoy, ocf_growth_yoy, asset_growth_yoy,
         earnings_surprise_avg, eps_growth_stability, earnings_beat_rate, consecutive_positive_quarters,
         earnings_growth_4q_avg,
         gross_profitability, operating_profitability, accruals_ratio, margin_volatility,
         roe_unavailable_reason, roa_unavailable_reason, operating_margin_unavailable_reason, net_margin_unavailable_reason,
         debt_to_equity_unavailable_reason, current_ratio_unavailable_reason, quick_ratio_unavailable_reason,
         interest_coverage_unavailable_reason, debt_to_assets_unavailable_reason, quality_score_unavailable_reason,
         gross_margin_unavailable_reason, ebitda_unavailable_reason, ebitda_margin_unavailable_reason, roic_pct_unavailable_reason,
         fcf_to_net_income_unavailable_reason, ocf_to_net_income_unavailable_reason, payout_ratio_unavailable_reason,
         free_cash_flow_unavailable_reason, operating_cash_flow_unavailable_reason, total_debt_unavailable_reason,
         total_cash_unavailable_reason, cash_per_share_unavailable_reason, earnings_growth_yoy_unavailable_reason,
         revenue_growth_yoy_unavailable_reason, net_income_growth_yoy_unavailable_reason, operating_income_growth_yoy_unavailable_reason,
         gross_margin_trend_unavailable_reason, operating_margin_trend_unavailable_reason, net_margin_trend_unavailable_reason,
         roe_trend_unavailable_reason, sustainable_growth_rate_unavailable_reason, quarterly_growth_momentum_unavailable_reason,
         fcf_growth_yoy_unavailable_reason, ocf_growth_yoy_unavailable_reason, asset_growth_yoy_unavailable_reason,
         earnings_growth_4q_avg_unavailable_reason,
         gross_profitability_unavailable_reason, operating_profitability_unavailable_reason,
         accruals_ratio_unavailable_reason, margin_volatility_unavailable_reason,
         roce_pct, roce_pct_unavailable_reason, fcf_margin, fcf_margin_unavailable_reason,
         asset_turnover, asset_turnover_unavailable_reason,
         earnings_surprise_avg_unavailable_reason, eps_growth_stability_unavailable_reason,
         earnings_beat_rate_unavailable_reason, consecutive_positive_quarters_unavailable_reason,
         earnings_variability, earnings_variability_unavailable_reason)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (symbol) DO UPDATE SET
            roe = EXCLUDED.roe,
            roa = EXCLUDED.roa,
            operating_margin = EXCLUDED.operating_margin,
            net_margin = EXCLUDED.net_margin,
            debt_to_equity = EXCLUDED.debt_to_equity,
            debt_to_assets = EXCLUDED.debt_to_assets,
            current_ratio = EXCLUDED.current_ratio,
            quick_ratio = EXCLUDED.quick_ratio,
            interest_coverage = EXCLUDED.interest_coverage,
            quality_score = EXCLUDED.quality_score,
            ebitda = EXCLUDED.ebitda,
            ebitda_margin = EXCLUDED.ebitda_margin,
            net_income_growth_yoy = EXCLUDED.net_income_growth_yoy,
            operating_income_growth_yoy = EXCLUDED.operating_income_growth_yoy,
            gross_margin_trend = EXCLUDED.gross_margin_trend,
            operating_margin_trend = EXCLUDED.operating_margin_trend,
            net_margin_trend = EXCLUDED.net_margin_trend,
            roe_trend = EXCLUDED.roe_trend,
            sustainable_growth_rate = EXCLUDED.sustainable_growth_rate,
            quarterly_growth_momentum = EXCLUDED.quarterly_growth_momentum,
            fcf_growth_yoy = EXCLUDED.fcf_growth_yoy,
            ocf_growth_yoy = EXCLUDED.ocf_growth_yoy,
            asset_growth_yoy = EXCLUDED.asset_growth_yoy,
            earnings_surprise_avg = EXCLUDED.earnings_surprise_avg,
            eps_growth_stability = EXCLUDED.eps_growth_stability,
            earnings_beat_rate = EXCLUDED.earnings_beat_rate,
            consecutive_positive_quarters = EXCLUDED.consecutive_positive_quarters,
            earnings_growth_4q_avg = EXCLUDED.earnings_growth_4q_avg,
            gross_profitability = EXCLUDED.gross_profitability,
            operating_profitability = EXCLUDED.operating_profitability,
            accruals_ratio = EXCLUDED.accruals_ratio,
            margin_volatility = EXCLUDED.margin_volatility,
            earnings_variability = EXCLUDED.earnings_variability,
            earnings_variability_unavailable_reason = EXCLUDED.earnings_variability_unavailable_reason,
            gross_margin = EXCLUDED.gross_margin,
            roic_pct = EXCLUDED.roic_pct,
            fcf_to_net_income = EXCLUDED.fcf_to_net_income,
            ocf_to_net_income = EXCLUDED.ocf_to_net_income,
            payout_ratio = EXCLUDED.payout_ratio,
            free_cash_flow = EXCLUDED.free_cash_flow,
            operating_cash_flow = EXCLUDED.operating_cash_flow,
            total_debt = EXCLUDED.total_debt,
            total_cash = EXCLUDED.total_cash,
            cash_per_share = EXCLUDED.cash_per_share,
            earnings_growth_yoy = EXCLUDED.earnings_growth_yoy,
            revenue_growth_yoy = EXCLUDED.revenue_growth_yoy,
            roe_unavailable_reason = EXCLUDED.roe_unavailable_reason,
            roa_unavailable_reason = EXCLUDED.roa_unavailable_reason,
            operating_margin_unavailable_reason = EXCLUDED.operating_margin_unavailable_reason,
            net_margin_unavailable_reason = EXCLUDED.net_margin_unavailable_reason,
            debt_to_equity_unavailable_reason = EXCLUDED.debt_to_equity_unavailable_reason,
            current_ratio_unavailable_reason = EXCLUDED.current_ratio_unavailable_reason,
            quick_ratio_unavailable_reason = EXCLUDED.quick_ratio_unavailable_reason,
            interest_coverage_unavailable_reason = EXCLUDED.interest_coverage_unavailable_reason,
            debt_to_assets_unavailable_reason = EXCLUDED.debt_to_assets_unavailable_reason,
            quality_score_unavailable_reason = EXCLUDED.quality_score_unavailable_reason,
            gross_margin_unavailable_reason = EXCLUDED.gross_margin_unavailable_reason,
            ebitda_unavailable_reason = EXCLUDED.ebitda_unavailable_reason,
            ebitda_margin_unavailable_reason = EXCLUDED.ebitda_margin_unavailable_reason,
            roic_pct_unavailable_reason = EXCLUDED.roic_pct_unavailable_reason,
            fcf_to_net_income_unavailable_reason = EXCLUDED.fcf_to_net_income_unavailable_reason,
            ocf_to_net_income_unavailable_reason = EXCLUDED.ocf_to_net_income_unavailable_reason,
            payout_ratio_unavailable_reason = EXCLUDED.payout_ratio_unavailable_reason,
            free_cash_flow_unavailable_reason = EXCLUDED.free_cash_flow_unavailable_reason,
            operating_cash_flow_unavailable_reason = EXCLUDED.operating_cash_flow_unavailable_reason,
            total_debt_unavailable_reason = EXCLUDED.total_debt_unavailable_reason,
            total_cash_unavailable_reason = EXCLUDED.total_cash_unavailable_reason,
            cash_per_share_unavailable_reason = EXCLUDED.cash_per_share_unavailable_reason,
            earnings_growth_yoy_unavailable_reason = EXCLUDED.earnings_growth_yoy_unavailable_reason,
            revenue_growth_yoy_unavailable_reason = EXCLUDED.revenue_growth_yoy_unavailable_reason,
            net_income_growth_yoy_unavailable_reason = EXCLUDED.net_income_growth_yoy_unavailable_reason,
            operating_income_growth_yoy_unavailable_reason = EXCLUDED.operating_income_growth_yoy_unavailable_reason,
            gross_margin_trend_unavailable_reason = EXCLUDED.gross_margin_trend_unavailable_reason,
            operating_margin_trend_unavailable_reason = EXCLUDED.operating_margin_trend_unavailable_reason,
            net_margin_trend_unavailable_reason = EXCLUDED.net_margin_trend_unavailable_reason,
            roe_trend_unavailable_reason = EXCLUDED.roe_trend_unavailable_reason,
            sustainable_growth_rate_unavailable_reason = EXCLUDED.sustainable_growth_rate_unavailable_reason,
            quarterly_growth_momentum_unavailable_reason = EXCLUDED.quarterly_growth_momentum_unavailable_reason,
            fcf_growth_yoy_unavailable_reason = EXCLUDED.fcf_growth_yoy_unavailable_reason,
            ocf_growth_yoy_unavailable_reason = EXCLUDED.ocf_growth_yoy_unavailable_reason,
            asset_growth_yoy_unavailable_reason = EXCLUDED.asset_growth_yoy_unavailable_reason,
            earnings_growth_4q_avg_unavailable_reason = EXCLUDED.earnings_growth_4q_avg_unavailable_reason,
            gross_profitability_unavailable_reason = EXCLUDED.gross_profitability_unavailable_reason,
            operating_profitability_unavailable_reason = EXCLUDED.operating_profitability_unavailable_reason,
            accruals_ratio_unavailable_reason = EXCLUDED.accruals_ratio_unavailable_reason,
            margin_volatility_unavailable_reason = EXCLUDED.margin_volatility_unavailable_reason,
            roce_pct = EXCLUDED.roce_pct,
            roce_pct_unavailable_reason = EXCLUDED.roce_pct_unavailable_reason,
            fcf_margin = EXCLUDED.fcf_margin,
            fcf_margin_unavailable_reason = EXCLUDED.fcf_margin_unavailable_reason,
            asset_turnover = EXCLUDED.asset_turnover,
            asset_turnover_unavailable_reason = EXCLUDED.asset_turnover_unavailable_reason,
            earnings_surprise_avg_unavailable_reason = EXCLUDED.earnings_surprise_avg_unavailable_reason,
            eps_growth_stability_unavailable_reason = EXCLUDED.eps_growth_stability_unavailable_reason,
            earnings_beat_rate_unavailable_reason = EXCLUDED.earnings_beat_rate_unavailable_reason,
            consecutive_positive_quarters_unavailable_reason = EXCLUDED.consecutive_positive_quarters_unavailable_reason,
            data_unavailable = EXCLUDED.data_unavailable,
            reason = EXCLUDED.reason,
            data_source = EXCLUDED.data_source,
            updated_at = EXCLUDED.updated_at
        """,
        (
            row["symbol"],
            row["roe"],
            row.get("roa"),
            row["operating_margin"],
            row["net_margin"],
            row["debt_to_equity"],
            row.get("debt_to_assets"),
            row.get("current_ratio"),
            row.get("quick_ratio"),
            row.get("interest_coverage"),
            row.get("quality_score"),
            row.get("ebitda"),
            row.get("ebitda_margin"),
            row["data_unavailable"],
            row.get("reason"),
            row.get("data_source", "sec_audited"),
            row["updated_at"],
            row.get("gross_margin"),
            row.get("roic_pct"),
            row.get("fcf_to_net_income"),
            row.get("ocf_to_net_income"),
            row.get("payout_ratio"),
            row.get("free_cash_flow"),
            row.get("operating_cash_flow"),
            row.get("total_debt"),
            row.get("total_cash"),
            row.get("cash_per_share"),
            row.get("earnings_growth_yoy"),
            row.get("revenue_growth_yoy"),
            row.get("net_income_growth_yoy"),
            row.get("operating_income_growth_yoy"),
            row.get("gross_margin_trend"),
            row.get("operating_margin_trend"),
            row.get("net_margin_trend"),
            row.get("roe_trend"),
            row.get("sustainable_growth_rate"),
            row.get("quarterly_growth_momentum"),
            row.get("fcf_growth_yoy"),
            row.get("ocf_growth_yoy"),
            row.get("asset_growth_yoy"),
            row.get("earnings_surprise_avg"),
            row.get("eps_growth_stability"),
            row.get("earnings_beat_rate"),
            row.get("consecutive_positive_quarters"),
            row.get("earnings_growth_4q_avg"),
            row.get("gross_profitability"),
            row.get("operating_profitability"),
            row.get("accruals_ratio"),
            row.get("margin_volatility"),
            row.get("roe_unavailable_reason"),
            row.get("roa_unavailable_reason"),
            row.get("operating_margin_unavailable_reason"),
            row.get("net_margin_unavailable_reason"),
            row.get("debt_to_equity_unavailable_reason"),
            row.get("current_ratio_unavailable_reason"),
            row.get("quick_ratio_unavailable_reason"),
            row.get("interest_coverage_unavailable_reason"),
            row.get("debt_to_assets_unavailable_reason"),
            row.get("quality_score_unavailable_reason"),
            row.get("gross_margin_unavailable_reason"),
            row.get("ebitda_unavailable_reason"),
            row.get("ebitda_margin_unavailable_reason"),
            row.get("roic_pct_unavailable_reason"),
            row.get("fcf_to_net_income_unavailable_reason"),
            row.get("ocf_to_net_income_unavailable_reason"),
            row.get("payout_ratio_unavailable_reason"),
            row.get("free_cash_flow_unavailable_reason"),
            row.get("operating_cash_flow_unavailable_reason"),
            row.get("total_debt_unavailable_reason"),
            row.get("total_cash_unavailable_reason"),
            row.get("cash_per_share_unavailable_reason"),
            row.get("earnings_growth_yoy_unavailable_reason"),
            row.get("revenue_growth_yoy_unavailable_reason"),
            row.get("net_income_growth_yoy_unavailable_reason"),
            row.get("operating_income_growth_yoy_unavailable_reason"),
            row.get("gross_margin_trend_unavailable_reason"),
            row.get("operating_margin_trend_unavailable_reason"),
            row.get("net_margin_trend_unavailable_reason"),
            row.get("roe_trend_unavailable_reason"),
            row.get("sustainable_growth_rate_unavailable_reason"),
            row.get("quarterly_growth_momentum_unavailable_reason"),
            row.get("fcf_growth_yoy_unavailable_reason"),
            row.get("ocf_growth_yoy_unavailable_reason"),
            row.get("asset_growth_yoy_unavailable_reason"),
            row.get("earnings_growth_4q_avg_unavailable_reason"),
            row.get("gross_profitability_unavailable_reason"),
            row.get("operating_profitability_unavailable_reason"),
            row.get("accruals_ratio_unavailable_reason"),
            row.get("margin_volatility_unavailable_reason"),
            row.get("roce_pct"),
            row.get("roce_pct_unavailable_reason"),
            row.get("fcf_margin"),
            row.get("fcf_margin_unavailable_reason"),
            row.get("asset_turnover"),
            row.get("asset_turnover_unavailable_reason"),
            row.get("earnings_surprise_avg_unavailable_reason"),
            row.get("eps_growth_stability_unavailable_reason"),
            row.get("earnings_beat_rate_unavailable_reason"),
            row.get("consecutive_positive_quarters_unavailable_reason"),
            row.get("earnings_variability"),
            row.get("earnings_variability_unavailable_reason"),
        ),
    )


def insert_growth_metrics(cur: Any, row: dict[str, Any]) -> None:
    """Insert growth_metrics row with multi-year CAGR values and trend fields."""
    cur.execute(
        """
        INSERT INTO growth_metrics
        (symbol, revenue_growth_1y, revenue_growth_3y, revenue_growth_5y, eps_growth_1y, eps_growth_3y, eps_growth_5y,
         eps_growth_trend_5y, sps_growth_trend_5y,
         book_value_growth,
         net_income_growth_yoy, operating_income_growth_yoy, gross_margin_trend, operating_margin_trend, net_margin_trend,
         roe_trend, sustainable_growth_rate, quarterly_growth_momentum, fcf_growth_yoy, ocf_growth_yoy, asset_growth_yoy,
         consecutive_positive_quarters, earnings_growth_4q_avg, eps_growth_stability,
         earnings_surprise_avg, earnings_beat_rate,
         forward_eps_growth_current_fy, forward_eps_growth_next_fy, forward_revenue_growth_next_fy, eps_estimate_revision_90d_pct,
         data_unavailable, reason, data_source, updated_at,
         revenue_growth_1y_unavailable_reason, revenue_growth_3y_unavailable_reason, revenue_growth_5y_unavailable_reason,
         eps_growth_1y_unavailable_reason, eps_growth_3y_unavailable_reason, eps_growth_5y_unavailable_reason,
         eps_growth_trend_5y_unavailable_reason, sps_growth_trend_5y_unavailable_reason,
         book_value_growth_unavailable_reason,
         net_income_growth_yoy_unavailable_reason, operating_income_growth_yoy_unavailable_reason, gross_margin_trend_unavailable_reason,
         operating_margin_trend_unavailable_reason, net_margin_trend_unavailable_reason, roe_trend_unavailable_reason,
         sustainable_growth_rate_unavailable_reason, quarterly_growth_momentum_unavailable_reason, fcf_growth_yoy_unavailable_reason,
         ocf_growth_yoy_unavailable_reason, asset_growth_yoy_unavailable_reason,
         consecutive_positive_quarters_unavailable_reason, earnings_growth_4q_avg_unavailable_reason, eps_growth_stability_unavailable_reason,
         earnings_surprise_avg_unavailable_reason, earnings_beat_rate_unavailable_reason,
         forward_eps_growth_current_fy_unavailable_reason, forward_eps_growth_next_fy_unavailable_reason,
         forward_revenue_growth_next_fy_unavailable_reason, eps_estimate_revision_90d_pct_unavailable_reason)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (symbol) DO UPDATE SET
            revenue_growth_1y = EXCLUDED.revenue_growth_1y,
            revenue_growth_3y = EXCLUDED.revenue_growth_3y,
            revenue_growth_5y = EXCLUDED.revenue_growth_5y,
            eps_growth_1y = EXCLUDED.eps_growth_1y,
            eps_growth_3y = EXCLUDED.eps_growth_3y,
            eps_growth_5y = EXCLUDED.eps_growth_5y,
            eps_growth_trend_5y = EXCLUDED.eps_growth_trend_5y,
            sps_growth_trend_5y = EXCLUDED.sps_growth_trend_5y,
            book_value_growth = EXCLUDED.book_value_growth,
            net_income_growth_yoy = EXCLUDED.net_income_growth_yoy,
            operating_income_growth_yoy = EXCLUDED.operating_income_growth_yoy,
            gross_margin_trend = EXCLUDED.gross_margin_trend,
            operating_margin_trend = EXCLUDED.operating_margin_trend,
            net_margin_trend = EXCLUDED.net_margin_trend,
            roe_trend = EXCLUDED.roe_trend,
            sustainable_growth_rate = EXCLUDED.sustainable_growth_rate,
            quarterly_growth_momentum = EXCLUDED.quarterly_growth_momentum,
            fcf_growth_yoy = EXCLUDED.fcf_growth_yoy,
            ocf_growth_yoy = EXCLUDED.ocf_growth_yoy,
            asset_growth_yoy = EXCLUDED.asset_growth_yoy,
            consecutive_positive_quarters = EXCLUDED.consecutive_positive_quarters,
            earnings_growth_4q_avg = EXCLUDED.earnings_growth_4q_avg,
            eps_growth_stability = EXCLUDED.eps_growth_stability,
            earnings_surprise_avg = EXCLUDED.earnings_surprise_avg,
            earnings_beat_rate = EXCLUDED.earnings_beat_rate,
            forward_eps_growth_current_fy = EXCLUDED.forward_eps_growth_current_fy,
            forward_eps_growth_next_fy = EXCLUDED.forward_eps_growth_next_fy,
            forward_revenue_growth_next_fy = EXCLUDED.forward_revenue_growth_next_fy,
            eps_estimate_revision_90d_pct = EXCLUDED.eps_estimate_revision_90d_pct,
            revenue_growth_1y_unavailable_reason = EXCLUDED.revenue_growth_1y_unavailable_reason,
            revenue_growth_3y_unavailable_reason = EXCLUDED.revenue_growth_3y_unavailable_reason,
            revenue_growth_5y_unavailable_reason = EXCLUDED.revenue_growth_5y_unavailable_reason,
            eps_growth_1y_unavailable_reason = EXCLUDED.eps_growth_1y_unavailable_reason,
            eps_growth_3y_unavailable_reason = EXCLUDED.eps_growth_3y_unavailable_reason,
            eps_growth_5y_unavailable_reason = EXCLUDED.eps_growth_5y_unavailable_reason,
            eps_growth_trend_5y_unavailable_reason = EXCLUDED.eps_growth_trend_5y_unavailable_reason,
            sps_growth_trend_5y_unavailable_reason = EXCLUDED.sps_growth_trend_5y_unavailable_reason,
            book_value_growth_unavailable_reason = EXCLUDED.book_value_growth_unavailable_reason,
            net_income_growth_yoy_unavailable_reason = EXCLUDED.net_income_growth_yoy_unavailable_reason,
            operating_income_growth_yoy_unavailable_reason = EXCLUDED.operating_income_growth_yoy_unavailable_reason,
            gross_margin_trend_unavailable_reason = EXCLUDED.gross_margin_trend_unavailable_reason,
            operating_margin_trend_unavailable_reason = EXCLUDED.operating_margin_trend_unavailable_reason,
            net_margin_trend_unavailable_reason = EXCLUDED.net_margin_trend_unavailable_reason,
            roe_trend_unavailable_reason = EXCLUDED.roe_trend_unavailable_reason,
            sustainable_growth_rate_unavailable_reason = EXCLUDED.sustainable_growth_rate_unavailable_reason,
            quarterly_growth_momentum_unavailable_reason = EXCLUDED.quarterly_growth_momentum_unavailable_reason,
            fcf_growth_yoy_unavailable_reason = EXCLUDED.fcf_growth_yoy_unavailable_reason,
            ocf_growth_yoy_unavailable_reason = EXCLUDED.ocf_growth_yoy_unavailable_reason,
            asset_growth_yoy_unavailable_reason = EXCLUDED.asset_growth_yoy_unavailable_reason,
            consecutive_positive_quarters_unavailable_reason = EXCLUDED.consecutive_positive_quarters_unavailable_reason,
            earnings_growth_4q_avg_unavailable_reason = EXCLUDED.earnings_growth_4q_avg_unavailable_reason,
            eps_growth_stability_unavailable_reason = EXCLUDED.eps_growth_stability_unavailable_reason,
            earnings_surprise_avg_unavailable_reason = EXCLUDED.earnings_surprise_avg_unavailable_reason,
            earnings_beat_rate_unavailable_reason = EXCLUDED.earnings_beat_rate_unavailable_reason,
            forward_eps_growth_current_fy_unavailable_reason = EXCLUDED.forward_eps_growth_current_fy_unavailable_reason,
            forward_eps_growth_next_fy_unavailable_reason = EXCLUDED.forward_eps_growth_next_fy_unavailable_reason,
            forward_revenue_growth_next_fy_unavailable_reason = EXCLUDED.forward_revenue_growth_next_fy_unavailable_reason,
            eps_estimate_revision_90d_pct_unavailable_reason = EXCLUDED.eps_estimate_revision_90d_pct_unavailable_reason,
            data_unavailable = EXCLUDED.data_unavailable,
            reason = EXCLUDED.reason,
            data_source = EXCLUDED.data_source,
            updated_at = EXCLUDED.updated_at
        """,
        (
            row["symbol"],
            row.get("revenue_growth_1y"),
            row.get("revenue_growth_3y"),
            row.get("revenue_growth_5y"),
            row.get("eps_growth_1y"),
            row.get("eps_growth_3y"),
            row.get("eps_growth_5y"),
            row.get("eps_growth_trend_5y"),
            row.get("sps_growth_trend_5y"),
            row.get("book_value_growth"),
            row.get("net_income_growth_yoy"),
            row.get("operating_income_growth_yoy"),
            row.get("gross_margin_trend"),
            row.get("operating_margin_trend"),
            row.get("net_margin_trend"),
            row.get("roe_trend"),
            row.get("sustainable_growth_rate"),
            row.get("quarterly_growth_momentum"),
            row.get("fcf_growth_yoy"),
            row.get("ocf_growth_yoy"),
            row.get("asset_growth_yoy"),
            row.get("consecutive_positive_quarters"),
            row.get("earnings_growth_4q_avg"),
            row.get("eps_growth_stability"),
            row.get("earnings_surprise_avg"),
            row.get("earnings_beat_rate"),
            row.get("forward_eps_growth_current_fy"),
            row.get("forward_eps_growth_next_fy"),
            row.get("forward_revenue_growth_next_fy"),
            row.get("eps_estimate_revision_90d_pct"),
            row["data_unavailable"],
            row.get("reason"),
            row.get("data_source", "sec_audited"),
            row["updated_at"],
            row.get("revenue_growth_1y_unavailable_reason"),
            row.get("revenue_growth_3y_unavailable_reason"),
            row.get("revenue_growth_5y_unavailable_reason"),
            row.get("eps_growth_1y_unavailable_reason"),
            row.get("eps_growth_3y_unavailable_reason"),
            row.get("eps_growth_5y_unavailable_reason"),
            row.get("eps_growth_trend_5y_unavailable_reason"),
            row.get("sps_growth_trend_5y_unavailable_reason"),
            row.get("book_value_growth_unavailable_reason"),
            row.get("net_income_growth_yoy_unavailable_reason"),
            row.get("operating_income_growth_yoy_unavailable_reason"),
            row.get("gross_margin_trend_unavailable_reason"),
            row.get("operating_margin_trend_unavailable_reason"),
            row.get("net_margin_trend_unavailable_reason"),
            row.get("roe_trend_unavailable_reason"),
            row.get("sustainable_growth_rate_unavailable_reason"),
            row.get("quarterly_growth_momentum_unavailable_reason"),
            row.get("fcf_growth_yoy_unavailable_reason"),
            row.get("ocf_growth_yoy_unavailable_reason"),
            row.get("asset_growth_yoy_unavailable_reason"),
            row.get("consecutive_positive_quarters_unavailable_reason"),
            row.get("earnings_growth_4q_avg_unavailable_reason"),
            row.get("eps_growth_stability_unavailable_reason"),
            row.get("earnings_surprise_avg_unavailable_reason"),
            row.get("earnings_beat_rate_unavailable_reason"),
            row.get("forward_eps_growth_current_fy_unavailable_reason"),
            row.get("forward_eps_growth_next_fy_unavailable_reason"),
            row.get("forward_revenue_growth_next_fy_unavailable_reason"),
            row.get("eps_estimate_revision_90d_pct_unavailable_reason"),
        ),
    )
