#!/usr/bin/env python3
"""
Backtest: Composite Score + Buy/Sell Signals Strategy

Simulates the live algo strategy historically:
  - Entry trigger: BUY signal in buy_sell_daily (pivot breakout above swing high with SMA50 filter)
  - Ranking: signal_quality_score (contemporaneous, from buy_sell_daily) - this INTENTIONALLY
    NO LONGER matches live Phase 7's ranking as of 2026-08-27 (see below for why).
  - Entry fill assumption: FIXED 2026-08-27 (real-money-readiness review) - entries now fill at
    the NEXT trading day's close after the signal fired, not the signal day's own close. Live-DB
    evidence (n=104 closed local trades) showed real Phase 8 entries land anywhere from the SAME
    calendar day (50/116) to 1 day later (62/116, the modal case) to 3 days later (4/116)
    relative to signal_date - never simulated at all under the old same-day-close assumption.
    This backtest now uses the single MODAL case (1 trading day of lag) as a materially more
    realistic default than zero lag; it is still an approximation (a full lag-distribution model
    would need real fill-timestamp data this local environment doesn't have) but a
    directionally-correct one, since a working breakout keeps running while the real pipeline
    catches up to it, so any positive lag pushes entries worse on average, not better. Of the 36
    live trades matchable back to their triggering buy_sell_daily.buylevel, entries averaged
    +0.75% (median +0.55%) ABOVE that breakout trigger price, worse than the trigger level on
    72% of them - the flat DEFAULT_SLIPPAGE_BPS haircut alone did not capture this; the lag
    itself needed to be simulated, not just a bigger flat haircut. See `run_backtest()`'s own
    docstring for the exact mechanism (`prev_signal_date`/`fill_prices`).

Live Phase 7 ranking history: originally composite_score, Session 377 switched it to
signal_quality_score (SQS) on a short-term-predictive-power hypothesis, a 2026-08-26 empirical
check of live signals found the opposite (near-zero/inverse correlation with forward returns -
see signal_quality_score_pooled_check_no_predictive_power_found_20260825 in memory), and live
Phase 7 was switched BACK to composite_score-primary ranking 2026-08-27 (real-money-readiness
review; see phase7_signal_generation.py's module docstring for the full history/evidence).

This backtest script's DEFAULT ranking (signal_quality_score) deliberately was NOT switched to
match live Phase 7 when the "the mechanism differs" gap was first found - it can't be, without
introducing worse look-ahead bias than the SQS-vs-composite_score question it would be trying
to answer. `stock_scores` has no historical date dimension (current snapshot only) -
composite_score sourced from it is always TODAY's value regardless of the historical
signal_date being simulated, so ranking backtest history by IT SPECIFICALLY would use future
information a live run on that historical date never had. signal_quality_score IS
contemporaneous (stored per-date on buy_sell_daily), which is why it remained this script's
DEFAULT ranking key even after live Phase 7 stopped using it that way.
2026-08-26: signal_quality_score itself has since been empirically checked against real live
outcomes and found to show no robust predictive power (see
signal_quality_score_pooled_check_no_predictive_power_found_20260825 in memory / a
pooled correlation ~0, non-monotonic quintiles) - meaning this backtest's DEFAULT-mode
historical Sharpe numbers are generated by ranking on a score shown not to work live, so they
should NOT be treated as confirmation that live Phase 7's CURRENT (composite_score-based)
ranking works either.

FIXED 2026-09-04 (real-money-readiness review, financial-calculation-integrity audit): the gap
above is now closed at the code level. `stock_scores_history` (migration 1221, point-in-time
composite_score by symbol+date) exists specifically for this - pass `--rank-by
composite_score_pit` (or `rank_by="composite_score_pit"` to `run_backtest()`) to rank same-day
BUY signals by a genuinely point-in-time composite_score, asof-joined by (symbol,
score_date<=signal_date) in `_get_daily_buy_signals()`, rather than `stock_scores`'s always-
current snapshot. This actually tests live Phase 7's real ranking mechanism
(composite_score-primary since 2026-08-27) without look-ahead bias. CAVEAT, still real: as of
2026-09-04 `stock_scores_history` only has snapshots from 2026-08-24 onward (~11 distinct
dates) - a run in this mode today is not yet statistically meaningful, same underlying
data-shallowness this repo's 2026-08-25 regime-adaptive-exits finding hit for a different
table (see tests/unit/test_regime_adaptive_exits_backtest_infeasible_20260825.py). The wiring
is correct and ready; don't treat an early `composite_score_pit` run's Sharpe/win-rate as
real evidence until the table has genuine depth (a year+ of daily snapshots, ideally spanning
more than one regime). The default ranking stays `signal_quality_score` until then, so existing
callers/results are unaffected by this change. Momentum sub-score is price-based (1m/3m/6m/12m)
so recency bias is expected for stocks that gained since signal date, in either ranking mode.

Usage:
    python -m algo.backtest.run_backtest [options]

    --start-date DATE    Start date for backtest (default: 2 years ago)
    --end-date DATE      End date (default: today)
    --initial-capital N  Starting capital in dollars (default: 100000)
    --max-positions N    Max concurrent positions (default: 10)
    --min-composite N    Min composite_score to qualify (default: 50)
    --profit-target PCT  Profit target % (default: 20)
    --stop-loss PCT      Stop loss % (default: 8)
    --max-hold-days N    Max holding period in days (default: 60)
    --position-size PCT  Fixed position size as % of portfolio (default: 10)
    --strategy NAME      Strategy name for results table (default: composite_score_signals)
    --slippage-bps BPS   Per-side slippage/spread haircut in basis points (default: 5.0)
    --dry-run            Print results without writing to DB
"""

import argparse
import logging
import statistics
import sys
from datetime import date, timedelta
from typing import Any

import psycopg2

from algo.infrastructure.market_calendar import MarketCalendar
from utils.db.context import DatabaseContext
from utils.metrics_calculator import MetricsCalculator

logger = logging.getLogger(__name__)

# Conservative, standard per-side transaction-cost haircut applied to every fill (2026-08-25,
# closing the "zero slippage/spread on every fill" gap documented in run_backtest()'s docstring).
# 5 bps/side is a common, well-precedented default for liquid US large/mid-cap equities in
# practitioner and academic backtesting when real broker-level slippage data isn't available -
# NOT derived from this system's own execution history (algo_tca has 0 local rows to calibrate
# against, see the docstring below). This exists to avoid the opposite, worse error - reporting
# backtest performance as if every fill were free - not to claim precision this system doesn't
# have. Replace with a real distribution drawn from `algo_tca.slippage_bps` once that table has
# live rows; until then this is an explicit, visible estimate, not silent zero-cost execution.
DEFAULT_SLIPPAGE_BPS = 5.0


def _fetch_risk_free_rate_annual() -> float:
    """Real 3-month T-bill rate (FRED DGS3MO), decimal annual - same source/convention as
    algo/reporting/performance.py's rolling_sharpe(). Added 2026-08-25 (goal: closing the
    "run_backtest.py duplicates the pre-fix raw-return Sharpe formula" gap found auditing
    the just-fixed calculate_sharpe_ratio() risk-free-rate bug - this script independently
    reimplemented the same formula inline instead of calling MetricsCalculator, so it carried
    the identical rf=0 assumption. Falls back to 0.0 (old behavior) if DGS3MO is unavailable,
    same non-fatal-degradation choice as rolling_sharpe().
    """
    try:
        with DatabaseContext("read") as cur:
            cur.execute(
                "SELECT value::float FROM economic_data WHERE series_id = 'DGS3MO' "
                "AND date <= CURRENT_DATE AND value IS NOT NULL ORDER BY date DESC LIMIT 1"
            )
            row = cur.fetchone()
            if row is not None and row[0] is not None:
                return float(row[0]) / 100.0
    except (psycopg2.DatabaseError, psycopg2.OperationalError) as e:
        logger.warning(f"[BACKTEST] DGS3MO risk-free rate lookup failed ({e}) - using 0.0")
    else:
        logger.warning("[BACKTEST] DGS3MO risk-free rate unavailable - using 0.0")
    return 0.0


def _get_trading_dates(start: date, end: date) -> list[date]:
    try:
        with DatabaseContext("read") as cur:
            cur.execute(
                """
                SELECT DISTINCT date FROM price_daily
                WHERE date >= %s AND date <= %s
                ORDER BY date ASC
                """,
                (start, end),
            )
            return [row[0] for row in cur.fetchall()]
    except (psycopg2.DatabaseError, psycopg2.OperationalError) as e:
        raise RuntimeError(f"[BACKTEST] FATAL: Cannot fetch trading dates from price_daily: {e}") from e


def _get_daily_buy_signals(
    signal_date: date, min_composite: float, rank_by: str = "signal_quality_score"
) -> list[dict[str, Any]]:
    """Get BUY signals detected on signal_date, ranked by `rank_by`.

    rank_by="signal_quality_score" (default, unchanged behavior): ranks by
    signal_quality_score (contemporaneous - no look-ahead bias). composite_score is also
    fetched from `stock_scores` for informational use only, NOT filtered/ranked by it, since
    that table has no date dimension (always TODAY's value, would be look-ahead bias against
    a historical signal_date). min_composite is accepted for API compatibility but unused in
    this mode.

    rank_by="composite_score_pit" (added 2026-09-04, real-money-readiness review, closing the
    gap this module's docstring flagged since 2026-08-26): ranks by composite_score sourced
    from `stock_scores_history` (migration 1221), joined point-in-time - the most recent
    `score_date <= signal_date` per symbol, mirroring the asof-join pattern already used by
    `algo/risk/market_exposure.py`'s `read_market_regime()`. This is genuinely contemporaneous
    (never a future score) and lets this backtest actually test live Phase 7's real ranking
    mechanism (composite_score-primary since 2026-08-27) without reintroducing look-ahead bias.
    min_composite IS applied as a real filter in this mode (rows with no score on-or-before
    signal_date, or below the threshold, are excluded) - unlike the default mode, since a
    genuinely point-in-time composite_score makes that threshold meaningful here.
    CAVEAT: as of 2026-09-04, stock_scores_history only has snapshots from 2026-08-24 onward
    (~11 distinct dates) - a backtest run in this mode over that short a window is not
    statistically meaningful yet (same underlying data-shallowness documented in
    tests/unit/test_regime_adaptive_exits_backtest_infeasible_20260825.py for a different
    table). The wiring is correct and ready for when the table has real depth; don't treat an
    early run's Sharpe/win-rate as evidence either way until it does.

    NOTE: the "entry_price" field returned here (signal_date's own close) is INFORMATIONAL
    ONLY as of 2026-08-27 - run_backtest()'s main loop no longer uses it directly for sizing/
    cost basis. It fetches signals one trading day BEHIND its current sim_date and re-resolves
    the actual fill price via a fresh _get_prices_batch() call on sim_date itself, to model the
    real one-day (modal) lag between signal detection and live Phase 8 execution. See the
    module docstring's "Entry fill assumption" note.
    """
    if rank_by not in ("signal_quality_score", "composite_score_pit"):
        raise ValueError(
            f"[BACKTEST] Invalid rank_by={rank_by!r}. Must be 'signal_quality_score' or 'composite_score_pit'."
        )
    try:
        with DatabaseContext("read") as cur:
            if rank_by == "composite_score_pit":
                cur.execute(
                    """
                    SELECT b.symbol, b.close, b.high, b.low, b.sma_50, b.strength,
                           b.buylevel, b.stoplevel,
                           b.signal_quality_score, b.entry_quality_score,
                           s.composite_score, s.rs_percentile
                    FROM buy_sell_daily b
                    LEFT JOIN LATERAL (
                        SELECT composite_score, rs_percentile
                        FROM stock_scores_history sh
                        WHERE sh.symbol = b.symbol AND sh.score_date <= %s
                        ORDER BY sh.score_date DESC
                        LIMIT 1
                    ) s ON TRUE
                    WHERE b.date = %s
                      AND b.signal_type = 'BUY'
                      AND b.close IS NOT NULL
                      AND b.sma_50 IS NOT NULL
                      AND b.close > b.sma_50
                      AND b.signal_quality_score IS NOT NULL
                      AND s.composite_score IS NOT NULL
                      AND s.composite_score >= %s
                    ORDER BY s.composite_score DESC
                    """,
                    (signal_date, signal_date, min_composite),
                )
            else:
                cur.execute(
                    """
                    SELECT b.symbol, b.close, b.high, b.low, b.sma_50, b.strength,
                           b.buylevel, b.stoplevel,
                           b.signal_quality_score, b.entry_quality_score,
                           s.composite_score, s.rs_percentile
                    FROM buy_sell_daily b
                    LEFT JOIN stock_scores s ON s.symbol = b.symbol
                    WHERE b.date = %s
                      AND b.signal_type = 'BUY'
                      AND b.close IS NOT NULL
                      AND b.sma_50 IS NOT NULL
                      AND b.close > b.sma_50
                      AND b.signal_quality_score IS NOT NULL
                    ORDER BY b.signal_quality_score DESC
                    """,
                    (signal_date,),
                )
            rows = cur.fetchall()

        signals = []
        skipped_count = 0
        for r in rows:
            close = float(r[1])
            if not close:
                logger.warning(
                    f"[BACKTEST] Skipping {r[0]} on {signal_date}: close price is {close} "
                    f"(falsy value detected during signal processing)"
                )
                skipped_count += 1
                continue
            if r[5] is None:
                raise ValueError(
                    f"Signal strength missing for {r[0]} on {signal_date} - "
                    f"cannot rank signal quality without strength data"
                )
            signals.append(
                {
                    "symbol": r[0],
                    "entry_price": close,
                    "high": float(r[2]) if r[2] is not None else None,
                    "low": float(r[3]) if r[3] is not None else None,
                    "sma_50": float(r[4]) if r[4] is not None else None,
                    "signal_strength": float(r[5]),
                    "buylevel": float(r[6]) if r[6] is not None else None,
                    "stoplevel": float(r[7]) if r[7] is not None else None,
                    "signal_quality_score": float(r[8]),
                    "entry_quality_score": float(r[9]) if r[9] is not None else None,
                    "composite_score": float(r[10]) if r[10] is not None else None,
                    "rs_percentile": float(r[11]) if r[11] is not None else None,
                }
            )

        return signals
    except (ValueError, ZeroDivisionError, TypeError) as e:
        raise RuntimeError(f"[BACKTEST] FATAL: Cannot fetch buy signals for {signal_date}: {e}") from e


def _get_daily_sell_signals(signal_date: date) -> set[str]:
    try:
        with DatabaseContext("read") as cur:
            cur.execute(
                "SELECT symbol FROM buy_sell_daily WHERE date = %s AND signal_type = 'SELL'",
                (signal_date,),
            )
            return {row[0] for row in cur.fetchall()}
    except (psycopg2.DatabaseError, psycopg2.OperationalError) as e:
        raise RuntimeError(f"[BACKTEST] FATAL: Cannot fetch sell signals for {signal_date}: {e}") from e


def _get_price_on_date(symbol: str, target_date: date) -> float | None:
    try:
        with DatabaseContext("read") as cur:
            cur.execute(
                "SELECT close FROM price_daily WHERE symbol = %s AND date <= %s ORDER BY date DESC LIMIT 1",
                (symbol, target_date),
            )
            row = cur.fetchone()
            return float(row[0]) if row and row[0] is not None else None
    except (ValueError, ZeroDivisionError, TypeError) as e:
        raise RuntimeError(f"Operation failed: {e}") from e


def _get_prices_batch(symbols: list[str], target_date: date) -> dict[str, float]:
    if not symbols:
        raise ValueError("symbols list cannot be empty for backtest price fetch")
    try:
        with DatabaseContext("read") as cur:
            cur.execute(
                """
                SELECT DISTINCT ON (symbol) symbol, close
                FROM price_daily
                WHERE symbol = ANY(%s) AND date <= %s
                ORDER BY symbol, date DESC
                """,
                (symbols, target_date),
            )
            return {r[0]: float(r[1]) for r in cur.fetchall() if r[1] is not None}
    except (psycopg2.DatabaseError, psycopg2.OperationalError) as e:
        raise RuntimeError(f"[BACKTEST] FATAL: Cannot fetch prices for symbols: {e}") from e


def _get_avg_dollar_volume_batch(symbols: list[str], as_of_date: date) -> dict[str, float]:
    """20-trading-day trailing average dollar volume (volume * close) as of as_of_date,
    batched across symbols - same windowing/methodology as position_sizer.py's live
    max_pct_of_adv_dollars check (20 most recent rows strictly before as_of_date), for the
    optional participation-rate cap in run_backtest() below.

    REAL-MONEY-READINESS FINDING (2026-09-06 audit): live position_sizer.py enforces this
    cap but the backtest never modeled it at all, so a backtest could simulate a position
    size live trading would never actually be allowed to take on a thin name - overstating
    achievable backtested returns for that subset of trades. Opt-in (max_pct_of_adv_dollars
    param, default None) matching every other backstop's introduction pattern in this
    codebase, so existing callers/tests see zero behavior change unless they explicitly ask
    for ADV-capped parity.

    A symbol absent from the result has no resolvable 20-day window (new listing, data gap)
    - the caller must treat that as "cannot check, don't cap" rather than a rejection, same
    fail-open convention as position_sizer.py's own missing-ADV-reading handling.
    """
    if not symbols:
        raise ValueError("symbols list cannot be empty for backtest avg dollar volume fetch")
    try:
        with DatabaseContext("read") as cur:
            cur.execute(
                """
                SELECT symbol, AVG(volume * close) AS avg_dollar_vol
                FROM (
                    SELECT symbol, volume, close,
                           ROW_NUMBER() OVER (PARTITION BY symbol ORDER BY date DESC) AS rn
                    FROM price_daily
                    WHERE symbol = ANY(%s) AND date < %s
                ) recent
                WHERE rn <= 20
                GROUP BY symbol
                """,
                (symbols, as_of_date),
            )
            return {r[0]: float(r[1]) for r in cur.fetchall() if r[1] is not None}
    except (psycopg2.DatabaseError, psycopg2.OperationalError) as e:
        raise RuntimeError(f"[BACKTEST] FATAL: Cannot fetch avg dollar volume for symbols: {e}") from e


def run_backtest(  # noqa: C901
    start_date: date,
    end_date: date,
    initial_capital: float = 100_000.0,
    max_positions: int = 10,
    min_composite: float = 50.0,
    profit_target_pct: float = 20.0,
    stop_loss_pct: float = 8.0,
    max_hold_days: int = 60,
    position_size_pct: float = 10.0,
    strategy_name: str = "composite_score_signals",
    slippage_bps: float = DEFAULT_SLIPPAGE_BPS,
    rank_by: str = "signal_quality_score",
    base_risk_pct: float | None = None,
    max_pct_of_adv_dollars: float | None = None,
) -> dict[str, Any]:
    """Run backtest and return results dict.

    SIZING MODEL - fixed-fraction-of-portfolio vs. risk-based (real-money-readiness audit,
    2026-09-05): by default (base_risk_pct=None), every entry is sized as a flat
    `position_size_pct` of current total_value regardless of stop distance - this is NOT what
    live position_sizer.py does (risk_dollars = portfolio_value * base_risk_pct, shares =
    risk_dollars / (entry - stop)), and the two can diverge by several-fold on any trade whose
    stop distance differs meaningfully from the "implied" distance the flat fraction happens to
    assume. Live also applies several further multipliers this backtest does NOT simulate at
    all (drawdown-tier reduction, market-exposure regime, VIX-caution, per-symbol data-maturity
    discount) - even with base_risk_pct set, this remains an approximation of live sizing, not
    full parity; treat a Sharpe/return comparison between the two modes as directionally
    informative about the sizing-model divergence's exact magnitude, not as proof either mode's
    absolute performance figures are what a live account would have realized.

    Passing base_risk_pct (e.g. 0.75, matching live's AlgoConfig default) switches to
    risk-based sizing: shares = floor((total_value * base_risk_pct / 100) / risk_per_share),
    where risk_per_share = entry_price - (entry_price * (1 - stop_loss_pct/100)) - the same
    stop distance this backtest already uses for its own stop-loss exit, so the risk-per-share
    denominator is internally consistent with what actually triggers an exit here.
    position_size_pct still applies as the maximum position size cap either way (mirroring
    live's max_position_size_pct role) - risk-based sizing can only shrink a position relative
    to that cap, never grow it past the cap.

    KNOWN SIMPLIFICATION - no intraday data: _get_prices_batch() only fetches `close` from
    price_daily, so a stop-loss or profit-target exit is priced as if filled at exactly the
    theoretical stop/target level (entry_price * (1 +/- pct/100)), never at a worse price on a
    day the close gapped through that level (e.g. an overnight gap-down past the stop). Real
    stop-loss orders are typically stop-market, which fill at the actual (worse) price on a
    gap-through day, not the trigger price - so this systematically slightly overstates
    backtested performance during volatile/gapping periods relative to live execution. This is
    an inherent limitation of daily-bar-only backtesting (no code fix possible without loading
    intraday price data), not a calculation bug - noted here so backtest results aren't read as
    more precise than the underlying data supports.

    SLIPPAGE MODELING (fixed 2026-08-25, goal session - this previously modeled every fill as
    perfectly costless): every entry and exit fill now applies `slippage_bps` (default
    `DEFAULT_SLIPPAGE_BPS` = 5 bps/side, see its own module-level comment) against the bar
    `close`/theoretical stop-target level the fill would otherwise use unadjusted - buys pay
    `price * (1 + slippage_bps/10000)`, sells receive `price * (1 - slippage_bps/10000)`, so
    performance is never overstated by assuming free execution. This is a standard conservative
    default, NOT calibrated to this system's own execution history - `algo_tca` (populated by
    `algo/trading/tca.py`) tracks real `slippage_bps` per live trade for exactly this purpose,
    but has 0 rows in this local dev DB (no live trading history here) to draw a real
    distribution from yet. Live entries go through `order_manager.py`'s LIMIT orders and live
    exits mix LIMIT and MARKET orders (see [[exit_order_marketable_limit_20260824]] in memory) -
    this flat per-side haircut is a reasonable approximation of both, not an exact model of
    either. Replace `slippage_bps` with a value (or, better, a random draw) derived from
    `algo_tca.slippage_bps` once that table has live rows - flagged as a candidate contributor
    to the live-vs-backtest Sharpe divergence documented in
    [[trailing_year_sharpe_negative_real_but_undiagnosable_locally_20260822]] (that
    investigation could not identify a root cause locally; zero-slippage backtesting was a
    concrete candidate it did not consider).

    KNOWN SIMPLIFICATION - no intraday data (unchanged, see the module's `_get_prices_batch()`
    docstring): a stop-loss or profit-target exit is still priced at the theoretical
    `entry_price * (1 +/- pct/100)` level (now slippage-adjusted), not at a worse price on a day
    the close gapped through that level - no code fix possible without intraday price data.

    ENTRY LAG MODELING (fixed 2026-08-27, real-money-readiness review - this previously entered
    at the exact signal day's own close, zero lag): each sim_date's entry candidates are now
    BUY signals from the PRECEDING trading day (`prev_sim_date`), filled at `sim_date`'s own
    close (fetched fresh via `_get_prices_batch`, not `_get_daily_buy_signals`'s own `close`
    field, which is now informational only). This models the modal real-world lag between a
    signal firing and live Phase 8 actually executing it (see module docstring). Still a
    simplification - real entries land anywhere from same-day to 3+ days out - but strictly
    more realistic than assuming the fill happens the instant the breakout is detected.

    EXIT LAG MODELING (fixed 2026-09-06): the symmetric look at exit lag flagged here as a
    future check was done. SELL-signal exits had the identical zero-lag bug (exiting at the
    exact signal day's own close) - now fixed the same way as entries: yesterday's SELL
    signal, filled at today's price. Price-triggered exits (profit target/stop loss/max
    hold) are unaffected by design - those are level-based and continuously monitored in
    live exit_engine.py, not gated on the once-daily signal batch the way BUY/SELL signals
    are, so same-day detection-and-action remains correct for them.

    PARTICIPATION-RATE CAP (added 2026-09-06, real-money-readiness audit): live
    position_sizer.py's optional max_pct_of_adv_dollars cap (a candidate position can't
    exceed N% of the symbol's own 20-day average dollar volume) was never modeled here at
    all - a backtest could simulate a position size live trading would never actually be
    allowed to take on a thin name, overstating achievable backtested returns for that
    subset of trades. Opt-in (default None, matching every other backstop's introduction
    pattern in this codebase) - pass the same value configured live (algo_config's
    max_pct_of_adv_dollars, 5.0 by default as of this fix) for realistic parity. Uses the
    identical 20-trading-day trailing window/methodology as the live check
    (_get_avg_dollar_volume_batch mirrors position_sizer.py's own query). A symbol with no
    resolvable 20-day window (new listing, data gap) is not capped - fails open, same
    convention as the live check's own missing-ADV-reading handling.
    """
    # CRITICAL: Validate initial capital is positive (required for all P&L calculations)
    if initial_capital is None or initial_capital <= 0:
        raise ValueError(
            f"[BACKTEST] Invalid initial_capital={initial_capital}. "
            f"Must be positive number (in USD). All P&L metrics depend on valid starting capital."
        )

    logger.info(
        f"[BACKTEST] Starting {strategy_name}: {start_date} to {end_date}, "
        f"capital=${initial_capital:,.0f}, max_pos={max_positions}, "
        f"min_composite={min_composite}, stop={stop_loss_pct}%, target={profit_target_pct}%"
    )

    trading_dates = _get_trading_dates(start_date, end_date)
    if not trading_dates:
        raise RuntimeError(
            f"[BACKTEST] FATAL: No trading dates found in price_daily between {start_date} and {end_date}"
        )

    logger.info(f"[BACKTEST] {len(trading_dates)} trading days to simulate")

    capital = initial_capital
    positions: dict[str, dict[str, Any]] = {}  # symbol -> {entry_price, shares, entry_date, stop, target}
    completed_trades: list[dict[str, Any]] = []
    equity_curve = []

    # ENTRY LAG MODELING (see run_backtest()'s own docstring): prev_sim_date tracks the
    # PRECEDING trading day so entries can be sourced from that day's signals and filled at
    # today's price - a 1-trading-day lag, not the signal day's own close.
    prev_sim_date: date | None = None

    for sim_date in trading_dates:
        # Mark-to-market: update portfolio value at day open
        position_symbols = list(positions.keys())
        current_prices = _get_prices_batch(position_symbols, sim_date) if position_symbols else {}

        # Validate all position prices are available (fail-fast if data missing)
        for symbol in position_symbols:
            if symbol not in current_prices:
                raise RuntimeError(
                    f"[BACKTEST] FATAL: Missing price for position {symbol} on {sim_date}. "
                    f"Cannot calculate P&L without current prices. Check price_daily table."
                )

        # EXIT LAG MODELING (fixed 2026-09-06, real-money-readiness dig - this previously
        # exited on the exact signal day's own close, zero lag, the SAME bug class the
        # 2026-08-27 entry-lag fix addressed for BUY signals - see this function's own
        # docstring, which explicitly flagged this asymmetry as never having been checked).
        # SELL signals come from the same once-daily buy_sell_daily batch as BUY signals and
        # have the same real-world lag before live Phase 8/6 execution can react to them -
        # checking YESTERDAY's sell signal and exiting at TODAY's price is symmetric with the
        # entry-lag model below. Price-triggered exits (profit target/stop loss/max hold) are
        # deliberately NOT lagged here - those are level-based and continuously monitored in
        # live exit_engine.py, not gated on the once-daily signal batch the way BUY/SELL
        # signals are, so same-day detection-and-action remains correct for them.
        sell_signals = _get_daily_sell_signals(prev_sim_date) if prev_sim_date is not None else set()

        for symbol in list(positions.keys()):
            pos = positions[symbol]
            current_price = current_prices[symbol]
            # Trading-day-aware (not calendar days) to match the live max_hold_days semantics
            # in algo/trading/exit_engine.py - a naive calendar diff would let a weekend
            # inflate hold_days and trigger max_hold earlier here than live actually would.
            hold_days = MarketCalendar.trading_days_elapsed(pos["entry_date"], sim_date)

            if pos["entry_price"] <= 0:
                raise ValueError(f"Invalid entry price for {symbol}: {pos['entry_price']} <= 0. Cannot calculate P&L.")

            pnl_pct = (current_price - pos["entry_price"]) / pos["entry_price"] * 100

            exit_reason = None
            exit_price = current_price

            if symbol in sell_signals:
                exit_reason = "sell_signal"
            elif pnl_pct >= profit_target_pct:
                exit_reason = "profit_target"
                exit_price = pos["entry_price"] * (1 + profit_target_pct / 100)
            elif pnl_pct <= -stop_loss_pct:
                exit_reason = "stop_loss"
                exit_price = pos["entry_price"] * (1 - stop_loss_pct / 100)
            elif hold_days >= max_hold_days:
                exit_reason = "max_hold"

            if exit_reason:
                # Every exit is a sell - apply the same slippage haircut regardless of which
                # branch above set exit_price (see DEFAULT_SLIPPAGE_BPS/docstring).
                exit_price = exit_price * (1 - slippage_bps / 10_000)
                pnl_dollars = (exit_price - pos["entry_price"]) * pos["shares"]
                pnl_pct_final = (exit_price - pos["entry_price"]) / pos["entry_price"] * 100
                capital += pos["shares"] * exit_price  # return capital

                completed_trades.append(
                    {
                        "symbol": symbol,
                        "trade_date": pos["entry_date"],
                        "entry_price": pos["entry_price"],
                        "entry_quantity": int(pos["shares"]),
                        "exit_date": sim_date,
                        "exit_price": round(exit_price, 4),
                        "profit_loss_dollars": round(pnl_dollars, 2),
                        "profit_loss_pct": round(pnl_pct_final, 4),
                        "holding_days": hold_days,
                        "exit_reason": exit_reason,
                        "signal_quality_score": pos.get("signal_quality_score"),
                        "composite_score": pos.get("composite_score"),
                    }
                )

                logger.debug(f"[BACKTEST] EXIT {symbol}: {exit_reason} P&L={pnl_pct_final:+.1f}% ({hold_days}d)")
                del positions[symbol]

        # Record equity curve snapshot (all position prices already validated above)
        invested_value = sum(current_prices[sym] * pos["shares"] for sym, pos in positions.items())
        total_value = capital + invested_value
        equity_curve.append({"date": sim_date.isoformat(), "value": round(total_value, 2)})

        # Check entries: BUY signals from the PRECEDING trading day, filled at TODAY's price
        # (1-trading-day entry lag - see run_backtest()'s own docstring "ENTRY LAG MODELING").
        # No prev_sim_date on the very first simulated day - nothing to enter on, correctly
        # skipped rather than fabricating a lag-free entry for day 1 only.
        if len(positions) < max_positions and capital > 0 and prev_sim_date is not None:
            buy_signals = _get_daily_buy_signals(prev_sim_date, min_composite, rank_by=rank_by)
            candidate_symbols = [s["symbol"] for s in buy_signals if s["symbol"] not in positions]
            fill_prices = _get_prices_batch(candidate_symbols, sim_date) if candidate_symbols else {}
            adv_by_symbol = (
                _get_avg_dollar_volume_batch(candidate_symbols, sim_date)
                if candidate_symbols and max_pct_of_adv_dollars is not None
                else {}
            )

            for sig in buy_signals:
                symbol = sig["symbol"]
                if symbol in positions:
                    continue  # Already in position
                if len(positions) >= max_positions:
                    break

                # Yesterday's signal, filled at TODAY's price - NOT sig["entry_price"] (that
                # field is yesterday's own close, informational only as of 2026-08-27's entry-
                # lag fix, see _get_daily_buy_signals()'s docstring). A symbol missing from
                # today's prices (e.g. delisted/halted overnight) is skipped, not fatal - that's
                # a real, if rare, live possibility too, unlike a corrupt signal row.
                entry_price = fill_prices.get(symbol)
                if entry_price is None or entry_price <= 0:
                    logger.warning(
                        f"[BACKTEST] Skipping entry for {symbol}: no valid price on {sim_date} "
                        f"(signal was from {prev_sim_date})"
                    )
                    continue
                # Buys pay the slippage haircut too (see DEFAULT_SLIPPAGE_BPS/docstring) - sized
                # and costed against the actual fill price, not the pre-slippage signal price.
                entry_price = entry_price * (1 + slippage_bps / 10_000)
                # position_size_pct is always the CAP - see run_backtest's own "SIZING MODEL"
                # docstring section. Risk-based sizing (base_risk_pct set) can only shrink the
                # position relative to this cap, matching live position_sizer.py's own
                # cap-then-clamp ordering, never grow past it.
                cap_dollars = min(capital, total_value * position_size_pct / 100)
                if base_risk_pct is not None:
                    risk_per_share = entry_price * (stop_loss_pct / 100)
                    risk_dollars = total_value * base_risk_pct / 100
                    risk_based_dollars = (risk_dollars / risk_per_share) * entry_price if risk_per_share > 0 else 0
                    position_dollars = min(cap_dollars, risk_based_dollars)
                else:
                    position_dollars = cap_dollars

                # PARTICIPATION-RATE CAP (see run_backtest()'s own docstring) - applied after
                # every other cap, same as position_sizer.py's own cap-then-clamp ordering,
                # so it can only shrink the position further, never grow it past the caps
                # above. A symbol with no resolvable ADV reading is not capped (fails open).
                if max_pct_of_adv_dollars is not None:
                    avg_dollar_vol = adv_by_symbol.get(symbol)
                    if avg_dollar_vol is not None:
                        max_adv_dollars = avg_dollar_vol * max_pct_of_adv_dollars / 100
                        position_dollars = min(position_dollars, max_adv_dollars)

                shares = int(position_dollars / entry_price)

                if shares < 1:
                    logger.warning(
                        f"[BACKTEST] Rejected entry for {symbol}: shares < 1 "
                        f"(position_dollars=${position_dollars:.2f}, entry_price=${entry_price:.2f})"
                    )
                    continue

                shares = int(shares)
                cost = shares * entry_price

                if cost > capital:
                    logger.warning(
                        f"[BACKTEST] Rejected entry for {symbol}: insufficient_capital "
                        f"(cost=${cost:.2f}, capital=${capital:.2f})"
                    )
                    continue

                capital -= cost
                positions[symbol] = {
                    "entry_price": entry_price,
                    "shares": shares,
                    "entry_date": sim_date,
                    "signal_quality_score": sig.get("signal_quality_score"),
                    "composite_score": sig.get("composite_score"),
                }

                sq = sig.get("signal_quality_score")
                sq_str = f"{sq:.1f}" if sq is not None else "?"
                logger.debug(f"[BACKTEST] ENTER {symbol}: ${entry_price:.2f} x {shares} shares signal_quality={sq_str}")

        prev_sim_date = sim_date

    # Close any remaining open positions at last date's price
    if positions:
        final_date = trading_dates[-1]
        final_prices = _get_prices_batch(list(positions.keys()), final_date)
        # Validate all position prices are available for final close (fail-fast if data missing)
        for symbol in positions.keys():
            if symbol not in final_prices:
                raise RuntimeError(
                    f"[BACKTEST] FATAL: Missing final price for position {symbol} on {final_date}. "
                    f"Cannot close out positions without current prices. Check price_daily table."
                )
        for symbol, pos in positions.items():
            # Forced end-of-backtest close is still a sell - same slippage haircut as any
            # other exit (see DEFAULT_SLIPPAGE_BPS/docstring).
            exit_price = final_prices[symbol] * (1 - slippage_bps / 10_000)
            pnl_dollars = (exit_price - pos["entry_price"]) * pos["shares"]
            pnl_pct_final = (exit_price - pos["entry_price"]) / pos["entry_price"] * 100
            hold_days = MarketCalendar.trading_days_elapsed(pos["entry_date"], final_date)
            capital += pos["shares"] * exit_price

            completed_trades.append(
                {
                    "symbol": symbol,
                    "trade_date": pos["entry_date"],
                    "entry_price": pos["entry_price"],
                    "entry_quantity": int(pos["shares"]),
                    "exit_date": final_date,
                    "exit_price": round(exit_price, 4),
                    "profit_loss_dollars": round(pnl_dollars, 2),
                    "profit_loss_pct": round(pnl_pct_final, 4),
                    "holding_days": hold_days,
                    "exit_reason": "end_of_backtest",
                    "signal_quality_score": pos.get("signal_quality_score"),
                    "composite_score": pos.get("composite_score"),
                }
            )

    # Compute performance metrics
    final_capital = capital
    total_return_pct = (final_capital - initial_capital) / initial_capital * 100
    n_days = (end_date - start_date).days
    if n_days <= 0:
        raise ValueError("CRITICAL: Backtest date range invalid (end_date must be after start_date)")
    years = n_days / 365.25
    if years <= 0:
        raise ValueError("CRITICAL: Year calculation invalid for annualized return")
    annualized_return_pct = ((final_capital / initial_capital) ** (1.0 / years) - 1) * 100

    total_trades = len(completed_trades)
    winning_trades = [t for t in completed_trades if t["profit_loss_pct"] > 0]
    losing_trades = [t for t in completed_trades if t["profit_loss_pct"] <= 0]
    win_count = len(winning_trades)
    loss_count = len(losing_trades)
    win_rate_pct = (win_count / total_trades * 100) if total_trades > 0 else None
    best_trade = max(t["profit_loss_pct"] for t in completed_trades) if total_trades > 0 else None
    worst_trade = min(t["profit_loss_pct"] for t in completed_trades) if total_trades > 0 else None
    avg_hold = sum(t["holding_days"] for t in completed_trades) / total_trades if total_trades > 0 else None

    gross_profit = sum(t["profit_loss_dollars"] for t in winning_trades)
    gross_loss = abs(sum(t["profit_loss_dollars"] for t in losing_trades))
    if gross_loss <= 0:
        profit_factor = None
    else:
        profit_factor = gross_profit / gross_loss

    # Max drawdown from equity curve
    max_dd_pct: float | None = 0.0
    if equity_curve:
        peak = equity_curve[0]["value"]
        if peak <= 0:
            logger.warning(
                f"[BACKTEST] Equity curve starts at {peak} (non-positive). Cannot calculate meaningful drawdown."
            )
            max_dd_pct = None
        else:
            for point in equity_curve:
                v = point["value"]
                if v > peak:
                    peak = v
                # Only calculate drawdown when peak is positive (avoid division by zero)
                if peak > 0:
                    dd = (v - peak) / peak * 100
                    if dd < max_dd_pct:
                        max_dd_pct = dd

    # Sharpe/Sortino/Calmar from equity curve daily returns - routed through
    # MetricsCalculator (same canonical formulas rolling_sharpe()/sortino_ratio()/
    # calmar_ratio() in algo/reporting/performance.py use) instead of a second, inline
    # reimplementation. FIXED 2026-08-25 (goal): the inline formula this replaced was
    # `avg_ret / std_ret * sqrt(252)` - the exact same raw-return-not-excess-return bug
    # just fixed in calculate_sharpe_ratio() for live Sharpe (see that fix's commit
    # message) - this script had independently drifted the same formula and carried the
    # identical rf=0 assumption. It also never computed Sortino/Calmar at all, despite
    # algo/reporting/tests/backtest/reference_metrics.json (this script's own reference
    # baseline) claiming values for both - a mismatch that made that file's provenance
    # unverifiable (see backtest_vs_live_comparison()'s docstring note).
    sharpe = None
    sortino = None
    calmar = None
    if len(equity_curve) > 30:
        values = [p["value"] for p in equity_curve]
        # CRITICAL: Skip returns where prior value is <= 0 (cannot calculate meaningful returns)
        daily_returns = []
        for i in range(1, len(values)):
            if values[i - 1] > 0:
                daily_returns.append((values[i] - values[i - 1]) / values[i - 1])
            else:
                logger.warning(f"[BACKTEST] Skipped return at {i}: equity={values[i - 1]:.0f} is not positive")
        if daily_returns:
            if len(daily_returns) < 2:
                raise ValueError(
                    f"CRITICAL: Insufficient daily returns ({len(daily_returns)}) for Sharpe calculation (need 2+). "
                    f"Equity curve must have at least 3 snapshots (2+ returns)."
                )
            std_ret = statistics.stdev(daily_returns)
            if std_ret <= 0:
                raise ValueError(
                    "CRITICAL: Zero or negative volatility in returns (invalid backtest data). "
                    "Check for flat equity curve (no price changes) or corrupt data."
                )
            risk_free_rate_annual = _fetch_risk_free_rate_annual()
            sharpe = MetricsCalculator.calculate_sharpe_ratio(
                daily_returns, min_observations=2, risk_free_rate_annual=risk_free_rate_annual
            )
            try:
                sortino = MetricsCalculator.calculate_sortino_ratio(daily_returns, min_observations=2)
            except ValueError as e:
                logger.info(f"[BACKTEST] Sortino not computable ({e}) - no negative daily returns in this window")
            try:
                calmar = MetricsCalculator.calculate_calmar_ratio(values, min_observations=2)
            except ValueError as e:
                logger.info(f"[BACKTEST] Calmar not computable ({e})")

    avg_trade_return_pct = (
        (sum(t["profit_loss_pct"] for t in completed_trades) / total_trades) if total_trades > 0 else None
    )

    results = {
        "strategy_name": strategy_name,
        "start_date": start_date,
        "end_date": end_date,
        "initial_capital": initial_capital,
        "final_capital": round(final_capital, 2),
        "total_return_pct": round(total_return_pct, 4),
        "annualized_return_pct": round(annualized_return_pct, 4),
        "max_drawdown_pct": round(max_dd_pct, 4) if max_dd_pct is not None else None,
        "sharpe_ratio": sharpe,
        "sortino_ratio": sortino,
        "calmar_ratio": calmar,
        "win_rate_pct": round(win_rate_pct, 4) if win_rate_pct is not None else None,
        "profit_factor": (
            (round(profit_factor, 4) if profit_factor != float("inf") else 9999.0)
            if profit_factor is not None
            else None
        ),
        "total_trades": total_trades,
        "winning_trades": win_count,
        "losing_trades": loss_count,
        "avg_trade_return_pct": round(avg_trade_return_pct, 4) if avg_trade_return_pct is not None else None,
        "best_trade_pct": round(best_trade, 4) if best_trade is not None else None,
        "worst_trade_pct": round(worst_trade, 4) if worst_trade is not None else None,
        "avg_holding_days": round(avg_hold, 2) if avg_hold is not None else None,
        "parameters": {
            "min_composite_score": min_composite,
            "profit_target_pct": profit_target_pct,
            "stop_loss_pct": stop_loss_pct,
            "max_hold_days": max_hold_days,
            "max_positions": max_positions,
            "position_size_pct": position_size_pct,
            "base_risk_pct": base_risk_pct,
        },
        "trades": completed_trades,
        "equity_curve": equity_curve,
    }

    # win_rate_pct is None on a zero-trade run and max_dd_pct is None when the equity curve
    # starts non-positive - formatting either unconditionally with ":.1f" previously raised
    # TypeError here, crashing run_backtest() itself (before it could even return results)
    # on the exact zero-trade case a narrow/strict backtest window legitimately produces.
    win_rate_str = f"{win_rate_pct:.1f}%" if win_rate_pct is not None else "n/a"
    max_dd_str = f"{max_dd_pct:.1f}%" if max_dd_pct is not None else "n/a"
    logger.info(
        f"[BACKTEST] COMPLETE: {total_trades} trades, "
        f"return={total_return_pct:+.1f}% (annualized={annualized_return_pct:+.1f}%), "
        f"win_rate={win_rate_str}, sharpe={sharpe}, "
        f"max_dd={max_dd_str}"
    )

    return results


def save_results(results: dict[str, Any]) -> int | None:
    """Write backtest results to backtest_runs and backtest_trades tables.

    Returns run_id integer on success, None on failure.
    """
    if not results:
        logger.error("[BACKTEST] No results to save")
        return None

    trades = results.pop("trades", [])
    results.pop("equity_curve", [])

    run_name = f"{results['strategy_name']}_{results['start_date']}_{results['end_date']}"
    # Deduplicate by using ON CONFLICT on run_name+run_timestamp (via unique constraint)

    try:
        run_id = None
        with DatabaseContext("write") as cur:
            cur.execute(
                """
                INSERT INTO backtest_runs (
                    run_name, strategy_name, start_date, end_date,
                    initial_capital, final_value, total_return, annual_return,
                    max_drawdown, sharpe_ratio, win_rate, profit_factor,
                    num_trades, num_winning_trades, num_losing_trades,
                    avg_win, avg_loss, largest_win, largest_loss
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, %s, %s
                )
                RETURNING run_id
                """,
                (
                    run_name,
                    results["strategy_name"],
                    results["start_date"],
                    results["end_date"],
                    results["initial_capital"],
                    results["final_capital"],
                    results["total_return_pct"] / 100.0,  # store as fraction
                    results["annualized_return_pct"] / 100.0,
                    results["max_drawdown_pct"] / 100.0,
                    results["sharpe_ratio"],
                    results["win_rate_pct"] / 100.0,
                    results["profit_factor"],
                    results["total_trades"],
                    results["winning_trades"],
                    results["losing_trades"],
                    results["avg_trade_return_pct"],
                    results["worst_trade_pct"],  # avg_loss proxy
                    results["best_trade_pct"],
                    results["worst_trade_pct"],
                ),
            )
            row = cur.fetchone()
            if row is None or row[0] is None:
                raise RuntimeError("Backtest run insert failed: RETURNING run_id returned no row")
            run_id = int(row[0])

        # Write individual trades
        if trades and run_id:
            with DatabaseContext("write") as cur:
                for trade in trades:
                    entry_price = trade["entry_price"]
                    exit_price_raw = trade.get("exit_price")
                    if exit_price_raw is None:
                        raise RuntimeError(
                            f"Trade missing exit_price (symbol={trade.get('symbol')}, "
                            f"entry_date={trade.get('entry_date')}). "
                            "Backtest trades must always have explicit exit prices."
                        )
                    exit_price = exit_price_raw
                    qty = trade["entry_quantity"]
                    pnl_raw = trade.get("profit_loss_dollars")
                    if pnl_raw is None:
                        raise RuntimeError(
                            f"Trade missing profit_loss_dollars (symbol={trade.get('symbol')}, "
                            f"entry_date={trade.get('entry_date')}). "
                            "Backtest trades must always have explicit P&L calculations."
                        )
                    pnl = pnl_raw
                    pnl_pct_raw = trade.get("profit_loss_pct")
                    if pnl_pct_raw is None:
                        raise RuntimeError(
                            f"Trade missing profit_loss_pct (symbol={trade.get('symbol')}, "
                            f"entry_date={trade.get('entry_date')}). "
                            "Backtest trades must always have explicit P&L calculations."
                        )
                    pnl_pct = pnl_pct_raw
                    cur.execute(
                        """
                        INSERT INTO backtest_trades (
                            run_id, symbol, entry_date, exit_date,
                            entry_price, exit_price, quantity,
                            entry_value, exit_value,
                            profit_loss, profit_loss_percent,
                            trade_outcome, holding_days
                        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                        """,
                        (
                            run_id,
                            trade["symbol"],
                            trade["trade_date"],
                            trade.get("exit_date"),
                            round(entry_price, 4),
                            round(exit_price, 4),
                            qty,
                            round(entry_price * qty, 2),
                            round(exit_price * qty, 2),
                            round(pnl, 2),
                            round(pnl_pct, 4),
                            "win" if pnl_pct > 0 else "loss",
                            trade.get("holding_days"),
                        ),
                    )

        logger.info(f"[BACKTEST] Saved to DB: run_id={run_id}, {len(trades)} trades written")
        return run_id

    except (psycopg2.DatabaseError, psycopg2.OperationalError) as e:
        raise RuntimeError(f"Operation failed: {e}") from e


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    parser = argparse.ArgumentParser(description="Run composite score + buy/sell signal backtest")
    parser.add_argument(
        "--start-date",
        type=str,
        default=None,
        help="Start date YYYY-MM-DD (default: 2 years ago)",
    )
    parser.add_argument(
        "--end-date",
        type=str,
        default=None,
        help="End date YYYY-MM-DD (default: today)",
    )
    parser.add_argument("--initial-capital", type=float, default=100_000.0, help="Starting capital")
    parser.add_argument("--max-positions", type=int, default=10, help="Max concurrent positions")
    parser.add_argument("--min-composite", type=float, default=50.0, help="Min composite_score (0-100)")
    parser.add_argument("--profit-target", type=float, default=20.0, help="Profit target %%")
    parser.add_argument("--stop-loss", type=float, default=8.0, help="Stop loss %%")
    parser.add_argument("--max-hold-days", type=int, default=60, help="Max holding period in days")
    parser.add_argument(
        "--position-size",
        type=float,
        default=10.0,
        help="Position size as %% of portfolio",
    )
    parser.add_argument("--strategy", type=str, default="composite_score_signals", help="Strategy name")
    parser.add_argument(
        "--slippage-bps",
        type=float,
        default=DEFAULT_SLIPPAGE_BPS,
        help="Per-side slippage/spread haircut in basis points applied to every fill (default: 5.0)",
    )
    parser.add_argument(
        "--base-risk-pct",
        type=float,
        default=None,
        help=(
            "Enable risk-based position sizing (matching live position_sizer.py's "
            "risk_dollars=portfolio_value*base_risk_pct/(entry-stop) formula) instead of the "
            "default flat %%-of-portfolio sizing. Live's AlgoConfig default is 0.75. "
            "--position-size still applies as the maximum position size cap either way. "
            "Still an approximation, not full live parity - see run_backtest()'s 'SIZING "
            "MODEL' docstring section for what remains unsimulated (drawdown-tier reduction, "
            "market-exposure regime, VIX-caution, per-symbol data-maturity discount)."
        ),
    )
    parser.add_argument("--dry-run", action="store_true", help="Print results without saving to DB")
    parser.add_argument(
        "--rank-by",
        type=str,
        default="signal_quality_score",
        choices=["signal_quality_score", "composite_score_pit"],
        help=(
            "Ranking key for same-day BUY signals. 'signal_quality_score' (default) is "
            "contemporaneous, from buy_sell_daily. 'composite_score_pit' ranks by a genuinely "
            "point-in-time composite_score from stock_scores_history (asof-joined by symbol, "
            "score_date<=signal_date) - this is what actually tests live Phase 7's real "
            "ranking mechanism without look-ahead bias, but stock_scores_history is shallow "
            "(added 2026-08-24) so early runs in this mode are not yet statistically "
            "meaningful. See _get_daily_buy_signals()'s docstring."
        ),
    )
    args = parser.parse_args()

    from algo.config import MAX_BACKFILL_DAYS_LIMIT

    today = date.today()
    start = date.fromisoformat(args.start_date) if args.start_date else today - timedelta(days=MAX_BACKFILL_DAYS_LIMIT)
    end = date.fromisoformat(args.end_date) if args.end_date else today

    results = run_backtest(
        start_date=start,
        end_date=end,
        initial_capital=args.initial_capital,
        max_positions=args.max_positions,
        min_composite=args.min_composite,
        profit_target_pct=args.profit_target,
        stop_loss_pct=args.stop_loss,
        max_hold_days=args.max_hold_days,
        position_size_pct=args.position_size,
        strategy_name=args.strategy,
        slippage_bps=args.slippage_bps,
        rank_by=args.rank_by,
        base_risk_pct=args.base_risk_pct,
    )

    if not results:
        logger.error("Backtest returned no results")
        return 1

    # Several of these metrics are legitimately None (e.g. win_rate_pct/profit_factor/
    # best_trade_pct on a zero-trade run, max_drawdown_pct on a non-positive equity curve) -
    # formatting None with a numeric spec (":.1f", ":+.2f") raises TypeError, which previously
    # crashed this summary print (and the whole CLI run) instead of just showing "n/a" for a
    # backtest window that happened to produce no trades or no losses.
    def _fmt(value: float | None, spec: str, suffix: str = "") -> str:
        return f"{value:{spec}}{suffix}" if value is not None else "n/a"

    # Log summary
    separator = "=" * 60
    logger.info(f"\n{separator}")
    logger.info(f"BACKTEST RESULTS: {results['strategy_name']}")
    logger.info(separator)
    logger.info(f"Period:          {results['start_date']} to {results['end_date']}")
    logger.info(f"Initial Capital: ${results['initial_capital']:,.0f}")
    logger.info(f"Final Capital:   ${results['final_capital']:,.0f}")
    logger.info(f"Total Return:    {_fmt(results['total_return_pct'], '+.2f', '%')}")
    logger.info(f"Ann. Return:     {_fmt(results['annualized_return_pct'], '+.2f', '%')}")
    logger.info(f"Max Drawdown:    {_fmt(results['max_drawdown_pct'], '.2f', '%')}")
    logger.info(f"Sharpe Ratio:    {results['sharpe_ratio']}")
    logger.info(f"Sortino Ratio:   {results['sortino_ratio']}")
    logger.info(f"Calmar Ratio:    {results['calmar_ratio']}")
    logger.info(f"Win Rate:        {_fmt(results['win_rate_pct'], '.1f', '%')}")
    logger.info(f"Profit Factor:   {_fmt(results['profit_factor'], '.2f')}")
    logger.info(f"Total Trades:    {results['total_trades']}")
    logger.info(f"Wins/Losses:     {results['winning_trades']}/{results['losing_trades']}")
    logger.info(f"Avg Trade:       {_fmt(results['avg_trade_return_pct'], '+.2f', '%')}")
    logger.info(f"Best Trade:      {_fmt(results['best_trade_pct'], '+.2f', '%')}")
    logger.info(f"Worst Trade:     {_fmt(results['worst_trade_pct'], '+.2f', '%')}")
    logger.info(f"Avg Hold:        {_fmt(results['avg_holding_days'], '.1f', ' days')}")
    logger.info(separator)

    trades_list = results.pop("trades", [])
    results.pop("equity_curve", [])

    if not args.dry_run:
        results["trades"] = trades_list
        run_id = save_results(results)
        if run_id:
            logger.info(f"[BACKTEST] Saved to DB: run_id={run_id}")
            return 0
        else:
            logger.error("[BACKTEST] Failed to save to DB (see logs)")
            return 1
    else:
        logger.info("[BACKTEST] [DRY RUN] Results not saved to DB")
        return 0


if __name__ == "__main__":
    sys.exit(main())
