const { Pool } = require('pg');

const pool = new Pool({
  host: process.env.DB_HOST || 'localhost',
  port: process.env.DB_PORT || 5432,
  database: process.env.DB_NAME || 'stocks',
  user: process.env.DB_USER || 'stockuser',
  password: process.env.DB_PASSWORD || 'stockpass'
});

async function loadSampleData() {
  const client = await pool.connect();

  try {
    console.log('🔄 Clearing existing data...');
    await client.query('DELETE FROM buy_sell_daily');

    console.log('📊 Inserting sample swing trading signals...');

    const signals = [
      {
        symbol: 'AAPL',
        signal: 'BUY',
        date: '2025-09-28',
        open: 174.5,
        high: 176.2,
        low: 173.8,
        close: 175.5,
        volume: 65000000,
        buylevel: 175.0,
        stoplevel: 162.75,
        inposition: true,
        // Swing trading metrics
        selllevel: 218.75,
        target_price: 218.75,
        current_price: 175.5,
        risk_reward_ratio: 3.5,
        market_stage: 'Stage 2 - Advancing',
        stage_confidence: 85,
        substage: 'Stage 2 - Mid',
        sata_score: 8,  // Strong Stage 2
        pct_from_ema_21: 1.2,
        pct_from_sma_50: 3.5,
        pct_from_sma_200: 8.2,
        volume_ratio: 2.1,
        volume_analysis: 'Very High',
        entry_quality_score: 82,
        profit_target_8pct: 189.0,
        profit_target_20pct: 210.0,
        current_gain_loss_pct: 0.0,
        risk_pct: 7.0,
        position_size_recommendation: 80,
        passes_minervini_template: true,
        rsi: 58,
        adx: 32,
        atr: 3.2,
        daily_range_pct: 1.4,
        volatility_profile: 'medium'
      },
      {
        symbol: 'MSFT',
        signal: 'BUY',
        date: '2025-09-28',
        open: 419.0,
        high: 422.5,
        low: 418.2,
        close: 420.75,
        volume: 28000000,
        buylevel: 420.0,
        stoplevel: 388.0,
        inposition: true,
        selllevel: 525.0,
        target_price: 525.0,
        current_price: 420.75,
        risk_reward_ratio: 3.3,
        market_stage: 'Stage 2 - Advancing',
        stage_confidence: 78,
        substage: 'Stage 2 - Early',
        sata_score: 7,  // Early Stage 2
        pct_from_ema_21: -0.5,
        pct_from_sma_50: 2.1,
        pct_from_sma_200: 12.5,
        volume_ratio: 1.5,
        volume_analysis: 'High',
        entry_quality_score: 75,
        profit_target_8pct: 453.6,
        profit_target_20pct: 504.0,
        current_gain_loss_pct: 0.0,
        risk_pct: 7.6,
        position_size_recommendation: 65,
        passes_minervini_template: true,
        rsi: 52,
        adx: 28,
        atr: 4.5,
        daily_range_pct: 1.0,
        volatility_profile: 'medium'
      },
      {
        symbol: 'GOOGL',
        signal: 'SELL',
        date: '2025-09-28',
        open: 144.0,
        high: 144.5,
        low: 143.0,
        close: 143.5,
        volume: 22000000,
        buylevel: 145.0,
        stoplevel: 140.0,
        inposition: false,
        selllevel: 122.75,
        target_price: 122.75,
        current_price: 143.5,
        risk_reward_ratio: 2.8,
        market_stage: 'Stage 3 - Topping',
        stage_confidence: 72,
        substage: 'Stage 3 - Late',
        sata_score: 5,  // Stage 3 Topping
        pct_from_ema_21: -2.1,
        pct_from_sma_50: -4.5,
        pct_from_sma_200: -1.2,
        volume_ratio: 0.8,
        volume_analysis: 'Low',
        entry_quality_score: 45,
        profit_target_8pct: 133.4,
        profit_target_20pct: 116.0,
        current_gain_loss_pct: -1.0,
        risk_pct: 3.4,
        position_size_recommendation: 0,
        passes_minervini_template: false,
        rsi: 68,
        adx: 22,
        atr: 2.8,
        daily_range_pct: 1.0,
        volatility_profile: 'low'
      },
      {
        symbol: 'NVDA',
        signal: 'BUY',
        date: '2025-09-28',
        open: 118.0,
        high: 120.5,
        low: 117.5,
        close: 119.8,
        volume: 95000000,
        buylevel: 119.0,
        stoplevel: 110.0,
        inposition: true,
        selllevel: 148.75,
        target_price: 148.75,
        current_price: 119.8,
        risk_reward_ratio: 3.3,
        market_stage: 'Stage 2 - Advancing',
        stage_confidence: 92,
        substage: 'Stage 2 - Mid',
        sata_score: 9,  // Very strong Stage 2
        pct_from_ema_21: 0.8,
        pct_from_sma_50: 5.2,
        pct_from_sma_200: 15.3,
        volume_ratio: 2.5,
        volume_analysis: 'Very High',
        entry_quality_score: 88,
        profit_target_8pct: 128.5,
        profit_target_20pct: 142.8,
        current_gain_loss_pct: 0.67,
        risk_pct: 7.6,
        position_size_recommendation: 110,
        passes_minervini_template: true,
        rsi: 62,
        adx: 35,
        atr: 5.2,
        daily_range_pct: 2.5,
        volatility_profile: 'high'
      },
      {
        symbol: 'META',
        signal: 'BUY',
        date: '2025-09-28',
        open: 392.0,
        high: 397.5,
        low: 390.2,
        close: 394.79,
        volume: 18000000,
        buylevel: 395.0,
        stoplevel: 365.0,
        inposition: true,
        selllevel: 493.75,
        target_price: 493.75,
        current_price: 394.79,
        risk_reward_ratio: 3.3,
        market_stage: 'Stage 2 - Advancing',
        stage_confidence: 81,
        substage: 'Stage 2 - Mid',
        sata_score: 7,  // Stage 2 Mid
        pct_from_ema_21: 1.5,
        pct_from_sma_50: 4.2,
        pct_from_sma_200: 10.8,
        volume_ratio: 1.3,
        volume_analysis: 'Average',
        entry_quality_score: 76,
        profit_target_8pct: 426.6,
        profit_target_20pct: 474.0,
        current_gain_loss_pct: 0.0,
        risk_pct: 7.6,
        position_size_recommendation: 32,
        passes_minervini_template: true,
        rsi: 56,
        adx: 30,
        atr: 8.5,
        daily_range_pct: 1.9,
        volatility_profile: 'medium'
      },
      {
        symbol: 'TSLA',
        signal: 'BUY',
        date: '2025-09-28',
        open: 248.0,
        high: 252.5,
        low: 246.8,
        close: 250.2,
        volume: 82000000,
        buylevel: 250.0,
        stoplevel: 232.0,
        inposition: false,
        selllevel: 312.5,
        target_price: 312.5,
        current_price: 250.2,
        risk_reward_ratio: 3.5,
        market_stage: 'Stage 2 - Advancing',
        stage_confidence: 68,
        substage: 'Stage 2 - Late',
        sata_score: 6,  // Stage 2 Late
        pct_from_ema_21: 4.2,
        pct_from_sma_50: 8.5,
        pct_from_sma_200: 18.2,
        volume_ratio: 1.8,
        volume_analysis: 'High',
        entry_quality_score: 65,
        profit_target_8pct: 270.0,
        profit_target_20pct: 300.0,
        current_gain_loss_pct: 0.08,
        risk_pct: 7.2,
        position_size_recommendation: 55,
        passes_minervini_template: true,
        rsi: 71,
        adx: 26,
        atr: 12.5,
        daily_range_pct: 2.3,
        volatility_profile: 'high'
      },
      {
        symbol: 'NFLX',
        signal: 'HOLD',
        date: '2025-09-28',
        open: 682.0,
        high: 688.5,
        low: 679.2,
        close: 685.5,
        volume: 3500000,
        buylevel: 685.0,
        stoplevel: 650.0,
        inposition: false,
        selllevel: 685.0,
        target_price: 685.0,
        current_price: 685.5,
        risk_reward_ratio: 1.0,
        market_stage: 'Stage 1 - Basing',
        stage_confidence: 55,
        substage: 'Stage 1 - Late',
        sata_score: 4,  // Stage 1 Basing
        pct_from_ema_21: 0.2,
        pct_from_sma_50: -1.2,
        pct_from_sma_200: 5.5,
        volume_ratio: 0.9,
        volume_analysis: 'Average',
        entry_quality_score: 52,
        profit_target_8pct: 740.0,
        profit_target_20pct: 822.0,
        current_gain_loss_pct: 0.0,
        risk_pct: 5.1,
        position_size_recommendation: 0,
        passes_minervini_template: false,
        rsi: 48,
        adx: 18,
        atr: 15.2,
        daily_range_pct: 1.4,
        volatility_profile: 'medium'
      },
      {
        symbol: 'AMD',
        signal: 'BUY',
        date: '2025-09-28',
        open: 162.0,
        high: 165.5,
        low: 161.2,
        close: 164.3,
        volume: 58000000,
        buylevel: 164.0,
        stoplevel: 152.0,
        inposition: true,
        selllevel: 205.0,
        target_price: 205.0,
        current_price: 164.3,
        risk_reward_ratio: 3.4,
        market_stage: 'Stage 2 - Advancing',
        stage_confidence: 76,
        substage: 'Stage 2 - Early',
        sata_score: 7,  // Early Stage 2
        pct_from_ema_21: 0.5,
        pct_from_sma_50: 3.8,
        pct_from_sma_200: 14.2,
        volume_ratio: 1.9,
        volume_analysis: 'High',
        entry_quality_score: 73,
        profit_target_8pct: 177.12,
        profit_target_20pct: 196.8,
        current_gain_loss_pct: 0.18,
        risk_pct: 7.3,
        position_size_recommendation: 85,
        passes_minervini_template: true,
        rsi: 54,
        adx: 27,
        atr: 6.8,
        daily_range_pct: 2.7,
        volatility_profile: 'high'
      }
    ];

    for (const signal of signals) {
      await client.query(`
        INSERT INTO buy_sell_daily (
          symbol, timeframe, date, open, high, low, close, volume, signal,
          buylevel, stoplevel, inposition, selllevel, target_price, current_price,
          risk_reward_ratio, market_stage, stage_confidence, substage, sata_score,
          pct_from_ema_21, pct_from_sma_50, pct_from_sma_200,
          volume_ratio, volume_analysis, entry_quality_score,
          profit_target_8pct, profit_target_20pct, current_gain_loss_pct,
          risk_pct, position_size_recommendation, passes_minervini_template,
          rsi, adx, atr, daily_range_pct, volatility_profile
        ) VALUES (
          $1, 'daily', $2, $3, $4, $5, $6, $7, $8,
          $9, $10, $11, $12, $13, $14,
          $15, $16, $17, $18, $19,
          $20, $21, $22,
          $23, $24, $25,
          $26, $27, $28,
          $29, $30, $31,
          $32, $33, $34, $35, $36
        )
      `, [
        signal.symbol, signal.date, signal.open, signal.high, signal.low,
        signal.close, signal.volume, signal.signal, signal.buylevel, signal.stoplevel,
        signal.inposition, signal.selllevel, signal.target_price, signal.current_price,
        signal.risk_reward_ratio, signal.market_stage, signal.stage_confidence, signal.substage, signal.sata_score,
        signal.pct_from_ema_21, signal.pct_from_sma_50, signal.pct_from_sma_200,
        signal.volume_ratio, signal.volume_analysis, signal.entry_quality_score,
        signal.profit_target_8pct, signal.profit_target_20pct, signal.current_gain_loss_pct,
        signal.risk_pct, signal.position_size_recommendation, signal.passes_minervini_template,
        signal.rsi, signal.adx, signal.atr, signal.daily_range_pct, signal.volatility_profile
      ]);
      console.log(`  ✅ ${signal.symbol} - ${signal.signal} (Stage: ${signal.market_stage}, Confidence: ${signal.stage_confidence})`);
    }

    console.log(`\n✅ Loaded ${signals.length} sample signals with full swing trading metrics!`);
    console.log('\n🌐 View at: http://localhost:5174/signals');

  } catch (error) {
    console.error('❌ Error loading data:', error);
    throw error;
  } finally {
    client.release();
    await pool.end();
  }
}

loadSampleData().catch(console.error);
