#!/bin/bash

# Dynamic Frontend Build Script
# This script builds the frontend with the correct API URL from CloudFormation

set -e

STACK_NAME=${1:-"financial-dashboard-dev"}
ENVIRONMENT=${2:-"dev"}

echo "🚀 Building frontend for stack: $STACK_NAME"

# Get API Gateway URL from CloudFormation stack outputs
echo "📡 Fetching API Gateway URL from CloudFormation..."
API_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' \
  --output text)

if [ -z "$API_URL" ] || [ "$API_URL" = "None" ]; then
  echo "❌ Failed to get API Gateway URL from stack $STACK_NAME"
  echo "   Available stacks:"
  aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --query 'StackSummaries[].StackName' --output table
  exit 1
fi

echo "✅ Found API Gateway URL: $API_URL"

# Create dynamic .env file
echo "📝 Creating .env file with dynamic API URL..."
cat > .env << EOF
# Auto-generated by deploy script
VITE_API_URL=$API_URL
VITE_SERVERLESS=true
VITE_ENVIRONMENT=$ENVIRONMENT
VITE_BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VITE_STACK_NAME=$STACK_NAME
EOF

echo "📋 Environment configuration:"
cat .env

# Build the frontend
echo "🔨 Building frontend..."
npm run build

echo "✅ Frontend build complete!"
echo "📁 Built files are in the 'dist' directory"
echo "🌐 API URL: $API_URL"
