"""Standardized exception hierarchy for the entire codebase."""

from .core import (
    BaseAPIException,
    DatabaseError,
    DatabaseConnectionError,
    DatabaseQueryTimeout,
    DatabaseSchemaError,
    DatabaseConstraintViolation,
    ValidationError,
    InputValidationError,
    DataQualityError,
    SchemaValidationError,
    TimeoutError as APITimeoutError,
    DatabaseTimeout,
    ExternalAPITimeout,
    LoaderTimeout,
    ExternalAPIError,
    HTTPError,
    RateLimitedError,
    ServiceUnavailableError,
    DataError,
    MissingDataError,
    StaleDataError,
    IncompleteDataError,
    InternalError,
    UnexpectedError,
    ProcessingError,
)

__all__ = [
    'BaseAPIException',
    'DatabaseError',
    'DatabaseConnectionError',
    'DatabaseQueryTimeout',
    'DatabaseSchemaError',
    'DatabaseConstraintViolation',
    'ValidationError',
    'InputValidationError',
    'DataQualityError',
    'SchemaValidationError',
    'APITimeoutError',
    'DatabaseTimeout',
    'ExternalAPITimeout',
    'LoaderTimeout',
    'ExternalAPIError',
    'HTTPError',
    'RateLimitedError',
    'ServiceUnavailableError',
    'DataError',
    'MissingDataError',
    'StaleDataError',
    'IncompleteDataError',
    'InternalError',
    'UnexpectedError',
    'ProcessingError',
]
