"""Standardized exception hierarchy for the entire codebase."""

from .core import (
    BaseAPIException,
    DatabaseConnectionError,
    DatabaseConstraintViolation,
    DatabaseError,
    DatabaseQueryTimeout,
    DatabaseSchemaError,
    DatabaseTimeout,
    DataError,
    DataQualityError,
    ExternalAPIError,
    ExternalAPITimeout,
    HTTPError,
    IncompleteDataError,
    InputValidationError,
    InternalError,
    LoaderTimeout,
    MissingDataError,
    ProcessingError,
    RateLimitedError,
    SchemaValidationError,
    ServiceUnavailableError,
    StaleDataError,
    UnexpectedError,
    ValidationError,
)
from .core import (
    TimeoutError as APITimeoutError,
)


__all__ = [
    "APITimeoutError",
    "BaseAPIException",
    "DataError",
    "DataQualityError",
    "DatabaseConnectionError",
    "DatabaseConstraintViolation",
    "DatabaseError",
    "DatabaseQueryTimeout",
    "DatabaseSchemaError",
    "DatabaseTimeout",
    "ExternalAPIError",
    "ExternalAPITimeout",
    "HTTPError",
    "IncompleteDataError",
    "InputValidationError",
    "InternalError",
    "LoaderTimeout",
    "MissingDataError",
    "ProcessingError",
    "RateLimitedError",
    "SchemaValidationError",
    "ServiceUnavailableError",
    "StaleDataError",
    "UnexpectedError",
    "ValidationError",
]
