"""Structural-typing protocol shared by Orchestrator's mixin files (file-size ratchet split,
2026-09-10). Declares every attribute/method any mixin references on `self` that isn't
defined in that same mixin, so mypy can type-check each mixin's `self.` usage without each
file repeating its own TYPE_CHECKING stub block - see algo/orchestration/orchestrator.py for
the concrete Orchestrator class these mixins compose into (it, not this Protocol, is what
actually runs). Used only under `if TYPE_CHECKING`; has zero runtime effect.
"""

from __future__ import annotations

from typing import Any, Protocol

from algo.orchestrator.phase_executor import OrchestratorPhaseExecutor


class OrchestratorProtocol(Protocol):
    _STATUS_FLAGS: dict[str, str]
    _cached_db_execution_mode: Any
    _execution_mode_mismatch_alert: Any
    _exposure_actions: Any
    _exposure_constraints: Any
    _lock_acquired: bool
    _phase1_result: Any
    _phase2_result: Any
    _phase3_result: Any
    _phase5_result: Any
    _phase9_result: Any
    _position_recs: Any
    _prior_sigterm_handler: Any
    alerts: Any
    config: Any
    db_monitor: Any
    degraded_mode: bool
    dry_run: bool
    execution_mode: str
    execution_tracker: Any
    executor: OrchestratorPhaseExecutor
    halt_manager: Any
    lock_manager: Any
    phase_results: Any
    run_date: Any
    run_id: str
    run_start: float
    verbose: bool

    def _acquire_run_lock(self, *args: Any, **kwargs: Any) -> Any: ...
    def _check_loader_health(self, *args: Any, **kwargs: Any) -> Any: ...
    def _cleanup_expired_locks(self, *args: Any, **kwargs: Any) -> Any: ...
    def _cleanup_stale_loader_locks(self, *args: Any, **kwargs: Any) -> Any: ...
    def _cleanup_stale_orchestrator_run_locks(self, *args: Any, **kwargs: Any) -> Any: ...
    def _emit_performance_metrics(self, *args: Any, **kwargs: Any) -> Any: ...
    def _execute_phases(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def _executor_phase_1(self, *args: Any, **kwargs: Any) -> Any: ...
    def _executor_phase_2(self, *args: Any, **kwargs: Any) -> Any: ...
    def _executor_phase_3(self, *args: Any, **kwargs: Any) -> Any: ...
    def _executor_phase_4(self, *args: Any, **kwargs: Any) -> Any: ...
    def _executor_phase_5(self, *args: Any, **kwargs: Any) -> Any: ...
    def _executor_phase_6(self, *args: Any, **kwargs: Any) -> Any: ...
    def _executor_phase_7(self, *args: Any, **kwargs: Any) -> Any: ...
    def _executor_phase_8(self, *args: Any, **kwargs: Any) -> Any: ...
    def _executor_phase_9(self, *args: Any, **kwargs: Any) -> Any: ...
    def _final_report(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def _handle_concurrency_lock(self, *args: Any, **kwargs: Any) -> dict[str, Any] | None: ...
    def _handle_executor_result(self, *args: Any, **kwargs: Any) -> dict[str, Any] | None: ...
    def _install_shutdown_handler(self, *args: Any, **kwargs: Any) -> Any: ...
    def _kill_long_running_loaders(self, *args: Any, **kwargs: Any) -> Any: ...
    def _release_run_lock(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resolve_execution_mode(self, *args: Any, **kwargs: Any) -> Any: ...
    def _restore_shutdown_handler(self, *args: Any, **kwargs: Any) -> Any: ...
    def _run_pipeline_health_sweep(self, *args: Any, **kwargs: Any) -> Any: ...
    def _run_preflight_checks(self, *args: Any, **kwargs: Any) -> dict[str, Any] | None: ...
    def _save_early_exit_log(self, *args: Any, **kwargs: Any) -> Any: ...
    def _save_orchestrator_run_status(self, *args: Any, **kwargs: Any) -> Any: ...
    def _setup_executor(self, *args: Any, **kwargs: Any) -> OrchestratorPhaseExecutor: ...
    def _validate_required_tables(self, *args: Any, **kwargs: Any) -> Any: ...
    def _validate_startup_configuration(self, *args: Any, **kwargs: Any) -> Any: ...
    def _verify_alpaca_account_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def _verify_database_isolation_level(self, *args: Any, **kwargs: Any) -> Any: ...
    def _wait_for_critical_loaders_proactive(self, *args: Any, **kwargs: Any) -> Any: ...
    def _wait_for_loaders_before_execution(self, *args: Any, **kwargs: Any) -> Any: ...
    def log_phase_result(self, *args: Any, **kwargs: Any) -> Any: ...
    def log_phase_start(self, *args: Any, **kwargs: Any) -> Any: ...
    def phase_1_data_freshness(self, *args: Any, **kwargs: Any) -> Any: ...
    def phase_2_circuit_breakers(self, *args: Any, **kwargs: Any) -> Any: ...
    def phase_3_position_monitor(self, *args: Any, **kwargs: Any) -> Any: ...
    def phase_5_exposure_policy(self, *args: Any, **kwargs: Any) -> Any: ...
    def phase_9_reconcile(self, *args: Any, **kwargs: Any) -> Any: ...
