"""Loader execution priority system for coordinated scheduling.

Defines which loaders are high-priority (must run first) vs background (can run in parallel).
Used by EventBridge scheduling and orchestrator pre-flight checks to ensure critical loaders
complete before trading phases start.

Strategy:
- PHASE_1_CRITICAL: Must complete before Phase 1 (prices, technical, market regime)
- PHASE_1_OPTIONAL: Can run in parallel with Phase 1 (enrichment data)
- BACKGROUND: Can run anytime without blocking trading (sentiment, growth metrics)
"""

from enum import Enum


class LoaderPriority(Enum):
    """Priority levels for loader execution."""

    PHASE_1_CRITICAL = 1  # Must finish before Phase 1 (blocking)
    PHASE_1_OPTIONAL = 2  # Can run during Phase 1 (non-blocking)
    BACKGROUND = 3  # Can run anytime, doesn't block trading


# Loader execution order (map table_name -> priority)
LOADER_PRIORITY_MAP: dict[str, LoaderPriority] = {
    # ===== PHASE 1 CRITICAL (highest priority, must complete before Phase 1) =====
    # These are blocking: if they're still running when orchestrator fires, Phase 1 waits
    "price_daily": LoaderPriority.PHASE_1_CRITICAL,
    "price_weekly": LoaderPriority.PHASE_1_CRITICAL,
    "price_monthly": LoaderPriority.PHASE_1_CRITICAL,
    "etf_price_daily": LoaderPriority.PHASE_1_CRITICAL,
    "etf_price_weekly": LoaderPriority.PHASE_1_CRITICAL,
    "etf_price_monthly": LoaderPriority.PHASE_1_CRITICAL,
    "technical_data_daily": LoaderPriority.PHASE_1_CRITICAL,  # Minervini/Weinstein
    "market_health_daily": LoaderPriority.PHASE_1_CRITICAL,  # Market regime gating
    "market_exposure_daily": LoaderPriority.PHASE_1_CRITICAL,  # Position sizing
    "earnings_calendar": LoaderPriority.PHASE_1_OPTIONAL,  # DOWNGRADED 2026-08-05: Consistent yfinance timeout (exceeds 1h SLA). Move to optional to unblock Phase 1.
    # ===== PHASE 1 OPTIONAL (medium priority, nice-to-have enrichment) =====
    # These should finish by Phase 1 but won't block if slow
    "trend_template_data": LoaderPriority.PHASE_1_OPTIONAL,
    # BUG FOUND 2026-08-10: growth/quality/value/positioning/stability_metrics were PHASE_1_CRITICAL
    # here (comment: "FIXED 2026-07-07: Required for stock scoring (Phase 1 now validates)"), but
    # algo/orchestrator/phase1_data_freshness.py's actual code moved all 5 to its warn_tables dict
    # (Session 221: "they're website enrichments, not core to signals" - stale -> logged, trading
    # continues) - Phase 1 does NOT halt on these, contradicting this stale PHASE_1_CRITICAL tag.
    # Live-confirmed damage: orchestrator.py's _wait_for_critical_loaders_proactive() polls
    # get_critical_loaders() and actively waits up to 300s for PHASE_1_CRITICAL loaders to reach
    # 90%+ completion - live-reproduced growth_metrics/quality_metrics sitting at status=RUNNING,
    # completion_pct=0.00% for 56+ minutes (a stuck/abandoned row, same class as
    # [[loader_status_mark_running_stale_completion_pct_fix_20260810]]), which would burn the full
    # 5-minute proactive wait on every orchestrator run for tables Phase 1 doesn't even require.
    # Downgraded to PHASE_1_OPTIONAL to match phase1_data_freshness.py's actual, deliberate,
    # documented behavior instead of a 2026-07-07 decision that was superseded by Session 221 but
    # never reflected here.
    "growth_metrics": LoaderPriority.PHASE_1_OPTIONAL,
    "quality_metrics": LoaderPriority.PHASE_1_OPTIONAL,
    "value_metrics": LoaderPriority.PHASE_1_OPTIONAL,
    "positioning_metrics": LoaderPriority.PHASE_1_OPTIONAL,
    "stability_metrics": LoaderPriority.PHASE_1_OPTIONAL,
    "sector_ranking": LoaderPriority.PHASE_1_CRITICAL,  # FIXED: Position Monitor (Phase 3) requires sector_ranking data
    "insider_transaction_velocity": LoaderPriority.PHASE_1_OPTIONAL,  # Session 444: Insider confidence scoring (enrichment for positioning_metrics)
    "sec_segment_info": LoaderPriority.PHASE_1_OPTIONAL,  # XBRL segment disclosure source for diversification metrics (enrichment for quality_metrics)
    "sec_segment_metrics": LoaderPriority.PHASE_1_OPTIONAL,  # Segment diversification (Herfindahl index) from sec_segment_info (enrichment for quality_metrics)
    # ===== BACKGROUND (low priority, can run anytime) =====
    # These don't block trading; dashboard shows graceful degradation if missing
    "aaii_sentiment": LoaderPriority.BACKGROUND,
    "fear_greed_index": LoaderPriority.BACKGROUND,
    # ===== ORCHESTRATOR OUTPUTS (lowest priority, generated by orchestrator) =====
    # These should never block; orchestrator will regenerate if needed
    "stock_scores": LoaderPriority.BACKGROUND,
    "buy_sell_daily": LoaderPriority.BACKGROUND,
}


def get_priority(table_name: str) -> LoaderPriority:
    """Get the priority level for a loader.

    Args:
        table_name: Loader's table_name from data_loader_status

    Returns:
        LoaderPriority for this loader (default BACKGROUND if unknown)
    """
    return LOADER_PRIORITY_MAP.get(table_name, LoaderPriority.BACKGROUND)


def is_phase1_critical(table_name: str) -> bool:
    return get_priority(table_name) == LoaderPriority.PHASE_1_CRITICAL


def is_phase1_optional(table_name: str) -> bool:
    return get_priority(table_name) == LoaderPriority.PHASE_1_OPTIONAL


def is_background(table_name: str) -> bool:
    return get_priority(table_name) == LoaderPriority.BACKGROUND


def get_critical_loaders() -> set[str]:
    return {name for name, priority in LOADER_PRIORITY_MAP.items() if priority == LoaderPriority.PHASE_1_CRITICAL}


def get_optional_loaders() -> set[str]:
    return {name for name, priority in LOADER_PRIORITY_MAP.items() if priority == LoaderPriority.PHASE_1_OPTIONAL}


def get_background_loaders() -> set[str]:
    return {name for name, priority in LOADER_PRIORITY_MAP.items() if priority == LoaderPriority.BACKGROUND}
