"""Loader execution priority system for coordinated scheduling.

Defines which loaders are high-priority (must run first) vs background (can run in parallel).
Used by EventBridge scheduling and orchestrator pre-flight checks to ensure critical loaders
complete before trading phases start.

Strategy:
- PHASE_1_CRITICAL: Must complete before Phase 1 (prices, technical, market regime)
- PHASE_1_OPTIONAL: Can run in parallel with Phase 1 (enrichment data)
- BACKGROUND: Can run anytime without blocking trading (sentiment, growth metrics)
"""

from enum import Enum


class LoaderPriority(Enum):
    """Priority levels for loader execution."""

    PHASE_1_CRITICAL = 1  # Must finish before Phase 1 (blocking)
    PHASE_1_OPTIONAL = 2  # Can run during Phase 1 (non-blocking)
    BACKGROUND = 3  # Can run anytime, doesn't block trading


# Loader execution order (map table_name -> priority)
LOADER_PRIORITY_MAP: dict[str, LoaderPriority] = {
    # ===== PHASE 1 CRITICAL (highest priority, must complete before Phase 1) =====
    # These are blocking: if they're still running when orchestrator fires, Phase 1 waits
    "price_daily": LoaderPriority.PHASE_1_CRITICAL,
    "price_weekly": LoaderPriority.PHASE_1_CRITICAL,
    "price_monthly": LoaderPriority.PHASE_1_CRITICAL,
    "etf_price_daily": LoaderPriority.PHASE_1_CRITICAL,
    "etf_price_weekly": LoaderPriority.PHASE_1_CRITICAL,
    "etf_price_monthly": LoaderPriority.PHASE_1_CRITICAL,
    "technical_data_daily": LoaderPriority.PHASE_1_CRITICAL,  # Minervini/Weinstein
    "market_health_daily": LoaderPriority.PHASE_1_CRITICAL,  # Market regime gating
    "market_exposure_daily": LoaderPriority.PHASE_1_CRITICAL,  # Position sizing
    "earnings_calendar": LoaderPriority.PHASE_1_CRITICAL,  # Blackout window gating
    # ===== PHASE 1 OPTIONAL (medium priority, nice-to-have enrichment) =====
    # These should finish by Phase 1 but won't block if slow
    "trend_template_data": LoaderPriority.PHASE_1_OPTIONAL,
    "sector_ranking": LoaderPriority.PHASE_1_OPTIONAL,
    # ===== BACKGROUND (low priority, can run anytime) =====
    # These don't block trading; dashboard shows graceful degradation if missing
    "growth_metrics": LoaderPriority.BACKGROUND,
    "value_metrics": LoaderPriority.BACKGROUND,
    "positioning_metrics": LoaderPriority.BACKGROUND,
    "analyst_sentiment_analysis": LoaderPriority.BACKGROUND,
    "stability_metrics": LoaderPriority.BACKGROUND,
    "economic_metrics_daily": LoaderPriority.BACKGROUND,
    "aaii_sentiment": LoaderPriority.BACKGROUND,
    "fear_greed_index": LoaderPriority.BACKGROUND,
    # ===== ORCHESTRATOR OUTPUTS (lowest priority, generated by orchestrator) =====
    # These should never block; orchestrator will regenerate if needed
    "stock_scores": LoaderPriority.BACKGROUND,
    "buy_sell_daily": LoaderPriority.BACKGROUND,
}


def get_priority(table_name: str) -> LoaderPriority:
    """Get the priority level for a loader.

    Args:
        table_name: Loader's table_name from data_loader_status

    Returns:
        LoaderPriority for this loader (default BACKGROUND if unknown)
    """
    return LOADER_PRIORITY_MAP.get(table_name, LoaderPriority.BACKGROUND)


def is_phase1_critical(table_name: str) -> bool:
    """Returns True if this loader must complete before Phase 1."""
    return get_priority(table_name) == LoaderPriority.PHASE_1_CRITICAL


def is_phase1_optional(table_name: str) -> bool:
    """Returns True if this loader should complete by Phase 1 but won't block."""
    return get_priority(table_name) == LoaderPriority.PHASE_1_OPTIONAL


def is_background(table_name: str) -> bool:
    """Returns True if this loader can run anytime without blocking."""
    return get_priority(table_name) == LoaderPriority.BACKGROUND


def get_critical_loaders() -> set[str]:
    """Get all Phase 1 critical loaders (must complete before orchestrator phases)."""
    return {name for name, priority in LOADER_PRIORITY_MAP.items() if priority == LoaderPriority.PHASE_1_CRITICAL}


def get_optional_loaders() -> set[str]:
    """Get all Phase 1 optional loaders (nice-to-have enrichment)."""
    return {name for name, priority in LOADER_PRIORITY_MAP.items() if priority == LoaderPriority.PHASE_1_OPTIONAL}


def get_background_loaders() -> set[str]:
    """Get all background loaders (can run anytime)."""
    return {name for name, priority in LOADER_PRIORITY_MAP.items() if priority == LoaderPriority.BACKGROUND}
