"""Dashboard API contract - core algo/dashboard operational endpoints.

Split out of dashboard_api_contract.py (file-size ratchet decomposition, 2026-09-05).
Data-only module: run/config/portfolio/performance/health/audit/execution-history
endpoints. See dashboard_api_contract.py for EndpointRegistry/PanelRegistry."""

from typing import Any

from .dashboard_api_contract_models import ResponseSchema

CORE_ENDPOINTS: dict[str, dict[str, Any]] = {
    "run": {
        "path": "/api/algo/last-run",
        "method": "GET",
        "description": "Last algo run status",
        "response_schema": ResponseSchema(
            required_fields=["run_id", "success"],
            optional_fields=[
                "completed_at",
                "started_at",
                "phases",
                "halted",
                "errored",
                "summary",
                "halt_reason",
                "phases_completed",
                "phases_halted",
                "phases_errored",
                "phase_results",
                "last_run",
                "current_phase",
                "status",
                "message",
                "portfolio",
                "data_freshness",
            ],
            field_types={
                "run_id": (str, int),
                "completed_at": (str, type(None)),
                "started_at": (str, type(None)),
                "success": bool,
                "halted": (bool, type(None)),
                "errored": (bool, type(None)),
                "last_run": (str, type(None)),
                "current_phase": (str, type(None)),
                "status": (str, type(None)),
                "message": (str, type(None)),
                "portfolio": dict,
                "data_freshness": dict,
            },
            description="Last run metadata and status",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": ["run_id", "success"],
        "critical": True,
    },
    "cfg": {
        "path": "/api/algo/config",
        "method": "GET",
        "description": "Algo configuration",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "enable_algo",
                "execution_mode",
                "max_position_size_pct",
                "max_positions",
                "max_positions_per_sector",
                "base_risk_pct",
                "t1_target_r_multiple",
                "min_swing_grade",
                "min_swing_score",
                "swing_grade_threshold_a",
                "swing_grade_threshold_aplus",
                "swing_grade_threshold_b",
                "swing_grade_threshold_c",
                "swing_grade_threshold_d",
            ],
            field_types={},
            nested_schema={"*": dict},
            description="Algo configuration and settings",
        ),
        "freshness_max_age_seconds": None,
        "strict_fields": [],
        "critical": True,
    },
    "mkt": {
        "path": "/api/algo/markets",
        "method": "GET",
        "description": "Market data (SPY, VIX, halts, regime)",
        "response_schema": ResponseSchema(
            required_fields=["spy_close", "vix_level"],
            optional_fields=[
                "timestamp",
                "last_updated",
                "exposure_pct",
                "regime",
                "halt_reasons",
                "market_stage",
                "market_trend",
                "distribution_days_4w",
                "spy_change_pct",
                "up_volume_percent",
                "advance_decline_ratio",
                "new_highs_count",
                "new_lows_count",
                "put_call_ratio",
                "put_call_ratio_stale_value",
                "put_call_ratio_stale_date",
                "breadth_momentum_10d",
                "yield_curve_slope",
                "fed_rate_environment",
                "current",
                "market_health",
                "active_tier",
                "adr",
                "bmom",
                "fed",
                "history",
                "history_data_unavailable",
                "items",
                "nh",
                "nl",
                "pcr",
                "total",
                "ycs",
                "sectors",
                "sectors_data_unavailable",
            ],
            field_types={
                "spy_close": (float, int),
                "vix_level": (float, int),
                "timestamp": str,
            },
            description="Critical market data (SPY price, VIX) + indicators",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": ["spy_close", "vix_level"],
        "critical": True,
    },
    "exp_factors": {
        "path": "/api/algo/markets",
        "method": "GET",
        "description": "Market exposure factors (derived from markets endpoint)",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "exposure_pct",
                "raw_score",
                "regime",
                "factors",
                "regime_unavailable",
                "factors_unavailable",
            ],
            field_types={
                "exposure_pct": (float, int, type(None)),
                "raw_score": (float, int, type(None)),
                "regime": (str, type(None)),
                "factors": (list, dict, type(None)),
            },
            description="Exposure factors and market regime from markets endpoint",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "port": {
        "path": "/api/algo/portfolio",
        "method": "GET",
        "description": "Portfolio snapshot",
        "response_schema": ResponseSchema(
            required_fields=["total_portfolio_value", "total_cash", "position_count"],
            optional_fields=[
                "last_run",
                "total_buying_power",
                "daily_return_pct",
                "unrealized_pnl",
                "unrealized_pnl_pct",
                "unrealized_pnl_dollars",
                "cumulative_return_pct",
                "max_drawdown_pct",
                "largest_position_pct",
                "data_age_seconds",
            ],
            field_types={
                "total_portfolio_value": (float, int, str),
                "total_cash": (float, int, str),
                "position_count": int,
                "daily_return_pct": (float, int, str, type(None)),
                "unrealized_pnl": (dict, type(None)),
                "unrealized_pnl_pct": (float, int, str, type(None)),
                "unrealized_pnl_dollars": (float, int, type(None)),
                "cumulative_return_pct": (float, int, str, type(None)),
                "max_drawdown_pct": (float, int, str, type(None)),
                "largest_position_pct": (float, int, str, type(None)),
                "data_age_seconds": (int, type(None)),
            },
            description="Portfolio value, cash, positions",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": ["total_portfolio_value", "total_cash", "position_count"],
        "critical": True,
    },
    "perf": {
        "path": "/api/algo/performance",
        "method": "GET",
        "description": "Performance metrics and statistics",
        "response_schema": ResponseSchema(
            required_fields=["total_trades", "winning_trades", "losing_trades"],
            optional_fields=[
                "timestamp",
                "last_updated",
                "breakeven_trades",
                "win_rate",
                "win_rate_pct",
                "win_rate_confidence",
                "profit_factor",
                "total_pnl_dollars",
                "total_pnl_pct",
                "total_return_pct",
                "avg_trade_pct",
                "avg_win_pct",
                "avg_loss_pct",
                "avg_win_r",
                "avg_loss_r",
                "gross_win_dollars",
                "gross_loss_dollars",
                "open_positions_count",
                "open_losses_count",
                "total_open_losses_dollars",
                "best_trade_pct",
                "worst_trade_pct",
                "sharpe_annualized",
                "sharpe_ratio",
                "sharpe_confidence",
                "sortino_annualized",
                "sortino_ratio",
                "max_drawdown_pct",
                "calmar_ratio",
                "expectancy_r",
                "avg_hold_days",
                "avg_holding_days",
                "best_win_streak",
                "worst_loss_streak",
                "current_streak",
                "equity_vals",
                "recent_rets",
                "stale_alerts",
                "data_freshness",
                "report_date",
                "data_age_seconds",
            ],
            field_types={
                "total_trades": int,
                "winning_trades": int,
                "losing_trades": int,
                "breakeven_trades": (int, type(None)),
                "win_rate": (float, int, str, type(None)),
                "win_rate_pct": (float, int, str, type(None)),
                "win_rate_confidence": (str, type(None)),
                "profit_factor": (float, int, str, type(None)),
                "total_pnl_dollars": (float, int, str, type(None)),
                "total_pnl_pct": (float, int, str, type(None)),
                "total_return_pct": (float, int, str, type(None)),
                "avg_trade_pct": (float, int, str, type(None)),
                "avg_win_pct": (float, int, str, type(None)),
                "avg_loss_pct": (float, int, str, type(None)),
                "avg_win_r": (float, int, str, type(None)),
                "avg_loss_r": (float, int, str, type(None)),
                "gross_win_dollars": (float, int, str, type(None)),
                "gross_loss_dollars": (float, int, str, type(None)),
                "open_positions_count": (int, type(None)),
                "open_losses_count": (int, type(None)),
                "total_open_losses_dollars": (float, int, str, type(None)),
                "best_trade_pct": (float, int, str, type(None)),
                "worst_trade_pct": (float, int, str, type(None)),
                "sharpe_annualized": (float, int, str, type(None)),
                "sharpe_ratio": (float, int, str, type(None)),
                "sharpe_confidence": (str, type(None)),
                "sortino_annualized": (float, int, str, type(None)),
                "sortino_ratio": (float, int, str, type(None)),
                "max_drawdown_pct": (float, int, str, type(None)),
                "calmar_ratio": (float, int, str, type(None)),
                "expectancy_r": (float, int, str, type(None)),
                "avg_hold_days": (float, int, str, type(None)),
                "avg_holding_days": (float, int, str, type(None)),
                "best_win_streak": (int, type(None)),
                "worst_loss_streak": (int, type(None)),
                "current_streak": (int, type(None)),
                "equity_vals": (list, type(None)),
                "recent_rets": (list, type(None)),
                "stale_alerts": (list, type(None)),
                "data_freshness": (dict, type(None)),
                "report_date": (str, type(None)),
                "data_age_seconds": (int, type(None)),
            },
            description="Trade counts and performance statistics",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": ["total_trades", "winning_trades", "losing_trades"],
        "critical": True,
    },
    "pos": {
        "path": "/api/algo/positions",
        "method": "GET",
        "description": "Open positions",
        "response_schema": ResponseSchema(
            required_fields=["items"],
            optional_fields=[
                "timestamp",
                "coverage",
                "data_freshness",
                "pagination",
                "sector_allocation",
                "stale_alerts",
                "untracked_items",
            ],
            field_types={
                "items": list,
                "coverage": (dict, type(None)),
                "data_freshness": (dict, type(None)),
                "pagination": (dict, type(None)),
                "sector_allocation": (list, dict, type(None)),
                "stale_alerts": (list, type(None)),
            },
            description="List of open positions with details",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": ["items"],
        "critical": False,
    },
    "trades": {
        "path": "/api/algo/trades",
        "method": "GET",
        "params": {"limit": 10, "status": "closed"},
        "description": "Completed trades",
        "response_schema": ResponseSchema(
            required_fields=["items"],
            optional_fields=["timestamp", "data_freshness", "pagination"],
            field_types={
                "items": list,
                "data_freshness": (dict, type(None)),
                "pagination": (dict, type(None)),
            },
            description="List of completed trades (closed/settled)",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": ["items"],
        "critical": False,
    },
    "sig": {
        "path": "/api/algo/dashboard-signals",
        "method": "GET",
        "description": "Dashboard signals and grades",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "n",
                "total",
                "buy_sigs",
                "grades",
                "near",
                "top_a",
                "trend",
                "date",
                "data_freshness",
            ],
            field_types={
                "n": int,
                "total": int,
                "buy_sigs": list,
                "grades": dict,
                "date": (str, type(None)),
                "data_freshness": dict,
            },
            description="Signal counts and classifications",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "health": {
        "path": "/api/algo/data-status",
        "method": "GET",
        "description": "Data loader health status",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "ready_to_trade",
                "summary",
                "items",
                "sources",
                "total",
                "critical_stale",
                "expected_date",
                "as_of",
                "api_route_imports",
                "freshness",
                "status",
                "timestamp",
                "version",
                "execution_health",
                "trading_halt_reason",
                "trading_halted",
                "trading_halt_at",
                "trading_halt_triggered_by",
            ],
            field_types={
                "ready_to_trade": bool,
                "summary": dict,
                "items": list,
                "sources": list,
                "total": int,
                "critical_stale": list,
                "expected_date": str,
                "as_of": str,
                "trading_halt_at": str,
                "api_route_imports": dict,
                "freshness": dict,
                "status": str,
                "timestamp": str,
                "version": str,
            },
            description="Data loader health and readiness",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "cb": {
        "path": "/api/algo/circuit-breakers",
        "method": "GET",
        "description": "Circuit breaker status",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["breakers", "any_triggered", "triggered_count", "data_freshness"],
            field_types={
                "breakers": list,
                "any_triggered": bool,
                "data_freshness": (dict, type(None)),
            },
            description="Circuit breaker states",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "activity": {
        "path": "/api/algo/audit-log",
        "method": "GET",
        "params": {"limit": 50, "offset": 0},
        "description": "Activity and audit log",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["items", "total", "limit", "offset", "data_freshness"],
            field_types={
                "items": list,
                "total": int,
                "limit": int,
                "offset": int,
                "data_freshness": (dict, type(None)),
            },
            description="Recent activity and audit trail",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "notifs": {
        "path": "/api/algo/notifications",
        "method": "GET",
        "params": {"limit": 10},
        "description": "Notifications",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["items", "total"],
            field_types={"items": list, "total": int},
            description="Recent notifications",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "audit": {
        "path": "/api/algo/audit-log",
        "method": "GET",
        "params": {"limit": 50, "offset": 0},
        "description": "Audit log",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["items", "total", "limit", "offset", "data_freshness"],
            field_types={
                "items": list,
                "total": int,
                "limit": int,
                "offset": int,
                "data_freshness": (dict, type(None)),
            },
            description="Audit log entries",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "exec_hist": {
        "path": "/api/algo/execution/recent",
        "method": "GET",
        "params": {"days": 14, "limit": 20},
        "description": "Execution history",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["items", "total", "limit", "data_freshness"],
            field_types={"items": list, "total": int, "limit": int, "data_freshness": (dict, type(None))},
            description="Recent execution records",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "freshness_extended": {
        "path": "/api/algo/freshness/extended",
        "method": "GET",
        "params": {"limit": 20},
        "description": "Extended orchestrator run history: per-run phase breakdown, 30-day "
        "phase success rates, halt-reason frequency, loader failure streaks, and "
        "7d-vs-30d trend",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "run_history",
                "phase_health",
                "failure_patterns",
                "loader_health",
                "loader_health_total_unhealthy",
                "loader_health_total_tracked",
                "trend_summary",
                "generated_at",
            ],
            field_types={
                "run_history": list,
                "phase_health": dict,
                "failure_patterns": list,
                "loader_health": list,
                "loader_health_total_unhealthy": int,
                "loader_health_total_tracked": int,
                "trend_summary": dict,
            },
            description="Cross-run orchestrator health: history, phase success rates, "
            "failure patterns, loader reliability, and trend",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "exec_stats": {
        "path": "/api/algo/execution/stats",
        "method": "GET",
        "params": {"days": 1},
        "description": "Execution success/halt/error rates over a recent window",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["total_runs", "by_status", "success_rate", "halt_rate", "error_rate", "period_days"],
            field_types={"total_runs": int, "by_status": dict, "period_days": int},
            description="Aggregated run outcome rates",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "exec_patterns": {
        "path": "/api/algo/execution/patterns",
        "method": "GET",
        "params": {"days": 30},
        "description": "Which orchestrator phases halt/error most often, with example reasons",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["patterns", "period_days"],
            field_types={"patterns": list, "period_days": int},
            description="Per-phase 30-day failure counts and example reasons",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
}
