"""Dashboard API contract - market/economic/risk endpoints.

Split out of dashboard_api_contract.py (file-size ratchet decomposition, 2026-09-05).
Data-only module: sector rankings, economic calendar, sentiment, risk metrics,
performance analytics, and market status endpoints."""

from typing import Any

from .dashboard_api_contract_models import ResponseSchema

MARKET_ECONOMIC_ENDPOINTS: dict[str, dict[str, Any]] = {
    "srank": {
        "path": "/api/sectors",
        "method": "GET",
        "description": "Sector rankings with trends",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "items",
                "date",
                "signal",
                "strength",
                "details",
                "data_freshness",
                "limit",
                "page",
                "total",
            ],
            field_types={
                "items": list,
                "date": str,
                "signal": str,
                "data_freshness": dict,
                "limit": int,
                "page": int,
                "total": int,
            },
            description="Sector trends and rankings with pagination",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
    "eco": {
        "path": "/api/algo/economic-calendar",
        "method": "GET",
        "description": "Economic indicators and calendar",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "t10",
                "t2",
                "t3m",
                "t6m",
                "yc_10_2",
                "yc_10_3m",
                "hy",
                "ig",
                "oil",
                "nfci",
                "fed_funds",
                "cpi_yoy",
                "unrate",
                "be10",
                "be5",
                "dxy",
                "mortgage",
                "umcsent",
                "items",
            ],
            field_types={
                "t10": (float, int),
                "items": list,
            },
            description="Economic data and calendar events",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
    "sentiment": {
        "path": "/api/algo/sentiment",
        "method": "GET",
        "description": "Market sentiment (fear/greed index and breadth)",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "fear_greed_index",
                "sentiment_score",
                "bullish_pct",
                "bearish_pct",
                "neutral_pct",
                "date",
                "label",
                "data_freshness",
            ],
            field_types={
                "fear_greed_index": (float, int),
                "sentiment_score": (float, int, type(None)),
                "bullish_pct": (float, int, type(None)),
                "bearish_pct": (float, int, type(None)),
                "neutral_pct": (float, int, type(None)),
            },
            description="Market sentiment with fear/greed index and breadth data",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
    "econ_cal": {
        "path": "/api/algo/economic-calendar",
        "method": "GET",
        "description": "Economic calendar events",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["items", "total"],
            field_types={"items": list, "total": int},
            description="Economic calendar events",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
    "risk": {
        "path": "/api/algo/risk-metrics",
        "method": "GET",
        "description": "Risk metrics (VaR, CVaR, beta, concentration)",
        "response_schema": ResponseSchema(
            required_fields=["portfolio_beta", "top_5_concentration"],
            optional_fields=[
                "report_date",
                "var_pct_95",
                "cvar_pct_95",
                "stressed_var_pct",
                "svar",
                "has_positions",
            ],
            field_types={
                "var_pct_95": (float, int),
                "portfolio_beta": (float, int),
                "top_5_concentration": (float, int),
            },
            description="Risk metrics and exposures",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": ["portfolio_beta", "top_5_concentration"],
        "critical": False,
    },
    "perf_anl": {
        "path": "/api/algo/performance-analytics",
        "method": "GET",
        "description": "Performance analytics (Sharpe, Sortino, Calmar, Expectancy, R-multiples)",
        "response_schema": ResponseSchema(
            required_fields=[
                "rolling_sharpe_252d",
                "rolling_sortino_252d",
                "calmar_ratio",
                "win_rate_50t",
                "avg_win_r_50t",
                "avg_loss_r_50t",
                "expectancy",
                "max_drawdown_pct",
            ],
            optional_fields=["report_date", "data_age_seconds"],
            field_types={
                "rolling_sharpe_252d": (float, int, type(None)),
                "rolling_sortino_252d": (float, int, type(None)),
                "calmar_ratio": (float, int, type(None)),
                "win_rate_50t": (float, int, type(None)),
                "avg_win_r_50t": (float, int, type(None)),
                "avg_loss_r_50t": (float, int, type(None)),
                "expectancy": (float, int, type(None)),
                "max_drawdown_pct": (float, int, type(None)),
                "report_date": (str, type(None)),
                "data_age_seconds": (int, type(None)),
            },
            description="Advanced performance metrics (Sharpe, Sortino, Calmar, Win Rate, Avg Win R, Avg Loss R, Expectancy, Max Drawdown)",
        ),
        "freshness_max_age_seconds": 3600,
        # Only rolling_sharpe_252d is guaranteed non-null whenever a row exists at all - generate_daily_report
        # (algo/reporting/performance.py) raises before insert if it's unavailable. The rest are
        # honestly nullable by documented design: win_rate_50t/sortino/calmar need enough snapshot history to compute,
        # and avg_win_r_50t/avg_loss_r_50t/expectancy need both a winning AND a losing trade in the
        # lookback window - an expected early-sample state, not a pipeline failure. Do not add them back
        # to strict_fields; required_fields + field_types (which already allow type(None)) is correct.
        "strict_fields": [
            "rolling_sharpe_252d",
        ],
        "critical": False,
    },
    "sig_eval": {
        "path": "/api/algo/rejection-funnel",
        "method": "GET",
        "description": "Signal evaluation (rejection funnel stats)",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "total",
                "t1",
                "t2",
                "t3",
                "t4",
                "t5",
                "avg_score",
                "signal_date",
                "rejected",
                "data_freshness",
            ],
            field_types={
                "total": int,
                "t1": int,
                "data_freshness": (dict, type(None)),
            },
            description="Signal funnel statistics",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
    "sec_rot": {
        "path": "/api/algo/sector-rotation",
        "method": "GET",
        "description": "Sector rotation signal",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["date", "signal", "strength", "details", "items", "total", "data_freshness"],
            field_types={
                "signal": str,
                "strength": (float, int),
                "items": list,
                "total": int,
                "data_freshness": (dict, type(None)),
            },
            description="Sector rotation signal and strength",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
    "algo_metrics": {
        "path": "/api/algo/metrics",
        "method": "GET",
        "description": "Algo system metrics",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["items"],
            field_types={"items": list},
            description="System metrics",
        ),
        "freshness_max_age_seconds": 300,
        "strict_fields": [],
        "critical": False,
    },
    "market/status": {
        "path": "/api/market/status",
        "method": "GET",
        "description": "Market status and health indicators",
        "response_schema": ResponseSchema(
            required_fields=["date"],
            optional_fields=[
                "market_trend",
                "market_stage",
                "advance_decline_ratio",
                "new_highs_count",
                "new_lows_count",
                "vix_level",
                "put_call_ratio",
            ],
            field_types={"date": str, "vix_level": (int, float)},
            description="Current market status",
        ),
        "freshness_max_age_seconds": 86400,
        "strict_fields": [],
        "critical": False,
    },
    "economic/indicators": {
        "path": "/api/economic/indicators",
        "method": "GET",
        "description": "Economic indicators",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=["indicators"],
            field_types={"indicators": list},
            description="Leading economic indicators",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
    "economic/yield-curve": {
        "path": "/api/economic/yield-curve-full",
        "method": "GET",
        "description": "Yield curve and credit spreads",
        "response_schema": ResponseSchema(
            required_fields=[],
            optional_fields=[
                "currentCurve",
                "spreads",
                "isInverted",
                "history",
                "credit",
                "breakevens",
                "stress",
            ],
            field_types={"currentCurve": dict, "spreads": dict, "isInverted": bool},
            description="Yield curve and financial stress data",
        ),
        "freshness_max_age_seconds": 3600,
        "strict_fields": [],
        "critical": False,
    },
}
