#!/usr/bin/env python3
"""Generate algo_config seeding SQL for schema.sql."""
defaults = [
    ('base_risk_pct', '0.75', 'float', 'Base portfolio risk per trade'),
    ('max_position_size_pct', '8.0', 'float', 'Maximum single position size'),
    ('max_positions', '12', 'int', 'Maximum concurrent positions'),
    ('max_concentration_pct', '50.0', 'float', 'Max concentration in top position'),
    ('halt_drawdown_pct', '20.0', 'float', 'Portfolio drawdown pct to halt trading'),
    ('risk_reduction_at_minus_5', '0.75', 'float', 'Risk pct at -5 pct drawdown'),
    ('risk_reduction_at_minus_10', '0.5', 'float', 'Risk pct at -10 pct drawdown'),
    ('risk_reduction_at_minus_15', '0.25', 'float', 'Risk pct at -15 pct drawdown'),
    ('risk_reduction_at_minus_20', '0.0', 'float', 'Risk pct at -20 pct drawdown halt'),
    ('min_completeness_score', '70', 'int', 'Minimum data completeness pct'),
    ('min_stock_price', '5.0', 'float', 'Minimum stock price dollars'),
    ('min_signal_quality_score', '60', 'int', 'Minimum SQS 0-100'),
    ('min_volume_ma_50d', '300000', 'int', 'Minimum 50-day avg volume'),
    ('min_avg_daily_dollar_volume', '500000', 'float', 'Minimum daily dollar volume'),
    ('require_stock_stage_2', 'true', 'bool', 'Require Stage 2 trend template'),
    ('max_stop_distance_pct', '12.0', 'float', 'Max stop distance pct from entry'),
    ('max_positions_per_sector', '5', 'int', 'Max concurrent positions in one sector'),
    ('max_positions_per_industry', '3', 'int', 'Max concurrent positions in one industry'),
    ('min_swing_score', '55.0', 'float', 'Min swing trader score to enter'),
    ('min_swing_grade', '', 'string', 'Min swing grade override'),
    ('max_total_invested_pct', '95.0', 'float', 'Max pct of portfolio in open positions'),
    ('max_distribution_days', '4', 'int', 'Max market distribution days'),
    ('require_stage_2_market', 'false', 'bool', 'Require market Stage 2 at Tier 2'),
    ('vix_max_threshold', '35.0', 'float', 'VIX level to halt trading'),
    ('vix_caution_threshold', '25.0', 'float', 'VIX level to reduce positions'),
    ('vix_caution_risk_reduction', '0.75', 'float', 'Risk multiplier when VIX caution'),
    ('require_sma50_above_sma200', 'true', 'bool', 'Price and MA alignment'),
    ('min_percent_from_52w_low', '30.0', 'float', 'Min pct from 52w low'),
    ('max_percent_from_52w_high', '25.0', 'float', 'Max pct from 52w high'),
    ('min_trend_template_score', '6', 'int', 'Min Minervini score 0-8'),
    ('max_signal_age_days', '3', 'int', 'Reject BUY signals older than N days'),
    ('min_close_quality_pct', '60.0', 'float', 'Close must be in upper N pct of range'),
    ('min_breakout_volume_ratio', '1.25', 'float', 'Volume must be N x 50-day average'),
    ('require_weekly_stage_2', 'true', 'bool', 'Require weekly chart Stage 2'),
    ('min_rs_line_slope_days', '10', 'int', 'Days for RS line slope check'),
    ('max_rs_pct_from_60d_high', '15.0', 'float', 'Max pct RS-line below 60d high'),
    ('rs_slope_gate_enabled', 'false', 'bool', 'Hard-gate T3 on RS line trending up'),
    ('volume_decay_gate_enabled', 'false', 'bool', 'Hard-gate T3 on volume decay into breakout'),
    ('require_target_pullback', 'false', 'bool', 'Require pullback before partial profit exits'),
    ('t1_target_r_multiple', '1.5', 'float', 'Tier 1 profit target R-mult'),
    ('t2_target_r_multiple', '3.0', 'float', 'Tier 2 profit target R-mult'),
    ('t3_target_r_multiple', '4.0', 'float', 'Tier 3 profit target R-mult'),
    ('imported_position_default_stop_loss_pct', '5.0', 'float', 'Default stop loss pct for imported positions'),
    ('imported_position_default_target_1_pct', '5.0', 'float', 'Default target 1 pct for imported positions'),
    ('imported_position_default_target_2_pct', '10.0', 'float', 'Default target 2 pct for imported positions'),
    ('imported_position_default_target_3_pct', '15.0', 'float', 'Default target 3 pct for imported positions'),
    ('min_hold_days', '1', 'int', 'Minimum days to hold'),
    ('max_hold_days', '20', 'int', 'Max days to hold position'),
    ('exit_on_distribution_day', 'true', 'bool', 'Exit on market distribution'),
    ('exit_on_rs_line_break_50dma', 'true', 'bool', 'Exit when RS line breaks 50-DMA'),
    ('exit_on_td_sequential', 'true', 'bool', 'Exit on TD Sequential exhaustion'),
    ('use_chandelier_trail', 'true', 'bool', 'Use chandelier ATR trailing stop'),
    ('switch_to_21ema_after_days', '10', 'int', 'Days before switching chandelier to 21-EMA'),
    ('eight_week_rule_threshold_pct', '20.0', 'float', 'ONeill 8-week hold threshold pct'),
    ('eight_week_rule_window_days', '21', 'int', 'Days to check for 20pct plus gain'),
    ('chandelier_atr_mult', '3.0', 'float', 'ATR multiplier for chandelier stop'),
    ('move_be_at_r', '1.0', 'float', 'R-multiple to trigger breakeven stop raise'),
    ('pyramid_enabled', 'true', 'bool', 'Enable multi-entry pyramiding'),
    ('pyramid_split_pct', '50,33,17', 'string', 'Entry size split pct'),
    ('pyramid_add_1_gain_pct', '2.0', 'float', 'Gain pct to trigger Add 1'),
    ('pyramid_add_2_gain_pct', '3.0', 'float', 'Additional gain pct to trigger Add 2'),
    ('re_engage_recovery_pct', '8.0', 'float', 'Pct recovery from peak to resume trading'),
    ('re_engage_min_days', '5', 'int', 'Min days after halt before re-engagement'),
    ('require_ftd_to_re_engage', 'true', 'bool', 'Require Follow-Through Day signal'),
    ('max_daily_loss_pct', '2.0', 'float', 'Max daily loss pct before halt'),
    ('max_consecutive_losses', '3', 'int', 'Max consecutive losing trades'),
    ('min_win_rate_pct', '40.0', 'float', 'Min win rate pct to trade'),
    ('max_total_risk_pct', '4.0', 'float', 'Max total open risk pct'),
    ('max_weekly_loss_pct', '5.0', 'float', 'Max weekly loss pct before halt'),
    ('max_data_staleness_days', '3', 'int', 'Max data age in days'),
    ('daily_profit_cap_pct', '2.0', 'float', 'Daily profit cap pct'),
    ('sector_drawdown_halt_pct', '-12.0', 'float', 'Sector drawdown pct to halt trading'),
    ('position_halt_flag_count', '2', 'int', 'Flags to propose early exit'),
    ('max_reentries_per_name', '2', 'int', 'Max times to re-enter same symbol'),
    ('min_days_before_reentry_same_symbol', '5', 'int', 'Days to wait before re-entering symbol'),
    ('halt_entries_before_major_release_minutes', '60', 'int', 'Halt entries N minutes before major release'),
    ('earnings_blackout_days_before', '7', 'int', 'Days before earnings to block entries'),
    ('earnings_blackout_days_after', '3', 'int', 'Days after earnings to block entries'),
    ('min_price_history_days', '200', 'int', 'Min trading days of price history'),
    ('min_daily_volume_shares', '500000', 'int', 'Minimum daily volume shares'),
    ('max_spread_pct', '0.5', 'float', 'Maximum bid-ask spread pct'),
    ('min_market_cap_millions', '300.0', 'float', 'Minimum market cap millions'),
    ('min_float_millions', '50.0', 'float', 'Minimum float shares millions'),
    ('max_short_interest_pct', '30.0', 'float', 'Maximum short interest pct'),
    ('block_days_before_earnings', '5', 'int', 'Block entries N days before earnings'),
    ('max_extension_above_50ma_pct', '15.0', 'float', 'Max extension above 50-DMA pct'),
    ('strong_sector_top_n', '5', 'int', 'Top N sectors count as strong'),
    ('swing_weight_setup', '25', 'int', 'Swing score setup quality weight pct'),
    ('swing_weight_trend', '20', 'int', 'Swing score trend quality weight pct'),
    ('swing_weight_momentum', '20', 'int', 'Swing score momentum RS weight pct'),
    ('swing_weight_volume', '12', 'int', 'Swing score volume weight pct'),
    ('swing_weight_fundamentals', '10', 'int', 'Swing score fundamentals weight pct'),
    ('swing_weight_sector', '8', 'int', 'Swing score sector industry weight pct'),
    ('swing_weight_multi_timeframe', '5', 'int', 'Swing score multi-timeframe weight pct'),
    ('swing_min_trend_score', '5', 'int', 'Swing score minimum Minervini trend score 0-8'),
    ('swing_min_industry_rank', '100', 'int', 'Swing score industry rank threshold'),
    ('swing_days_to_earnings_block', '5', 'int', 'Swing score block entries N days to earnings'),
    ('execution_mode', 'auto', 'string', 'paper or dry or review or auto'),
    ('alpaca_paper_trading', 'false', 'bool', 'Use Alpaca paper account'),
    ('max_trades_per_day', '5', 'int', 'Max new trades per day'),
    ('default_portfolio_value', '100000.0', 'float', 'Bootstrap portfolio value when Alpaca unreachable'),
    ('enable_algo', 'true', 'bool', 'Enable algo trading'),
    ('enable_backtesting', 'false', 'bool', 'Enable backtest mode'),
    ('verbose_logging', 'true', 'bool', 'Detailed logging'),
    ('api_request_timeout_seconds', '5', 'int', 'HTTP request timeout seconds'),
    ('db_connection_timeout_seconds', '15', 'int', 'Database connection timeout seconds'),
]

lines = [
    '',
    '-- ============================================================',
    '-- Seed algo_config defaults (idempotent, ON CONFLICT DO NOTHING)',
    '-- Mirrors AlgoConfig._DEFAULTS in algo/algo_config.py',
    '-- ============================================================',
]
for key, value, vtype, desc in defaults:
    lines.append(
        f"INSERT INTO algo_config (key, value, value_type, description, updated_by) "
        f"VALUES ('{key}', '{value}', '{vtype}', '{desc}', 'schema-seed') "
        f"ON CONFLICT (key) DO NOTHING;"
    )

print('\n'.join(lines))
