#!/usr/bin/env python3
"""Generate frontend configuration from AWS Secrets Manager or environment."""

import json
import os
import sys
from pathlib import Path

# Add repo root to path
REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT))


def get_config():
    """Fetch config from Secrets Manager or use provided values."""
    api_url = os.environ.get("DASHBOARD_API_URL", "")
    pool_id = os.environ.get("COGNITO_USER_POOL_ID", "")
    client_id = os.environ.get("COGNITO_CLIENT_ID", "")

    if not (api_url and pool_id and client_id):
        # Try to fetch from Secrets Manager
        try:
            os.environ.setdefault("AWS_PROFILE", "algo-developer")
            os.environ.setdefault("AWS_DEFAULT_REGION", "us-east-1")

            from config.credential_manager import get_secret

            secret_json = get_secret("algo/dashboard-config", default="{}")
            secret = json.loads(secret_json)

            api_url = api_url or secret.get("api_url", "")
            pool_id = pool_id or secret.get("cognito_user_pool_id", "")
            client_id = client_id or secret.get("cognito_user_pool_client_id", "")
        except Exception as e:
            print(
                f"Warning: Could not fetch from Secrets Manager: {e}", file=sys.stderr
            )

    if not (api_url and pool_id and client_id):
        print("Error: Missing required configuration", file=sys.stderr)
        print(f"  DASHBOARD_API_URL: {api_url or 'NOT SET'}", file=sys.stderr)
        print(f"  COGNITO_USER_POOL_ID: {pool_id or 'NOT SET'}", file=sys.stderr)
        print(f"  COGNITO_CLIENT_ID: {client_id or 'NOT SET'}", file=sys.stderr)
        sys.exit(1)

    # Extract region from pool ID
    pool_region = pool_id.split("_")[0] if "_" in pool_id else "us-east-1"
    cognito_domain = f"{pool_region}.auth.us-east-1.amazoncognito.com"

    return {
        "api_url": api_url,
        "pool_id": pool_id,
        "client_id": client_id,
        "cognito_domain": cognito_domain,
    }


def generate_config_js(config):
    """Generate JavaScript config file."""
    js_content = """// Runtime configuration - Auto-generated by setup-frontend-config.py
// Do not commit this file to version control

window.__CONFIG__ = {{
  API_URL: "{config['api_url']}",
  USER_POOL_ID: "{config['pool_id']}",
  USER_POOL_CLIENT_ID: "{config['client_id']}",
  USER_POOL_DOMAIN: "{config['cognito_domain']}",
  BUILD_TIME: new Date().toISOString(),
  VERSION: '1.0.0-dev',
  ENVIRONMENT: 'development',
}};

console.log('[Config] Frontend environment loaded');
"""
    return js_content


def main():
    """Generate and write frontend config."""
    config = get_config()
    js_content = generate_config_js(config)

    # Write to public/config.js
    config_path = REPO_ROOT / "webapp" / "frontend" / "public" / "config.js"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    config_path.write_text(js_content, encoding="utf-8")
    print(f"[OK] Config written to {config_path.relative_to(REPO_ROOT)}")
    print(f"  API URL: {config['api_url']}")
    print(f"  Pool ID: {config['pool_id']}")


if __name__ == "__main__":
    main()
