#!/usr/bin/env pwsh
# Generate frontend config.js for local development
# This mirrors what the GitHub Actions deploy workflow does, but with dev values

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ConfigFile = "webapp/frontend/public/config.js"

# Development configuration
$config = @"
// Frontend Runtime Configuration (generated for local development)
// Generated by: scripts/setup-frontend-dev-config.ps1
// Do NOT commit this file (it's in .gitignore)
window.__CONFIG__ = {
  "API_URL": "",
  "USER_POOL_ID": "us-east-1_XJpLb9SKX",
  "USER_POOL_CLIENT_ID": "6smb0vrcidd9kvhju2kn2a3qrl",
  "USER_POOL_DOMAIN": "https://algo-dev.auth.us-east-1.amazoncognito.com",
  "AWS_REGION": "us-east-1",
  "ENVIRONMENT": "development"
};
"@

# Write the config file
Set-Content -Path $ConfigFile -Value $config -Encoding UTF8

Write-Host "OK - Generated $ConfigFile for local development" -ForegroundColor Green
Write-Host "  API_URL: (empty - uses Vite proxy to localhost:3001)" -ForegroundColor Gray
Write-Host "  ENVIRONMENT: development" -ForegroundColor Gray
