#!/bin/bash
# Update frontend config.js with correct API URL after deployment
# Usage: ./scripts/update-frontend-config.sh <API_URL> [CloudFront_Domain]

set -e

API_URL="${1:-}"
CLOUDFRONT_DOMAIN="${2:-}"

if [ -z "$API_URL" ]; then
  echo "❌ ERROR: API_URL is required"
  echo "Usage: ./scripts/update-frontend-config.sh <API_URL> [CloudFront_Domain]"
  echo ""
  echo "Examples:"
  echo "  ./scripts/update-frontend-config.sh https://api.example.com"
  echo "  ./scripts/update-frontend-config.sh https://abc123.lambda-url.us-east-1.on.aws d123456.cloudfront.net"
  exit 1
fi

echo "🔄 Updating frontend configuration..."
echo "  API_URL: $API_URL"
echo "  CloudFront: ${CLOUDFRONT_DOMAIN:-(none)}"

# Create config.js in public/ directory
CONFIG_JS="webapp/frontend/public/config.js"
cat > "$CONFIG_JS" <<EOF
// Runtime configuration - Production Environment
// Auto-generated by update-frontend-config.sh
window.__CONFIG__ = {
  "API_URL": "$API_URL",
  "USER_POOL_ID": "",
  "USER_POOL_CLIENT_ID": "",
  "USER_POOL_DOMAIN": "",
  "BUILD_TIME": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)",
  "VERSION": "1.0.1",
  "ENVIRONMENT": "production"
};
EOF

echo "✅ Updated $CONFIG_JS with API_URL=$API_URL"

# If CloudFront domain provided, create .env for S3 upload
if [ -n "$CLOUDFRONT_DOMAIN" ]; then
  ENV_FILE="webapp/frontend/.env.s3deploy"
  cat > "$ENV_FILE" <<EOF
# S3 deployment configuration
CF_DOMAIN=$CLOUDFRONT_DOMAIN
API_URL=$API_URL
EOF
  echo "✅ Created $ENV_FILE for S3 deployment"
  echo ""
  echo "📤 Next step: Upload dist/ to S3 bucket"
  echo "   aws s3 sync webapp/frontend/dist/ s3://your-bucket/ --delete"
  echo "   aws cloudfront create-invalidation --distribution-id <ID> --paths '/*'"
fi
