#!/bin/bash

# Setup development environment with production API for testing
# This allows testing the auth flow against the real deployed stack

set -e

echo "🚀 Setting up development environment with production API..."

# Known production API URL
API_URL="https://ye9syrnj8c.execute-api.us-east-1.amazonaws.com/dev"

# Update frontend environment
cd frontend

echo "📝 Creating development environment configuration..."

cat > .env.development << EOF
# Development Environment with Production API
VITE_API_URL=$API_URL
VITE_SERVERLESS=true
VITE_ENVIRONMENT=dev

# AWS Cognito Configuration - Leave empty to use development mode
VITE_COGNITO_USER_POOL_ID=
VITE_COGNITO_CLIENT_ID=
VITE_AWS_REGION=us-east-1
VITE_COGNITO_DOMAIN=
VITE_COGNITO_REDIRECT_SIGN_IN=http://localhost:3000
VITE_COGNITO_REDIRECT_SIGN_OUT=http://localhost:3000

# Development flags
VITE_ENABLE_DEBUG=true
VITE_ENABLE_MOCK_DATA=false
EOF

# Update runtime config
cat > public/config.js << EOF
// Runtime configuration - Development Environment
// This file is auto-generated by setup-dev-with-prod-api.sh
window.__CONFIG__ = {
  "API_URL": "$API_URL",
  "BUILD_TIME": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "VERSION": "1.0.0-dev",
  "ENVIRONMENT": "development"
};
EOF

cd ..

# Update lambda environment
echo "📝 Updating lambda environment..."

cd lambda

cat > .env << EOF
# Local development environment variables
NODE_ENV=development
DB_HOST=localhost
DB_PORT=5432
DB_NAME=stocks
DB_USER=postgres
DB_PASSWORD=password

# AWS Cognito Configuration - Leave empty for development mode
COGNITO_USER_POOL_ID=
COGNITO_CLIENT_ID=
AWS_REGION=us-east-1
WEBAPP_AWS_REGION=us-east-1
EOF

cd ..

echo "✅ Development environment configured!"
echo ""
echo "🔧 Configuration:"
echo "  Frontend points to: $API_URL"
echo "  Authentication: Development mode (bypassed)"
echo "  Local Lambda: Will run on port 3001 (for local testing)"
echo ""
echo "🚀 Next steps:"
echo "  1. cd frontend && npm run dev"
echo "  2. Visit http://localhost:3000"
echo "  3. Authentication will work in development mode"
echo ""
echo "💡 To use real Cognito values, run: ./get-cognito-config.sh"