name: Auto-Sync Documentation Routine

on:
  # Trigger after any push to main branch
  push:
    branches: [ main, loaddata ]
  
  # Trigger on pull request merge
  pull_request:
    types: [ closed ]
    branches: [ main ]
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force full document sync'
        required: false
        default: 'false'
        type: boolean

  # Schedule to run daily at 9 AM UTC
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-sync-docs:
    name: Auto-Sync Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install --no-save
          # Add any additional dependencies needed for document analysis
      
      - name: Run Auto-Sync Documentation Routine
        id: auto-sync
        run: |
          echo "🔄 Starting Auto-Sync Documentation Routine..."
          
          # Run the auto-sync script
          node auto-sync-docs.js
          
          # Check if any changes were made
          if git diff --quiet; then
            echo "No changes detected"
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create documentation update PR
        if: steps.auto-sync.outputs.changes_made == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Auto-sync documentation updates
            
            - Updated core documents for consistency
            - Synced todo list with current priorities
            - Generated next actions from document analysis
            
            🤖 Generated by Auto-Sync Documentation Routine
          title: 'Auto-Sync: Documentation Updates'
          body: |
            ## Auto-Sync Documentation Updates
            
            This PR contains automated updates to keep our 4 core documents in sync:
            
            ### Changes Made:
            - 📖 **CLAUDE.md**: Operational guidelines (read-only reference)
            - 📋 **FINANCIAL_PLATFORM_BLUEPRINT.md**: Updated with current implementation status
            - 🎯 **DESIGN.md**: Refreshed system architecture and resolved issues
            - 🧪 **TEST_PLAN.md**: Updated testing status and priorities
            - ✅ **claude-todo.md**: Synced with identified gaps and priorities
            
            ### Next Actions Identified:
            See `auto-sync-report.json` for detailed analysis and recommended next steps.
            
            ### Workflow:
            1. Review the changes in this PR
            2. Merge to trigger development workflow
            3. Development will proceed based on updated claude-todo.md priorities
            
            🤖 This PR was automatically generated by the Auto-Sync Documentation Routine.
          branch: auto-sync-docs-${{ github.run_number }}
          delete-branch: true
      
      - name: Upload sync report
        uses: actions/upload-artifact@v4
        with:
          name: auto-sync-report
          path: auto-sync-report.json
          retention-days: 30
      
      - name: Comment on recent commits
        if: steps.auto-sync.outputs.changes_made == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            let reportContent = 'Auto-sync report not found';
            try {
              const report = JSON.parse(fs.readFileSync('auto-sync-report.json', 'utf8'));
              reportContent = `
            ## 🔄 Auto-Sync Documentation Routine Completed
            
            **Next Actions Identified:**
            ${report.nextActions.map(action => `- ${action.content}`).join('\\n')}
            
            **Workflow Recommendation:**
            ${report.recommendedWorkflow.step1}
            ${report.recommendedWorkflow.step2}
            ${report.recommendedWorkflow.step3}
            
            **Next Priority:** ${report.recommendedWorkflow.nextAction}
            
            See auto-sync-report.json for full details.
            `;
            } catch (error) {
              console.error('Error reading sync report:', error);
            }
            
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: reportContent
            });