name: deploy-rds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_rds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Deploy RDS stack
        run: |
          aws cloudformation deploy \
            --stack-name rds-stack \
            --template-file rds-template.yml \
            --parameter-overrides \
              RDSUsername=${{ secrets.RDS_USERNAME }} \
              RDSPassword=${{ secrets.RDS_PASSWORD }} \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Show RDS outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name rds-stack \
            --query "Stacks[0].Outputs" --output table
