# .github/workflows/deploy-core.yml
name: Deploy core infrastructure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Cleanup failed core stack if needed
        run: |
          STATUS=$(aws cloudformation describe-stacks \
            --stack-name stocks-core-stack \
            --query "Stacks[0].StackStatus" \
            --output text 2>/dev/null || echo "NOT_FOUND")
          if [ "$STATUS" = "ROLLBACK_COMPLETE" ]; then
            echo "Found ROLLBACK_COMPLETE – deleting core stack..."
            aws cloudformation delete-stack --stack-name stocks-core-stack
            aws cloudformation wait stack-delete-complete --stack-name stocks-core-stack
          fi

      - name: Deploy core CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name stocks-core-stack \
            --template-file template-core.yml \
            --capabilities CAPABILITY_NAMED_IAM
