# File: .github/workflows/deploy-aws.yml
name: deploy-aws

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Debug: list files"
        run: ls -R .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name HelloWorldStack \
            --template-file template.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Invoke function for test
        run: |
          aws lambda invoke \
            --function-name HelloWorldFunction \
            --payload '{}' \
            response.json
          cat response.json
