name: deploy-iam

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_iam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Debug: list files"
        run: ls -R .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Deploy IAM stack
        run: |
          aws cloudformation deploy \
            --stack-name iam-stack \
            --template-file iam-template.yml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Show IAM outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name iam-stack \
            --query "Stacks[0].Outputs" --output table
