# .github/workflows/deploy-core.yml
name: Deploy core infrastructure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Deploy core CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name stocks-core-stack \
            --template-file template-core.yml \
            --capabilities CAPABILITY_NAMED_IAM
