# .github/workflows/deploy-nested.yml
name: Deploy nested CloudFormation stacks

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  S3_BUCKET: your-cfn-templates-bucket
  S3_PATH:    cloudformation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Upload CFN templates to S3
        run: |
          for f in template-core.yml template-app-stocks.yml template-app-ecs-tasks.yml template-parent.yml; do
            aws s3 cp "$f" "s3://${S3_BUCKET}/${S3_PATH}/$f" --acl private
          done

      - name: Deploy parent stack
        run: |
          aws cloudformation deploy \
            --stack-name stocks-all-in-one-stack \
            --template-url "https://${S3_BUCKET}.s3.amazonaws.com/${S3_PATH}/template-parent.yml" \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              VpcCidr=${{ secrets.VPC_CIDR }} \
              PublicSubnetCidr1=${{ secrets.PUBLIC_SUBNET1_CIDR }} \
              PublicSubnetCidr2=${{ secrets.PUBLIC_SUBNET2_CIDR }} \
              PrivateSubnetCidr1=${{ secrets.PRIVATE_SUBNET1_CIDR }} \
              PrivateSubnetCidr2=${{ secrets.PRIVATE_SUBNET2_CIDR }} \
              CodeKey=${{ needs.build_and_upload_lambda.outputs.code_key }} \
              RDSUsername=${{ secrets.RDS_USERNAME }} \
              RDSPassword=${{ secrets.RDS_PASSWORD }} \
              ImageTag=${{ needs.build_and_push_container.outputs.tag }}
