name: Simple Test

on:
  push:
    branches: [ main, initialbuild ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Test
        run: |
          echo "GitHub Actions is working!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"